import React,{useState} from 'react';
export function AiSubcodes({api,project,operate,jump}){
 const [codeId,setCodeId]=useState(''),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const review=['owner','reviewer'].includes(project.role);
 async function run(fn){setBusy(true);setMessage('');try{await fn();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 function edit(i,key,value){setResult(r=>({...r,proposals:r.proposals.map((p,j)=>j===i?{...p,[key]:value}:p)}));}
 return <section className="settings-card"><h2>Evidence-grounded subcode drafts</h2><p>Read parent-code quotations and draft more specific codes with a connected model. Edit and choose proposals before a reviewer adds them. Existing coding stays attached to its original code.</p><label>Parent code<select aria-label="Subcode parent" value={codeId} disabled={busy} onChange={e=>{setCodeId(e.target.value);setResult(null);}}><option value="">Choose an active code</option>{project.state.codes.filter(c=>!c.archivedAt&&c.codable!==false).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button disabled={busy||!review||!codeId} onClick={()=>run(async()=>{const r=await api('/projects/'+project.id+'/ai-review',{method:'POST',body:{mode:'subcodes',codeId,decisionScope:'accepted'}});setResult({...r,proposals:r.proposals.map(p=>({...p,selected:false}))});})}>Draft subcodes from accepted evidence</button>
 {result&&<><p>{result.sent} of {result.total} accepted passages sent. {result.sampling} · {result.model}</p>{!result.proposals.length&&<p>No supported new subcodes were returned.</p>}{result.proposals.map((p,i)=><article className="memo-card" key={i}><label><input type="checkbox" checked={p.selected} onChange={e=>edit(i,'selected',e.target.checked)}/> Include proposal</label><label>Name<input aria-label={'Subcode draft name '+(i+1)} value={p.name} onChange={e=>edit(i,'name',e.target.value)}/></label><label>Inclusion definition<textarea aria-label={'Subcode draft definition '+(i+1)} value={p.description} onChange={e=>edit(i,'description',e.target.value)}/></label>{p.citations.map(c=><button className="quote-link" key={c.id} onClick={()=>jump(c)}>{c.text}</button>)}</article>)}<button disabled={busy||!review||!result.proposals.some(p=>p.selected)} onClick={()=>run(async()=>{await operate('subcodes.apply',{parentId:result.codeId,model:result.model,coverage:result.coverage,proposals:result.proposals.filter(p=>p.selected)});setResult(null);setMessage('Reviewed subcodes added. Apply them to passages in a separate coding decision.');})}>Add selected reviewed subcodes</button></>}{message&&<p role="status">{message}</p>}</section>;
}
