import React,{useMemo,useState} from 'react';
import {Download} from 'lucide-react';
import {download} from '../exchange.js';
import {annotatedSourceModel,annotatedSourceHTML,annotatedSourceDOCX} from '../annotated-source-export.mjs';

export function AnnotatedSourceExport({state,documentId}){
 const [coder,setCoder]=useState(''),[status,setStatus]=useState('all'),[error,setError]=useState('');
 const doc=state.documents.find(d=>d.id===documentId),coders=[...new Set((state.codings||[]).filter(c=>c.documentId===documentId&&!c.deletedAt).map(c=>c.coder))].sort();
 const preview=useMemo(()=>{try{return {model:annotatedSourceModel(state,documentId,{coder,status})};}catch(e){return {error:e.message};}},[state,documentId,coder,status]);
 if(!doc)return null;
 function save(format){setError('');try{const name=(doc.name||'source').replace(/[^\p{L}\p{N}._ -]/gu,'_').slice(0,100)||'source',options={coder,status};if(format==='html')download(name+'.annotated.html',annotatedSourceHTML(state,documentId,options),'text/html');else download(name+'.annotated.docx',annotatedSourceDOCX(state,documentId,options),'application/vnd.openxmlformats-officedocument.wordprocessingml.document');}catch(e){setError(e.message);}}
 return <section className="viz-card" aria-label="Annotated source export"><h2>Export a source with coding highlights</h2><p>Share the transcript with overlapping codes, researcher attribution and an exact quotation ledger. Restricted passages appear as placeholders. Private notes, review rationales, arbitrary source attributes and recording bytes are omitted.</p><div className="filterbar"><label className="field"><span>Researcher</span><select aria-label="Annotated source researcher" value={coder} onChange={e=>setCoder(e.target.value)}><option value="">All available coders</option>{coders.map(c=><option key={c} value={c}>{c||'Unattributed'}</option>)}</select></label><label className="field"><span>Coding layer</span><select aria-label="Annotated source coding layer" value={status} onChange={e=>setStatus(e.target.value)}>{['all','coded','provisional','accepted','flagged'].map(s=><option key={s} value={s}>{s==='all'?'All current text decisions':s}</option>)}</select></label></div>{preview.model&&<p className="muted">{preview.model.applications.length} eligible text applications · {preview.model.excludedApplications} selected applications excluded · {preview.model.restrictedRanges} restricted intervals. Counts describe decisions, not thematic prevalence.</p>}{(error||preview.error)&&<p className="error-banner" role="alert">{error||preview.error}</p>}<div className="actions"><button disabled={!!preview.error} onClick={()=>save('html')}><Download size={16}/> Download annotated HTML</button><button disabled={!!preview.error} onClick={()=>save('docx')}><Download size={16}/> Download annotated Word document</button></div><p className="muted">Open the HTML file in a browser to print or save as PDF. These files contain text and coding references; use the project ZIP to preserve the complete project.</p></section>;
}
