import {exportCodeSetJSON,exportCodeSetQDC} from '../code-set-export.mjs';
import {download} from '../exchange.js';
import React,{useState} from 'react';
import {previewAutocoding} from '../autocoding.mjs';
export function Autocoding({project,me,operate,jump}){
 const s=project.state,canWrite=project.role!=='viewer',actor=me?.user?.id||me?.userId||me?.id;
 const [rule,setRule]=useState({mode:'literal',pattern:'',caseSensitive:false,codeId:''}),[sources,setSources]=useState([]),[preview,setPreview]=useState(null),[selected,setSelected]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[setName,setSetName]=useState(''),[setCodes,setSetCodes]=useState([]);
 const run=async fn=>{setError('');setBusy(true);try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const invalidate=()=>{setPreview(null);setSelected([]);};
 return <section className="settings-card"><h2>Reviewed autocoding & named code sets</h2><p>Literal or restricted regex finds exact passages locally. Preview and select each candidate before applying. Undo removes only your unchanged decisions from that run; reviewed or edited decisions remain.</p>{error&&<p role="alert">{error}</p>}
 <div className="field"><label>Existing code<select value={rule.codeId} disabled={!canWrite||busy} onChange={e=>{setRule({...rule,codeId:e.target.value});invalidate();}}><option value="">Choose a code</option>{s.codes.filter(c=>c.codable!==false&&!c.archivedAt).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>
 <label>Match mode<select value={rule.mode} onChange={e=>{setRule({...rule,mode:e.target.value});invalidate();}}><option value="literal">Literal text</option><option value="regex">Restricted regex</option></select></label>
 <label>Pattern<input value={rule.pattern} onChange={e=>{setRule({...rule,pattern:e.target.value});invalidate();}}/></label><label><input type="checkbox" checked={rule.caseSensitive} onChange={e=>{setRule({...rule,caseSensitive:e.target.checked});invalidate();}}/> Case sensitive</label>
 {rule.mode==='regex'&&<p>Supports character classes, alternation, anchors and bounded repetitions up to 100. Groups, lookarounds, backreferences and unbounded repetitions are blocked.</p>}
 <label>Sources (none selected means all interview sources)<select multiple value={sources} onChange={e=>{setSources([...e.target.selectedOptions].map(o=>o.value));invalidate();}}>{s.documents.filter(d=>d.sourceRole!=='reference').map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>
 <button disabled={!canWrite||busy} onClick={()=>run(()=>{const next=previewAutocoding(s,rule,{documentIds:sources});setPreview(next);setSelected([]);})}>Preview exact matches</button>
 {preview&&<><p>{preview.returned} of {preview.total} eligible matches displayed. {preview.truncated?'Narrow the source scope to inspect the remaining matches.':''} Consent-review ranges are skipped. This local tool can process sources excluded from remote AI.</p><button onClick={()=>setSelected(preview.matches.map(m=>m.key))}>Select displayed candidates</button><button onClick={()=>setSelected([])}>Clear selection</button>
 {preview.matches.map(m=><div className="review-card" key={m.key}><label><input type="checkbox" checked={selected.includes(m.key)} onChange={e=>setSelected(e.target.checked?[...selected,m.key]:selected.filter(k=>k!==m.key))}/> {s.documents.find(d=>d.id===m.documentId)?.name} · {m.start}–{m.end}</label><p>{m.text}</p><button onClick={()=>jump(m)}>Read context</button></div>)}
 <button disabled={!canWrite||busy||!selected.length} onClick={()=>run(async()=>{await operate('autocoding.apply',{rule:preview.rule,matches:preview.matches.filter(m=>selected.includes(m.key))});invalidate();})}>Apply {selected.length} reviewed candidates</button></>}
 {(s.autocodingRuns||[]).map(r=><div key={r.id}><p>{r.date} · {r.rule.mode}: {r.rule.pattern} · {r.codingIds.length} applications{r.undoneAt?' · Undone; '+r.retainedIds.length+' changed decisions retained':''}</p>{!r.undoneAt&&(!actor||r.actor===actor)&&<button disabled={!canWrite||busy} onClick={()=>run(()=>operate('autocoding.undo',{id:r.id}))}>Undo my run</button>}</div>)}
 <h3>Named code sets</h3><p>Save a reusable selection of existing codes. Export its definitions and necessary ancestor hierarchy as a portable JSON or QDC codebook; interviews and coding decisions are excluded.</p><label>Set name<input value={setName} onChange={e=>setSetName(e.target.value)}/></label><label>Codes<select multiple value={setCodes} onChange={e=>setSetCodes([...e.target.selectedOptions].map(o=>o.value))}>{s.codes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button disabled={!canWrite||busy} onClick={()=>run(async()=>{await operate('codeSet.save',{name:setName,codeIds:setCodes});setSetName('');setSetCodes([]);})}>Save code set</button>
 {(s.codeSets||[]).map(set=><div key={set.id}><strong>{set.name}</strong><button disabled={busy} onClick={()=>run(()=>download('named-codebook.json',exportCodeSetJSON(s,set.id),'application/json'))}>Export collection JSON</button><button disabled={busy} onClick={()=>run(()=>download('named-codebook.qdc',exportCodeSetQDC(s,set.id),'application/xml'))}>Export collection QDC</button><p>{set.codeIds.map(id=>s.codes.find(c=>c.id===id)?.name||'Removed code').join(', ')}</p><button onClick={()=>{setSetName(set.name);setSetCodes(set.codeIds);}}>Use selection</button><button disabled={!canWrite||busy} onClick={()=>run(()=>operate('codeSet.delete',{id:set.id}))}>Remove set</button></div>)}</section>;
}
