import React,{useState} from 'react';
import {readTable,casesFromTable} from '../tabular-import.mjs';
import {decodeSourceText,sourceByteProvenance,TEXT_ENCODINGS} from '../source-text-import.mjs';
export function CaseTableImport({state,disabled,onImport}){
 const [file,setFile]=useState(null),[table,setTable]=useState(null),[mapping,setMapping]=useState({}),[encoding,setEncoding]=useState('auto'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[provenance,setProvenance]=useState(null);
 async function load(next,enc){setFile(next);setTable(null);setError('');if(!next)return;try{const rows=await readTable(next,{encoding:enc}),xlsx=next.name.toLowerCase().endsWith('.xlsx'),bytes=new Uint8Array(await next.arrayBuffer());setProvenance(await sourceByteProvenance(bytes,next,xlsx?'xlsx':'csv',{encoding:xlsx?'archive-xml':decodeSourceText(bytes,enc).encoding,losses:xlsx?['Only the first worksheet is imported; formulas use stored values, styles and workbook metadata are omitted.']:[]}));setTable(rows);const headers=rows[0]?.map(String)||[];setMapping({nameColumn:headers.includes('name')?'name':'',sourceColumn:headers.includes('sources')?'sources':'',memoColumn:headers.includes('memo')?'memo':''});}catch(e){setError(e.message);}}
 let preview=[],previewError='';if(table&&mapping.nameColumn)try{preview=casesFromTable(table,state,{...mapping,provenance});}catch(e){previewError=e.message;}
 const headers=table?.[0]?.map(h=>String(h).trim())||[];
 return <section className="settings-card"><h2>Import a case table</h2><p>Choose the column containing case names. Other columns become attributes; source links require exact names or IDs. CSV values remain text until a declared attribute type converts them.</p><div className="filterbar"><label className="button">Preview CSV / XLSX<input aria-label="Case table file" type="file" accept=".csv,.xlsx" disabled={disabled||busy} onChange={e=>{load(e.target.files?.[0]||null,encoding);e.target.value='';}}/></label><label>CSV encoding<select aria-label="Case table encoding" value={encoding} disabled={busy} onChange={e=>{setEncoding(e.target.value);if(file)load(file,e.target.value);}}>{TEXT_ENCODINGS.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>{table&&<><div className="filterbar">{[['nameColumn','Case name column'],['sourceColumn','Source links column'],['memoColumn','Memo column']].map(([key,label])=><label key={key}>{label}<select aria-label={label} value={mapping[key]||''} disabled={busy} onChange={e=>setMapping({...mapping,[key]:e.target.value})}><option value="">{key==='nameColumn'?'Choose column':'None'}</option>{headers.map((h,i)=><option value={h} key={i}>{h||'(empty header)'}</option>)}</select></label>)}</div><p>{table.length-1} rows · {provenance?.encoding}. Nothing imported yet.</p>{!mapping.nameColumn&&<p>Select a case name column to build the preview.</p>}{preview.length>0&&<><h3>Import preview · {preview.length} cases</h3><pre style={{overflow:'auto'}}>{JSON.stringify(preview.slice(0,5).map(({importProvenance,...row})=>row),null,2)}</pre><button disabled={disabled||busy||!!previewError} onClick={async()=>{setBusy(true);setError('');try{if(await onImport(preview)===false)throw Error('Case import was not saved. Review the message above.');setFile(null);setTable(null);}catch(e){setError(e.message);}finally{setBusy(false);}}}>Import these cases</button></>}<button disabled={busy} onClick={()=>{setFile(null);setTable(null);setError('');}}>Cancel table import</button></>}{(error||previewError)&&<p role="alert">{error||previewError}</p>}</section>;
}
