import React,{useMemo,useState} from 'react';
import {coverageProfile,coderOverlapProfile,coverageExportRows,overlapExportRows,coverageSVG} from '../coverage-profile.mjs';
import {safeCSV} from '../report-export.mjs';
import {download} from '../exchange.js';
import {ChartExportButtons} from './chart-export.jsx';
import './coverage-profile.css';

const number=value=>value==null?'N/A':Number(value.toFixed(2)).toLocaleString();
export function CoverageProfile({state,filters,scope,onDrill}){
  const [view,setView]=useState('coverage'),[metric,setMetric]=useState('coveragePercent'),[rowMode,setRowMode]=useState('subtree');
  const profile=useMemo(()=>coverageProfile(state,filters,{rowMode}),[state,filters,rowMode]),overlap=useMemo(()=>view==='overlap'?coderOverlapProfile(state,filters):null,[state,filters,view]);
  const max=metric==='coveragePercent'?100:Math.max(1,...profile.codeRows.flatMap(c=>c.cells.map(cell=>cell[metric]||0)));
  return <section className="coverage-profile"><div className="filterbar"><button className={view==='coverage'?'active':''} onClick={()=>setView('coverage')}>Normalized text coverage</button><button className={view==='overlap'?'active':''} onClick={()=>setView('overlap')}>Coder overlap heatmap</button></div>
    {view==='coverage'?<><h2>Compare coding relative to eligible transcript length</h2><p className="muted">{profile.method}</p><div className="filterbar"><label>Normalized measure<select aria-label="Normalized analysis measure" value={metric} onChange={e=>setMetric(e.target.value)}><option value="coveragePercent">Eligible text coverage (%)</option><option value="applicationsPer1000">Applications per 1000 eligible codepoints</option></select></label><label>Coverage rows<select aria-label="Normalized coverage rows" value={rowMode} onChange={e=>setRowMode(e.target.value)}>{[['direct','Direct codes'],['subtree','Include descendants'],['categories','Code categories'],['all','All codes']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><button onClick={()=>download('normalized-text-coverage.csv',safeCSV(coverageExportRows(profile,{scope})),'text/csv')}>Export coverage CSV</button><ChartExportButtons name="normalized-text-coverage" svg={()=>coverageSVG(profile,{metric,scope})} svgLabel="Export coverage SVG" pngLabel="Export coverage PNG"/></div>
      <p className="muted">{profile.sources.reduce((n,c)=>n+c.eligibleCodepoints,0).toLocaleString()} eligible codepoints across {profile.sources.length} scoped sources. Parent rows and codes can share evidence; percentages across codes must not be added. Rates count each saved application, including coder layers. N/A means no eligible text.</p>
      {!profile.sources.length&&<p>No eligible sources match this scope.</p>}<div className="coverage-bars" aria-label="Normalized source coding comparison">{profile.codeRows.filter(code=>code.cells.some(c=>c.applications)).map(code=><div key={code.id}><h3>{code.name}</h3>{code.cells.map(cell=><button className="coverage-bar" key={cell.sourceId} aria-label={`${code.name} in ${cell.sourceName}: ${number(cell[metric])}${metric==='coveragePercent'?' percent':' applications per 1000 codepoints'}`} onClick={()=>onDrill(code.name+' · '+cell.sourceName,cell.rows)}><span>{cell.sourceName}</span><i><b style={{width:(cell[metric]==null?0:cell[metric]/max*100)+'%'}}/></i><strong>{number(cell[metric])}{metric==='coveragePercent'&&cell[metric]!=null?'%':''}</strong></button>)}</div>)}</div>
      <div className="table-wrap"><table><thead><tr><th>Code</th><th>Source</th><th>Eligible codepoints</th><th>Covered union</th><th>Coverage</th><th>Applications</th><th>Applications / 1000</th></tr></thead><tbody>{profile.codeRows.flatMap(code=>code.cells.map(cell=><tr key={code.id+':'+cell.sourceId}><th>{code.name}</th><td><button onClick={()=>onDrill(code.name+' · '+cell.sourceName,cell.rows)}>{cell.sourceName}</button></td><td>{cell.eligibleCodepoints.toLocaleString()}</td><td>{cell.coveredCodepoints.toLocaleString()}</td><td>{number(cell.coveragePercent)}{cell.coveragePercent!=null?'%':''}</td><td>{cell.applications}</td><td>{number(cell.applicationsPer1000)}</td></tr>))}</tbody></table></div></>:<><h2>Saved coder decisions · text overlap</h2><p className="muted">{overlap.method}</p><p>Select a cell to read that pair’s evidence. Different codes and sources remain separate dimensions even when selections have identical positions. The active filters above apply to this comparison.</p><div className="filterbar"><button onClick={()=>download('coder-overlap-heatmap.csv',safeCSV(overlapExportRows(overlap,{scope})),'text/csv')}>Export overlap CSV</button></div>{overlap.coders.length<2&&<p>At least two coder identities with eligible text coding are needed for a pair comparison. Existing AI identities describe agent decisions.</p>}<div className="table-wrap"><table className="coder-overlap"><caption>Jaccard overlap · 0 = no shared code coverage; 1 = identical coverage</caption><thead><tr><th>Coder</th>{overlap.coders.map(coder=><th key={coder}>{coder}</th>)}</tr></thead><tbody>{overlap.cells.map((cells,i)=><tr key={overlap.coders[i]}><th>{overlap.coders[i]}</th>{cells.map(cell=><td key={cell.b} style={{background:cell.jaccard==null?'#f2f2f2':`rgba(68,126,150,${.08+.55*cell.jaccard})`}}><button aria-label={`${cell.a} versus ${cell.b}: Jaccard ${number(cell.jaccard)}, intersection ${cell.intersection}, union ${cell.union}`} onClick={()=>onDrill(cell.a+' ↔ '+cell.b+' · Jaccard '+number(cell.jaccard),cell.rows)}><strong>{number(cell.jaccard)}</strong><small>{cell.intersection.toLocaleString()} / {cell.union.toLocaleString()} codepoints</small></button></td>)}</tr>)}</tbody></table></div></>}
  </section>;
}
