import React,{useMemo,useState} from 'react';
import {compareMediaCoders,mediaComparisonScope,mediaComparisonExportRows} from '../media-comparison.mjs';
import {safeCSV} from '../report-export.mjs';
import {download} from '../exchange.js';
export function MediaComparison({state:s,jump}){
 const [sourceId,setSource]=useState(''),[status,setStatus]=useState('all'),[codeId,setCode]=useState(''),[a,setA]=useState(''),[b,setB]=useState(''),[evidence,setEvidence]=useState(null);
 const scope=useMemo(()=>mediaComparisonScope(s,{sourceId,status,codeId}),[s,sourceId,status,codeId]),coders=[...new Set(scope.codings.map(c=>c.coder))],result=useMemo(()=>a&&b&&a!==b?compareMediaCoders(s,a,b,{sourceId,status,codeId}):null,[s,a,b,sourceId,status,codeId]);
 const pick=(change,value)=>{change(value);setEvidence(null);},display=n=>Number(n.toFixed(6)).toLocaleString();
 return <section className="settings-card media-comparison"><h2>Recording & region coder comparison</h2><p>Compare coded recording intervals and image/PDF regions separately from the text comparison above.</p><div className="filterbar"><label>Media comparison source<select aria-label="Media comparison source" value={sourceId} onChange={e=>pick(setSource,e.target.value)}><option value="">All eligible media sources</option>{s.documents.filter(d=>d.mediaKey&&d.sourceRole!=='reference').map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Media decision scope<select aria-label="Media decision scope" value={status} onChange={e=>pick(setStatus,e.target.value)}>{['all','coded','accepted','provisional','flagged'].map(v=><option key={v}>{v}</option>)}</select></label><label>Media comparison code<select aria-label="Media comparison code" value={codeId} onChange={e=>pick(setCode,e.target.value)}><option value="">All codes</option>{s.codes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>First media coder<select aria-label="First media coder" value={a} onChange={e=>pick(setA,e.target.value)}><option value="">Choose coder</option>{coders.map(c=><option key={c}>{c}</option>)}</select></label><label>Second media coder<select aria-label="Second media coder" value={b} onChange={e=>pick(setB,e.target.value)}><option value="">Choose coder</option>{coders.map(c=><option key={c}>{c}</option>)}</select></label></div><p className="muted">{scope.method}</p><p className="muted">Excluded scope counts: {Object.entries(scope.excluded).filter(([,v])=>v).map(([k,v])=>k+': '+v).join(' · ')||'None'}. Source exclusions count sources; coding exclusions count applications.</p>
 {result?<><p>{result.method}</p><button onClick={()=>download('media-coder-comparison.csv',safeCSV(mediaComparisonExportRows(result)),'text/csv')}>Export media coder comparison</button>{result.kinds.map(k=><article key={k.kind}><h3>{k.kind==='media'?'Recording intervals':k.kind==='image'?'Image regions':'PDF regions'}</h3><p>{k.applicationCount} eligible applications · {k.units} · coverage {k.jaccard===null?'Undefined':(k.jaccard*100).toFixed(2)+'%'} · exact selection matches {k.exact.matched}/{k.exact.units} ({k.exact.percent===null?'Undefined':k.exact.percent.toFixed(2)+'%'})</p><div className="table-wrap"><table><thead><tr><th>Code</th><th>Left union</th><th>Right union</th><th>Intersection</th><th>Union</th><th>{k.kind==='media'?'Jaccard':'Region IoU'}</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{k.byCode.map(c=><tr key={c.codeId}><td>{c.code}</td><td>{display(c.left)}</td><td>{display(c.right)}</td><td>{display(c.intersection)}</td><td>{display(c.union)}</td><td>{c.jaccard===null?'Undefined':(c.jaccard*100).toFixed(2)+'%'}</td><td><button onClick={()=>setEvidence({title:k.kind+' · '+c.code,rows:c.applications})}>Inspect compared selections</button></td></tr>)}</tbody></table></div></article>)}</>:<p>Choose two distinct researchers with eligible media coding. This panel never infers audio or region coding from transcript text.</p>}
 {evidence&&<section><h3>{evidence.title}</h3><button onClick={()=>setEvidence(null)}>Close compared evidence</button><div className="table-wrap"><table><thead><tr><th>Selection</th><th>Researcher</th><th>Code</th><th>Source</th></tr></thead><tbody>{evidence.rows.slice(0,100).map(c=><tr key={c.id}><td><button onClick={()=>jump(c)}>{c.kind==='media'?`${c.timeStart}–${c.timeEnd} seconds`:c.kind==='pdf'?`Page ${c.region.page}: ${c.text||'PDF region'}`:c.text||'Image region'}</button></td><td>{c.coder}</td><td>{s.codes.find(k=>k.id===c.codeId)?.name}</td><td>{s.documents.find(d=>d.id===c.documentId)?.name}</td></tr>)}</tbody></table>{evidence.rows.length>100&&<p>First 100 compared applications shown; CSV includes all computed metric rows.</p>}</div></section>}</section>;
}
