import React,{useRef,useState} from 'react';
import {Modal,Field} from '../components/ui.jsx';
import {tokenizeMemo,resolveMemoReference,memoReferenceOptions,insertMemoReference} from '../memo-references.mjs';
export function MemoReferences({state,content,onNavigate}){return <span className="memo-text">{tokenizeMemo(content).map((p,i)=>{if(p.kind==='text')return <React.Fragment key={i}>{p.text}</React.Fragment>;const r=resolveMemoReference(state,p.referenceKind,p.id);return r.available?<button type="button" className="quote-link" key={i} aria-label={'Open '+p.referenceKind+' '+r.label} onClick={()=>onNavigate?.({kind:p.referenceKind,id:p.id})}>@{p.referenceKind}: {r.label}{r.archived?' (archived)':''}</button>:<span key={i} className="muted" title={p.text}>{r.label} ({p.id})</span>;})}</span>;}
export function MemoEditor({state,initial={},onSave,onClose}){
 const [data,setData]=useState(initial),[selected,setSelected]=useState(''),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[activeReference,setActiveReference]=useState(null);const input=useRef(null),options=memoReferenceOptions(state).filter(r=>(r.kind+' '+r.label+' '+r.id).toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 const insert=()=>{if(!selected)return;const [kind,id]=JSON.parse(selected),next=insertMemoReference(data.content,kind,id,input.current?.selectionStart);setData({...data,content:next.content});requestAnimationFrame(()=>{input.current?.focus();input.current?.setSelectionRange(next.cursor,next.cursor);});};
 return <Modal title="Research memo" onClose={onClose} wide><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await onSave(data);onClose();}catch(e){setError(e.message);}finally{setBusy(false);}}}>
 <Field label="Title"><input required value={data.title||''} onChange={e=>setData({...data,title:e.target.value})}/></Field>
 <Field label="Memo"><textarea ref={input} rows={10} value={data.content||''} onChange={e=>setData({...data,content:e.target.value})}/></Field>
 <p className="muted">Insert @code, @source, @case or @memo references by selecting a record. Links retain its ID when renamed. Missing records stay unavailable. Memo text is plain text.</p>
 <Field label="Find a record to mention"><input value={query} onChange={e=>{setQuery(e.target.value);setSelected('');}}/></Field><Field label="Record to mention"><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose an existing record</option>{options.map(r=><option key={JSON.stringify([r.kind,r.id])} value={JSON.stringify([r.kind,r.id])}>{'@'+r.kind+' · '+r.label+' · '+r.id}</option>)}</select></Field><button type="button" disabled={!selected||busy} onClick={insert}>Insert record reference</button>
 <div aria-label="Memo reference preview"><strong>Preview</strong><p><MemoReferences state={state} content={data.content||''} onNavigate={r=>setActiveReference(resolveMemoReference(state,r.kind,r.id))}/></p></div>{activeReference?.available&&<section aria-label="Referenced record preview"><h3>{activeReference.label}</h3><p>@{activeReference.kind} · {activeReference.id}</p>{activeReference.kind==='code'&&<p>{activeReference.record.description||'No definition recorded.'}</p>}{activeReference.kind==='memo'&&<p className="memo-text">{activeReference.record.content}</p>}{['case','source'].includes(activeReference.kind)&&<dl>{Object.entries(activeReference.record.attributes||{}).map(([key,value])=><React.Fragment key={key}><dt>{key}</dt><dd>{String(value)}</dd></React.Fragment>)}</dl>}</section>}
 <Field label="Linked source"><select value={data.documentId||''} onChange={e=>setData({...data,documentId:e.target.value})}><option value="">Project memo</option>{state.documents.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></Field><Field label="Linked code"><select value={data.codeId||''} onChange={e=>setData({...data,codeId:e.target.value})}><option value="">No code link</option>{state.codes.filter(c=>c.codable!==false).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>
 {error&&<p role="status">{error}</p>}<footer><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save'}</button></footer></form></Modal>;
}
