import React,{useEffect,useMemo,useState} from 'react';
import {ChevronLeft,ChevronRight,Check} from 'lucide-react';
import {browserPassage,passageDraft,passageIsCurrent,transcriptUnits} from '../passage-selection.mjs';
import './passage-navigator.css';
export function PassageNavigator({document:doc,textRef,selection,onChoose}){
 const [expanded,setExpanded]=useState(false);
 const [mode,setMode]=useState(doc.turns?.length?'turns':'lines'),[candidate,setCandidate]=useState(null),[bounds,setBounds]=useState({start:0,end:0});
 const units=useMemo(()=>transcriptUnits(doc,mode),[doc,mode]);const index=units.findIndex(u=>selection&&u.start<=selection.start&&u.end>selection.start),chosen=index>=0?index:0;
 useEffect(()=>{setMode(doc.turns?.length?'turns':'lines');setCandidate(null);setBounds({start:0,end:0});},[doc.id]);
 useEffect(()=>{if(selection)setBounds({start:selection.start,end:selection.end});},[selection?.start,selection?.end]);
 useEffect(()=>{function capture(){setCandidate(browserPassage(textRef.current,doc,window.getSelection()));}window.document.addEventListener('selectionchange',capture);return()=>window.document.removeEventListener('selectionchange',capture);},[doc,textRef]);
 const range=passageDraft(doc,Number(bounds.start),Number(bounds.end));
 function choose(unit){if(!unit)return;onChoose({...passageDraft(doc,unit.start,unit.end),unitMode:mode});}
 return <details className="passage-navigator" aria-label="Precise passage navigation" open={expanded} onToggle={e=>{if(e.target===e.currentTarget)setExpanded(e.currentTarget.open);}}><summary>Choose a sentence, segment or exact range</summary><div className="passage-unit-controls"><label>Navigate<select aria-label="Transcript unit" value={mode} onChange={e=>setMode(e.target.value)}><option value="sentences">Sentences</option><option value="turns" disabled={!doc.turns?.length}>Source segments</option><option value="lines">Source lines</option></select></label><label className="passage-unit-picker">Passage<select aria-label="Go to transcript passage" value={units[chosen]?.id||''} onChange={e=>choose(units.find(u=>u.id===e.target.value))}>{units.map(u=><option key={u.id} value={u.id}>{u.label}</option>)}</select></label><button aria-label="Previous passage" disabled={chosen===0||!units.length} onClick={()=>choose(units[chosen-1])}><ChevronLeft size={17}/></button><button aria-label="Next passage" disabled={index>=units.length-1||!units.length} onClick={()=>choose(units[index<0?0:index+1])}><ChevronRight size={17}/></button><button onClick={()=>choose(units[chosen])} disabled={!units.length}>Select {mode==='sentences'?'sentence':mode==='turns'?'segment':'line'}</button></div>{candidate&&<div className="passage-touch-confirm"><button className="primary" disabled={!passageIsCurrent(doc,candidate)} onPointerDown={e=>e.preventDefault()} onClick={()=>choose(candidate)}><Check size={16}/> Use highlighted text</button><small>Select any text, then confirm here. Source lines follow original newline breaks; screen wrapping never changes quotation anchors.</small></div>}<details className="passage-range-editor"><summary>Select exact character range</summary><div><label>Start (included)<input aria-label="Passage start character" type="number" min="0" step="1" value={bounds.start} onChange={e=>setBounds({...bounds,start:e.target.value})}/></label><label>End (excluded)<input aria-label="Passage end character" type="number" min="0" step="1" value={bounds.end} onChange={e=>setBounds({...bounds,end:e.target.value})}/></label><button disabled={!range} onClick={()=>choose(range)}>Use exact range</button></div>{range&&<p className="passage-range-preview">{range.text}</p>}<small>Offsets count Unicode characters, including spaces and newline characters. A range can span multiple turns or lines.</small></details>{mode==='turns'&&units.length<(doc.turns||[]).length&&<p role="status">Some turn anchors need review. Select an exact source range instead.</p>}</details>;
}

export function PassageStepControls({document:doc,selection,onChoose}){
 const mode=selection.unitMode||(doc.turns?.length?'turns':'lines'),units=useMemo(()=>transcriptUnits(doc,mode),[doc,mode]),index=units.findIndex(u=>u.start<=selection.start&&u.end>selection.start);
 function choose(i){const u=units[i];if(u)onChoose({...passageDraft(doc,u.start,u.end),unitMode:mode});}
 return <div className="selected-passage-steps"><button aria-label="Previous selected passage" disabled={index<=0} onClick={()=>choose(index-1)}><ChevronLeft size={16}/> Previous {mode==='sentences'?'sentence':mode==='turns'?'segment':'line'}</button><button aria-label="Next selected passage" disabled={index<0||index>=units.length-1} onClick={()=>choose(index+1)}>Next {mode==='sentences'?'sentence':mode==='turns'?'segment':'line'}<ChevronRight size={16}/></button></div>;
}
