import React,{useEffect,useMemo,useState} from 'react';
import {executeResultQuery} from '../query-intervals.mjs';
import {safeCSV} from '../report-export.mjs';
import {download} from '../exchange.js';
export function QueryLaboratory({state:s,project,jump,operate,initialScope={}}){
 const [spec,setSpec]=useState({mode:'intervals',kind:'all',operator:'and',near:200,status:'all',source:initialScope.sourceId||'',caseId:initialScope.caseId||'',coder:initialScope.coder||'',codeA:initialScope.codeId||'',text:''}),[page,setPage]=useState(0),[name,setName]=useState(''),[message,setMessage]=useState(''),[selected,setSelected]=useState([]),[busy,setBusy]=useState(false);
 const rows=useMemo(()=>executeResultQuery(s,spec),[s,spec]),change=(k,v)=>setSpec(prev=>({...prev,[k]:v}));
 useEffect(()=>{setSelected([]);setPage(0);},[s,project.revision,spec]);
 useEffect(()=>{setMessage('');},[spec]);
 async function save(type){setBusy(true);try{await operate(type,{name,spec,...(type==='query.results.materialize'?{resultIds:selected}:{})});setMessage(type==='query.results.save'?'Saved query reruns against current sources.':'Frozen fragments saved as your own coding with original provenance.');setName('');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 const exportRows=()=>download('query-fragments.csv',safeCSV([['Source ID','Source revision','Kind','Units','Start codepoint','End codepoint','Quotation','Recording key','Start seconds','End seconds','Operation','Original coding provenance JSON','Related coding provenance JSON','Supplied turn bounds JSON'],...rows.map(r=>[r.documentId,r.sourceRevision,r.kind||'text',r.units,r.start,r.end,r.text,r.recordingKey,r.kind==='media'?r.timeStart:null,r.kind==='media'?r.timeEnd:null,r.operation,JSON.stringify(r.provenance),JSON.stringify(r.relatedProvenance),JSON.stringify(r.suppliedTurnBounds||[])])]),'text/csv');
 const visible=rows.slice(page*50,page*50+50),toggle=id=>setSelected(old=>old.includes(id)?old.filter(x=>x!==id):[...old,id]);
 return <section className="query-laboratory"><h2>Fragment queries & corpus search</h2><p>Use the application query tab for whole original quotations. This panel computes precise fragments or searches eligible source text including uncoded passages.</p><div className="filterbar"><label>Result mode<select aria-label="Fragment result mode" value={spec.mode} onChange={e=>change('mode',e.target.value)}><option value="intervals">Interval results</option><option value="literal">Literal corpus search</option></select></label><label>Source<select aria-label="Fragment source" value={spec.source} onChange={e=>change('source',e.target.value)}><option value="">All eligible sources</option>{s.documents.filter(d=>d.sourceRole!=='reference').map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Case<select aria-label="Fragment case" value={spec.caseId||''} onChange={e=>change('caseId',e.target.value)}><option value="">All cases</option>{(s.cases||[]).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>{spec.mode==='literal'?'Search literal text':'Quotation contains'}<input aria-label="Corpus literal text" value={spec.text} onChange={e=>change('text',e.target.value)}/></label><label><input type="checkbox" checked={spec.caseSensitive===true} onChange={e=>change('caseSensitive',e.target.checked)}/> Case sensitive</label></div>
 {spec.mode==='intervals'&&<div className="filterbar"><label>Code A<select aria-label="Fragment code A" value={spec.codeA||''} onChange={e=>change('codeA',e.target.value)}><option value="">All codes</option>{s.codes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Operator<select aria-label="Fragment operator" value={spec.operator} onChange={e=>change('operator',e.target.value)}><option value="and">AND · intersection</option><option value="or">OR · union</option><option value="not">NOT · subtract B from A</option><option value="near">NEAR · matching original A ranges</option></select></label><label>Code B<select aria-label="Fragment code B" value={spec.codeB||''} onChange={e=>change('codeB',e.target.value)}><option value="">No second code</option>{s.codes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Selection type<select aria-label="Fragment type" value={spec.kind} onChange={e=>change('kind',e.target.value)}><option value="all">Text and recording ranges</option><option value="text">Text codepoints</option><option value="media">Recording seconds</option></select></label><label>Coder<select aria-label="Fragment coder" value={spec.coder||''} onChange={e=>change('coder',e.target.value)}><option value="">All coders</option>{[...new Set(s.codings.map(c=>c.coder))].map(c=><option key={c}>{c}</option>)}</select></label><label>Decision<select aria-label="Fragment decision" value={spec.status} onChange={e=>change('status',e.target.value)}>{['all','coded','accepted','provisional','flagged'].map(v=><option key={v}>{v}</option>)}</select></label><label><input type="checkbox" checked={spec.includeDescendants!==false} onChange={e=>change('includeDescendants',e.target.checked)}/> Include descendants</label>{spec.operator==='near'&&<label>Distance in codepoints or seconds<input aria-label="Fragment near distance" type="number" min="0" step="any" value={spec.near} onChange={e=>change('near',e.target.value)}/></label>}</div>}
 <p className="muted">AND intersects coverage, OR unions connected coverage, NOT splits A around B; NEAR preserves matching original A boundaries. Text and recordings are never mixed. Recording results require the current recording. Reference sources, stale anchors, deleted coding and consent-review passages are excluded. Passage cases clip text fragments; recording membership needs a whole-source case link. Literal search keeps original Unicode positions and does not infer audio alignment.</p>
 <div className="filterbar"><strong>{rows.length} results · {selected.length} selected</strong><button onClick={()=>setSelected(visible.map(r=>r.queryResultId))}>Select this page</button><button onClick={()=>setSelected([])}>Clear selection</button><button onClick={exportRows}>Export all fragments CSV</button><button disabled={!page} onClick={()=>setPage(page-1)}>Previous fragments</button><span>Page {page+1}</span><button disabled={(page+1)*50>=rows.length} onClick={()=>setPage(page+1)}>Next fragments</button></div>
 <div className="table-wrap"><table><thead><tr><th>Select</th><th>Exact result</th><th>Bounds</th><th>Original decisions</th></tr></thead><tbody>{visible.map(r=><tr key={r.queryResultId}><td><input aria-label={'Select fragment '+(r.kind==='media'?r.timeStart:r.start)} type="checkbox" checked={selected.includes(r.queryResultId)} onChange={()=>toggle(r.queryResultId)}/></td><td><button className="quote-link" onClick={()=>jump(r)}>{r.text}</button><small>{s.documents.find(d=>d.id===r.documentId)?.name}</small></td><td>{r.kind==='media'?`${r.timeStart}–${r.timeEnd} seconds`:`${r.start}–${r.end} codepoints`}</td><td>{r.provenance.length?'Derived from '+r.provenance.length+' code applications':'Literal source match; no original coding'}{r.relatedProvenance.length>0&&<small>{r.relatedProvenance.length} related applications retained</small>}</td></tr>)}</tbody></table>{!rows.length&&<p>No eligible matching results.</p>}</div>
 {project.role!=='viewer'&&<div className="settings-card"><label>Query / result code name<input aria-label="Fragment result name" value={name} onChange={e=>setName(e.target.value)}/></label><button disabled={busy||!name.trim()} onClick={()=>save('query.results.save')}>Save fragment query</button><button disabled={busy||!name.trim()||!selected.length} onClick={()=>save('query.results.materialize')}>Freeze selected fragments as my code</button></div>}
 {(s.savedQueries||[]).filter(q=>['intervals','literal'].includes(q.spec?.mode)).length>0&&<div className="filterbar"><label>Saved fragment queries<select aria-label="Saved fragment query" value="" onChange={e=>{const q=s.savedQueries.find(q=>q.id===e.target.value);if(q)setSpec(q.spec);}}><option value="">Run a saved query</option>{s.savedQueries.filter(q=>['intervals','literal'].includes(q.spec?.mode)).map(q=><option key={q.id} value={q.id}>{q.name}</option>)}</select></label></div>}{message&&<p role="status">{message}</p>}</section>;
}
