import React,{useMemo,useState} from 'react';
import {consentMarkers,consentAnchorCurrent} from '../source-consent.mjs';

export function SourceConsentReview({document:doc,project,operate,initialSelection}){
 const initialScope=useMemo(()=>initialSelection?.documentId===doc.id&&consentAnchorCurrent(doc,initialSelection)?initialSelection:null,[doc,initialSelection]);
 const [start,setStart]=useState(()=>initialScope?.start??0),[end,setEnd]=useState(()=>initialScope?.end??0),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const text=useMemo(()=>Array.from(doc.text||''),[doc.text]);
 const markers=useMemo(()=>consentMarkers(doc),[doc.text,doc.revision]);
 const canReview=['owner','reviewer'].includes(project.role)&&project.access?.capabilities?.sources!==false;
 const validScope=Number.isInteger(start)&&Number.isInteger(end)&&start>=0&&end>start&&end<=text.length;
 const preview=useMemo(()=>{
  if(!validScope)return null;
  const count=end-start,limit=300;
  return {count,before:text.slice(Math.max(0,start-80),start).join(''),after:text.slice(end,Math.min(text.length,end+80)).join(''),first:text.slice(start,Math.min(end,start+(count>limit*2?limit:count))).join(''),last:count>limit*2?text.slice(end-limit,end).join(''):null,omitted:Math.max(0,count-limit*2)};
 },[text,start,end,validScope]);
 const run=async(type,data)=>{setBusy(true);setError('');try{await operate(type,{id:doc.id,...data});setNote('');}catch(e){setError(e.message);}finally{setBusy(false);}};
 const passageStyle={whiteSpace:'pre-wrap',overflowWrap:'anywhere'};
 return <section className="settings-card"><h2>Consent and off-record passages</h2><p>Markers are suggestions to inspect. Pending and withheld passages are excluded from analysis and annotated reports. Native project archives retain the original source for preservation.</p><p>Including a passage records your authorization and its scope; it does not verify transcript accuracy or speaker identity.</p>{markers.map(m=><button key={m.start} disabled={!canReview||busy} onClick={()=>{setStart(m.start);setEnd(text.length);}}>{m.text} · {m.start}–{m.end}: preview suggested scope to end of source</button>)}<p>Marker suggestions only set the preview boundaries. Review and adjust the scope before flagging or re-anchoring it.</p><div className="filterbar"><label>Scope start (codepoint)<input aria-label="Consent scope start" type="number" step="1" min="0" max={text.length} value={start} onChange={e=>setStart(Number(e.target.value))}/></label><label>Scope end (codepoint)<input aria-label="Consent scope end" type="number" step="1" min="0" max={text.length} value={end} onChange={e=>setEnd(Number(e.target.value))}/></label></div>
 <section aria-label="Selected consent scope preview" className="callout" style={{display:'block',minWidth:0}}>
  <h3>Scope preview</h3>
  {preview?<><p><strong>{preview.count.toLocaleString()} characters selected</strong> · codepoints {start}–{end} of {text.length.toLocaleString()}. The start is included; the end is excluded.</p>
   <div aria-label="Context before selected scope"><small>Outside selected scope — before{start===0?' (start of source)':''}</small><p dir={doc.direction||'auto'} style={passageStyle}>{preview.before||'No preceding context.'}</p></div>
   <div aria-label="Selected scope text"><strong>Selected scope{preview.omitted?' — beginning and end':' — exact text'}</strong><blockquote dir={doc.direction||'auto'} style={passageStyle}>{preview.first}</blockquote>{preview.omitted>0&&<><p><em>{preview.omitted.toLocaleString()} selected characters in the middle are omitted from this preview. The full range will be flagged or re-anchored.</em></p><blockquote dir={doc.direction||'auto'} style={passageStyle}>{preview.last}</blockquote></>}</div>
   <div aria-label="Context after selected scope"><small>Outside selected scope — after{end===text.length?' (end of source)':''}</small><p dir={doc.direction||'auto'} style={passageStyle}>{preview.after||'No following context.'}</p></div>
  </>:<p>Choose whole-number boundaries with the end after the start to preview a passage. This source has {text.length.toLocaleString()} characters.</p>}
 </section>
 <label className="field"><span>Decision reason and authorization scope</span><textarea aria-label="Consent decision reason" value={note} onChange={e=>setNote(e.target.value)}/></label><button disabled={!canReview||busy||!note.trim()||!validScope} onClick={()=>run('source.consent.flag',{start,end,text:text.slice(start,end).join(''),sourceRevision:doc.revision||1,note})}>Flag passage for consent review</button>{error&&<p role="alert">{error}</p>}{(doc.consentDecisions||[]).map(r=><article className="memo-card" key={r.id}><strong>{r.start}–{r.end} · {r.status}</strong><p>{r.note}</p><small>{r.createdBy} · {(r.history||[]).length} prior decisions</small>{!consentAnchorCurrent(doc,r)&&<p>Source changed. Choose the current boundaries above and re-anchor before deciding.</p>}<div className="filterbar">{['pending','withheld','included'].map(status=><button key={status} disabled={!canReview||busy||!note.trim()||!consentAnchorCurrent(doc,r)} onClick={()=>run('source.consent.decide',{flagId:r.id,status,note})}>{status==='included'?'Include with authorization':status==='withheld'?'Withhold from analysis':'Keep pending'}</button>)}<button disabled={!canReview||busy||!note.trim()||!validScope} onClick={()=>run('source.consent.reanchor',{flagId:r.id,start,end,text:text.slice(start,end).join(''),sourceRevision:doc.revision||1,note})}>Re-anchor scope</button></div><details><summary>Decision history</summary>{(r.history||[]).map((h,i)=><p key={i}>{h.status} · {h.changedBy} · {h.decisionNote}</p>)}</details></article>)}</section>;
}
