import React,{useState} from 'react';
import {RESEARCH_APPROACHES,studyDesignDraft,prepareStudyDesign} from '../study-method.mjs';
import './study-interface.css';

export function StudyDesign({state,project,operate,onNavigate}){
 const [draft,setDraft]=useState(()=>studyDesignDraft(state)),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
 const canEdit=['owner','reviewer'].includes(project.role)&&project.access?.capabilities?.structure!==false,method=RESEARCH_APPROACHES.find(a=>a.id===draft.approach);
 const set=(key,value)=>{setDraft(d=>({...d,[key]:value}));setSaved(false);};
 const field=(key,label,max,help)=> <label className="field"><span>{label}</span><textarea aria-label={label} maxLength={max} rows={key==='question'?3:4} disabled={!canEdit||busy} value={draft[key]} onChange={e=>set(key,e.target.value)}/>{help&&<small>{help}</small>}</label>;
 async function save(e){e.preventDefault();setError('');setBusy(true);try{await operate('settings.save',{researchDesign:prepareStudyDesign(draft,state.settings?.researchDesign,project.access?.actor||project.role)});setSaved(true);}catch(error){setError(error.message);}finally{setBusy(false);}}
 return <div className="page study-design"><div className="page-heading"><div><span className="eyebrow">ORIENT YOUR ANALYSIS</span><h1>Research question &amp; method</h1><p>Make the purpose, approach and researcher perspective visible before interpreting the interviews.</p></div><button onClick={()=>onNavigate('overview')}>Back to study overview</button></div>
 {!canEdit&&<p className="callout">Study setup is shared project context. An owner or reviewer can edit it. Your available view depends on project permissions.</p>}
 <form onSubmit={save}><div className="study-design-grid"><section className="settings-card"><h2>What are you trying to understand?</h2>{field('question','Research question or purpose',4000,'This guides what you attend to; it can be revised as understanding develops.')}<label className="field"><span>Qualitative approach</span><select aria-label="Qualitative approach" disabled={!canEdit||busy} value={draft.approach} onChange={e=>set('approach',e.target.value)}>{RESEARCH_APPROACHES.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{draft.approach==='other'&&<label className="field"><span>Approach name</span><input aria-label="Approach name" maxLength={200} disabled={!canEdit||busy} value={draft.methodName} onChange={e=>set('methodName',e.target.value)}/></label>}{field('methodRationale','Why this approach?',8000,'Explain the fit with the question and how interpretations will be developed.')}</section>
 <aside className="settings-card"><h2>Let the method guide the tools</h2><p>{method?.guidance}</p>{method?.href&&<a href={method.href} target="_blank" rel="noreferrer">Read the method guidance</a>}<ul><li>Codes label selected passages. Themes express an interpretation developed across the material.</li><li>Memos record ideas, assumptions and changes in your reasoning.</li><li>Return to source context and look for qualifications and contrasting accounts.</li><li>Saved activity and quotation counts describe work performed; they do not establish accuracy, saturation or quality.</li></ul><p>You can revisit any step. Comparison metrics and charting are optional tools whose use should fit your approach.</p></aside></div>
 <section className="settings-card"><h2>Context and reflexivity</h2><p>These notes are shared with your project team. Use private notes for personal material you do not want to share.</p><div className="study-design-grid">{field('samplingNotes','Who or what is represented?',8000,'Describe source selection, setting and limitations. File labels do not verify speaker identity.')}{field('researcherPosition','Researcher perspective and assumptions',8000,'Record relevant experience, relationships and assumptions that may shape interpretation.')}</div>{field('sourceScope','Source scope and reporting boundaries',8000,'Describe what is being analyzed and how it may be reported. Passage-level consent decisions remain in Source review.')}</section>
 {error&&<p role="alert" className="error-banner">{error}</p>}{saved&&<p role="status">Study setup saved. Earlier setup decisions remain in its history and project audit trail.</p>}<div className="actions"><button className="primary" disabled={!canEdit||busy} type="submit">{busy?'Saving study setup…':'Save study setup'}</button><button type="button" onClick={()=>onNavigate('sources')}>Continue to sources</button></div></form>
 {state.settings?.researchDesign?.history?.length>0&&<details className="settings-card"><summary>Earlier study setup decisions ({state.settings.researchDesign.history.length})</summary>{[...state.settings.researchDesign.history].reverse().map((d,i)=><article key={i}><strong>{d.question}</strong><p>{RESEARCH_APPROACHES.find(a=>a.id===d.approach)?.name||d.methodName}</p><small>{d.modifiedBy} · {d.modifiedAt}</small></article>)}</details>}
 </div>;
}
