import React,{useEffect,useState} from 'react';
import {normalizeTeamPolicy,TEAM_CAPABILITIES,TEAM_ROLES,DEFAULT_ROLE_CAPABILITIES} from '../team-policy.mjs';
const descriptions={coding:'Apply or review coding',codebook:'Edit code definitions and hierarchy',sources:'Import or change shared sources',structure:'Cases, attributes and study settings',memos:'Own notes, journals and reading tools',ai:'Search and AI review services',audio:'Recording uploads and transcription jobs',history:'Decision history',recovery:'Recovery points and verified downloads'};
export function TeamPolicyEditor({project,operate,busy}){
 const [draft,setDraft]=useState(()=>normalizeTeamPolicy(project.state.settings?.teamAccess)),[error,setError]=useState('');
 useEffect(()=>{setDraft(normalizeTeamPolicy(project.state.settings?.teamAccess));setError('');},[project.id,project.revision]);
 if(project.role!=='owner')return <section><h2>Project permissions</h2><p>{draft.blindCoding?'Blind coding is active: coders receive only their own decisions, notes and history. Reviewers and the owner can compare the complete project.':'Coding decisions are shared with project members.'}</p></section>;
 function preset(role,name){const caps=structuredClone(DEFAULT_ROLE_CAPABILITIES[role]);if(name==='manual'){caps.ai=false;caps.audio=false;}if(name==='focused'){for(const key of ['codebook','sources','structure','ai','audio','recovery'])caps[key]=false;}setDraft({...draft,roles:{...draft.roles,[role]:caps}});}
 return <section><h2>Project permissions</h2><p>Permissions limit each role’s existing authority. Reviewers can review other decisions; coders edit their own work; viewers remain read-only.</p><label className="check"><input type="checkbox" checked={draft.blindCoding} onChange={e=>setDraft({...draft,blindCoding:e.target.checked})}/> Blind independent coding</label><p>While active, coders see their own decisions, notes and history. Shared sources and code definitions remain visible. Reviewers and the owner retain complete comparison access. Coders cannot download historical backups or change shared study structure. Previously downloaded data cannot be recalled.</p><div className="table-wrap"><table><thead><tr><th>Permission</th>{TEAM_ROLES.map(role=><th key={role}>{role}<select aria-label={role+' permission preset'} defaultValue="" onChange={e=>preset(role,e.target.value)}><option value="" disabled>Choose preset</option><option value="standard">Standard</option><option value="manual">Manual research</option><option value="focused">Focused coding</option></select></th>)}</tr></thead><tbody>{TEAM_CAPABILITIES.map(key=><tr key={key}><td>{descriptions[key]}</td>{TEAM_ROLES.map(role=><td key={role}><input aria-label={role+' '+key+' permission'} type="checkbox" disabled={role==='viewer'&&!['history','recovery'].includes(key)} checked={draft.roles[role][key]} onChange={e=>setDraft({...draft,roles:{...draft.roles,[role]:{...draft.roles[role],[key]:e.target.checked}}})}/></td>)}</tr>)}</tbody></table></div>{error&&<p role="alert">{error}</p>}<button disabled={busy} onClick={async()=>{try{await operate('permissions.update',draft);}catch(e){setError(e.message);}}}>Save project permissions</button></section>;
}
