import React,{useMemo,useState} from 'react';
import {transcriptionQuality} from '../transcript-quality.mjs';
import {canSeekTurn} from '../transcript-alignment.mjs';
export function TranscriptQuality({document:doc,mediaRef,onSelect}) {
 const [threshold,setThreshold]=useState(.5);
 const report=useMemo(()=>transcriptionQuality(doc,threshold),[doc,threshold]);
 const max=Math.max(1,...report.bins.map(b=>b.count));
 return <details className="settings-card"><summary>Machine transcript listening priorities</summary><p>Native ASR word probabilities help choose passages to listen to. They do not measure transcript accuracy. Alignment scores are excluded; transcript corrections still require a reviewer.</p><label>Flag probabilities below <input aria-label="Transcript probability review threshold" type="number" min="0" max="1" step=".05" value={threshold} onChange={e=>{const value=Number(e.target.value);if(Number.isFinite(value)&&value>=0&&value<=1)setThreshold(value);}}/></label><p>{report.flaggedWords.toLocaleString()} flagged words in {report.rows.length.toLocaleString()} turns · {report.scoredWords.toLocaleString()} supplied ASR probabilities · {report.unscoredWords.toLocaleString()} words without a valid ASR probability</p>{report.scoredWords>0&&<svg role="img" aria-label="ASR probability distribution, not measured accuracy" viewBox="0 0 600 140" style={{width:'100%',maxWidth:600}}>{report.bins.map((b,i)=><g key={i}><rect x={i*60+2} y={105-b.count/max*95} width="54" height={b.count/max*95} fill={b.start<threshold?'#b45964':'#447e96'}><title>{b.start.toFixed(1)}–{b.end.toFixed(1)}: {b.count} words</title></rect><text x={i*60+4} y="125" fontSize="11">{b.start.toFixed(1)}–{b.end.toFixed(1)}</text></g>)}</svg>}<div style={{maxHeight:300,overflow:'auto'}}>{report.rows.slice(0,100).map(row=><div key={row.turnId} style={{padding:'8px 0',borderBottom:'1px solid #ddd'}}><button onClick={()=>onSelect?.({documentId:doc.id,start:row.start,end:row.end})}>View source passage</button><button disabled={!canSeekTurn(doc,row)||!doc.mediaKey} onClick={()=>{if(mediaRef?.current)mediaRef.current.currentTime=row.timeStart;}}>Listen at {Number.isFinite(row.timeStart)?row.timeStart.toFixed(1):'missing'} seconds</button><p>{row.text.slice(0,300)}</p><small>{row.flagged.slice(0,12).map(w=>`${w.text.trim()} (${w.probability.toFixed(2)})`).join(' · ')}</small></div>)}</div>{report.rows.length>100&&<p>Showing the first 100 flagged turns. Adjust the review threshold to focus the list.</p>}{!report.scoredWords&&<p>This source has no native ASR word probabilities available.</p>}</details>;
}
