import React,{useMemo,useState} from 'react';
import {transcriptionQuality} from '../transcript-quality.mjs';
import {canSeekTurn} from '../transcript-alignment.mjs';
export function TranscriptQuality({document:doc,mediaRef,onSelect}) {
 const [threshold,setThreshold]=useState(.5),[order,setOrder]=useState('lowest');
 const report=useMemo(()=>transcriptionQuality(doc,threshold),[doc,threshold]);
 const max=Math.max(1,...report.bins.map(b=>b.count)),barHeight=n=>n?Math.max(3,Math.sqrt(n/max)*90):0,lowest=r=>Math.min(1,...r.flagged.map(w=>w.probability)),rows=order==='lowest'?[...report.rows].sort((a,b)=>lowest(a)-lowest(b)||a.start-b.start):report.rows;
 return <details className="settings-card"><summary>Machine transcript listening priorities</summary><p>Native ASR word probabilities help choose passages to listen to. They do not measure transcript accuracy. Alignment scores are excluded; transcript corrections still require a reviewer.</p><label>Flag probabilities below <input aria-label="Transcript probability review threshold" type="number" min="0" max="1" step=".05" value={threshold} onChange={e=>{const value=Number(e.target.value);if(Number.isFinite(value)&&value>=0&&value<=1)setThreshold(value);}}/></label><p>{report.flaggedWords.toLocaleString()} flagged words in {report.rows.length.toLocaleString()} turns · {report.scoredWords.toLocaleString()} supplied ASR probabilities · {report.unscoredWords.toLocaleString()} words without a valid ASR probability</p>{report.scoredWords>0&&<svg role="img" aria-label="ASR probability distribution, not measured accuracy" viewBox="0 0 600 140" style={{width:'100%',maxWidth:600}}><desc>Bar height uses a square-root scale so small bins stay visible; the number above each bar is the exact word count.</desc>{report.bins.map((b,i)=><g key={i}><text x={i*60+29} y={101-barHeight(b.count)} fontSize="11" textAnchor="middle" fill="#40545f">{b.count.toLocaleString()}</text><rect x={i*60+2} y={105-barHeight(b.count)} width="54" height={barHeight(b.count)} fill={b.start<threshold?'#b45964':'#447e96'}><title>{b.start.toFixed(1)}–{b.end.toFixed(1)}: {b.count} words</title></rect><text x={i*60+4} y="125" fontSize="11">{b.start.toFixed(1)}–{b.end.toFixed(1)}</text></g>)}</svg>}{report.rows.length>0&&<label>Order turns<select aria-label="Listening priority order" value={order} onChange={e=>setOrder(e.target.value)}><option value="lowest">Lowest word probability first</option><option value="transcript">Transcript order</option></select></label>}<p className="muted">Bar height uses a square-root scale so small bins stay visible; numbers are exact word counts.</p><div style={{maxHeight:300,overflow:'auto'}}>{rows.slice(0,100).map(row=><div key={row.turnId} style={{padding:'8px 0',borderBottom:'1px solid #ddd'}}><button onClick={()=>onSelect?.({documentId:doc.id,start:row.start,end:row.end})}>View source passage</button><button disabled={!canSeekTurn(doc,row)||!doc.mediaKey} onClick={()=>{if(mediaRef?.current)mediaRef.current.currentTime=row.timeStart;}}>Listen at {Number.isFinite(row.timeStart)?row.timeStart.toFixed(1):'missing'} seconds</button><p>{row.text.slice(0,300)}</p><small>{row.flagged.slice(0,12).map(w=>`${w.text.trim()} (${w.probability.toFixed(2)})`).join(' · ')}</small></div>)}</div>{report.rows.length>100&&<p>Showing the first 100 flagged turns. Adjust the review threshold to focus the list.</p>}{!report.scoredWords&&<p>This source has no native ASR word probabilities available.</p>}</details>;
}
