import React,{useEffect,useMemo,useRef,useState} from 'react';
import {codeTrackLayout,secondsAt,retimeEdge,nudgeEdge,clampRange,NUDGE} from '../waveform-tracks.mjs';
import {peakColumns} from '../media-peaks.mjs';
import './waveform-code-tracks.css';
const clock=n=>{const m=Math.floor(n/60);return String(m).padStart(2,'0')+':'+(n-m*60).toFixed(1).padStart(4,'0');};
const STEPS=[.5,1,2,5,10,15,30,60,120,300,600,900,1800,3600,7200];
// One lane per code on the current recording (QualCoder SegmentTracksView). Timing changes go through coding.media.retime.
export function WaveformCodeTracks({document:doc,state,mediaRef,duration,peaks,position=0,canWrite,canReview,actor,operate,onRange,onSelect}){
 const [zoom,setZoom]=useState(1),[selectedId,setSelectedId]=useState(''),[draft,setDraft]=useState(null),[creating,setCreating]=useState(null),[extra,setExtra]=useState([]),[status,setStatus]=useState(''),[saving,setSaving]=useState(false),[mediaDuration,setMediaDuration]=useState(NaN);
 const inner=useRef(null),scroller=useRef(null),drag=useRef(null),keyDraft=useRef(null),timer=useRef(null);
 useEffect(()=>{const media=mediaRef?.current;if(!media)return;const read=()=>setMediaDuration(media.duration);read();media.addEventListener('loadedmetadata',read);media.addEventListener('durationchange',read);return()=>{media.removeEventListener('loadedmetadata',read);media.removeEventListener('durationchange',read);};},[mediaRef,doc.mediaKey]);
 useEffect(()=>()=>clearTimeout(timer.current),[]);
 const layout=useMemo(()=>codeTrackLayout(state,doc,{actor,canEdit:!!canWrite&&!!operate,canReview,extraCodeIds:extra}),[state,doc,actor,canWrite,canReview,extra,operate]);
 const known=[duration,mediaDuration].find(n=>Number.isFinite(n)&&n>0),ends=[...layout.lanes.flatMap(l=>l.segments),...(layout.approximate?.segments||[])].map(s=>s.end),total=known||Math.max(10,...ends)*1.05;
 const step=STEPS.find(s=>total/zoom/s<=8)||STEPS.at(-1),ticks=Array.from({length:Math.floor(total/step)+1},(_,i)=>i*step);
 const strip=useMemo(()=>{if(!peaks)return '';const c=peakColumns(peaks,Math.min(6000,1600*zoom));return c.min.map((lo,i)=>`M${i+.5} ${50-c.max[i]*48}V${50-lo*48+.5}`).join('');},[peaks,zoom]);
 useEffect(()=>{const el=scroller.current;if(el)el.scrollLeft=Math.max(0,(mediaRef?.current?.currentTime||0)/total*el.scrollWidth-el.clientWidth/2);},[zoom]);
 const pct=t=>Math.max(0,Math.min(100,t/total*100))+'%',at=e=>{const r=inner.current.getBoundingClientRect();return secondsAt(e.clientX-r.left,r.width,total);};
 function seek(t){if(mediaRef?.current)mediaRef.current.currentTime=Math.max(0,Math.min(known||t,t));}
 function select(seg){setSelectedId(seg.id);seek(seg.start);onSelect?.({timeStart:seg.start,timeEnd:seg.end});}
 async function save(seg,next){clearTimeout(timer.current);keyDraft.current=null;if(next.start===seg.start&&next.end===seg.end){setDraft(null);return;}setDraft({id:seg.id,...next});setSaving(true);try{await operate('coding.media.retime',{id:seg.id,timeStart:next.start,timeEnd:next.end,recordingKey:doc.mediaKey,previousTimeStart:seg.start,previousTimeEnd:seg.end});setStatus('Saved '+clock(next.start)+'–'+clock(next.end)+'.');onSelect?.({timeStart:next.start,timeEnd:next.end});}catch(e){setStatus('Range not saved: '+e.message);}finally{setSaving(false);setDraft(null);}}
 function startEdge(e,seg,edge){if(!seg.editable||saving||e.button>0)return;e.stopPropagation();e.preventDefault();e.currentTarget.setPointerCapture?.(e.pointerId);drag.current={type:'edge',seg,edge,x:e.clientX};setSelectedId(seg.id);setDraft({id:seg.id,start:seg.start,end:seg.end});}
 function startLane(e,lane){if(e.target!==e.currentTarget||e.button>0)return;e.currentTarget.setPointerCapture?.(e.pointerId);drag.current={type:'create',codeId:lane.codeId,t0:at(e),x:e.clientX,allowed:!!canWrite&&!!onRange&&lane.codable};}
 function move(e){const d=drag.current;if(!d)return;if(d.type==='edge')setDraft({id:d.seg.id,...retimeEdge(d.seg,d.edge,at(e),known)});else if(d.allowed&&Math.abs(e.clientX-d.x)>4){const r=clampRange(d.t0,at(e),known);setCreating({codeId:d.codeId,...r});}}
 function end(e){const d=drag.current;drag.current=null;if(!d)return;const moved=Math.abs(e.clientX-d.x)>4;if(d.type==='edge'){if(!moved){setDraft(null);select(d.seg);return;}save(d.seg,retimeEdge(d.seg,d.edge,at(e),known));return;}setCreating(null);if(!d.allowed||!moved){seek(d.t0);return;}const r=clampRange(d.t0,at(e),known);onRange({timeStart:r.start,timeEnd:r.end,codeId:d.codeId});}
 function cancel(){drag.current=null;setDraft(null);setCreating(null);}
 function key(e,seg){if(e.key==='Enter'||e.key===' '){e.preventDefault();select(seg);return;}if(e.key==='Escape'&&keyDraft.current){clearTimeout(timer.current);keyDraft.current=null;setDraft(null);return;}if(!['ArrowLeft','ArrowRight'].includes(e.key)||!seg.editable||saving)return;e.preventDefault();const base=keyDraft.current?.id===seg.id?keyDraft.current:seg,next={id:seg.id,...nudgeEdge(base,e.shiftKey?'end':'start',e.key==='ArrowRight'?NUDGE:-NUDGE,known)};keyDraft.current=next;setDraft(next);setSelectedId(seg.id);clearTimeout(timer.current);timer.current=setTimeout(()=>save(seg,next),800);}
 function blur(seg){if(keyDraft.current?.id===seg.id)save(seg,keyDraft.current);}
 if(layout.withheld)return <section className="wave-tracks" aria-label="Code tracks"><p className="wave-tracks-note" role="status">Recording code tracks are withheld while this source has a pending or withheld consent restriction.</p></section>;
 const addable=(state.codes||[]).filter(c=>c.codable!==false&&!layout.lanes.some(l=>l.codeId===c.id));
 const segment=(lane,s)=>{const shown=draft?.id===s.id?{...s,...draft}:s,label=lane.name+': '+clock(shown.start)+' to '+clock(shown.end)+(s.coder?', coded by '+s.coder:'')+(s.editable?'. Arrow keys move the start by 0.5 seconds; Shift with arrow keys moves the end.':', read only.');return <div key={s.id} role="button" tabIndex="0" aria-label={label} aria-pressed={selectedId===s.id} title={label} className={'wave-seg'+(s.editable?' editable':'')+(selectedId===s.id?' selected':'')+(draft?.id===s.id?' dragging':'')+(s.status==='needs_review'?' review':'')} style={{left:pct(shown.start),width:`calc(${pct(shown.end-shown.start)} + 1px)`,'--row':s.row,'--seg':lane.color}} onClick={()=>{if(!drag.current)select(shown);}} onKeyDown={e=>key(e,s)} onBlur={()=>blur(s)}>{s.editable&&['start','end'].map(edge=><span key={edge} aria-hidden="true" className={'wave-handle '+edge} onPointerDown={e=>startEdge(e,s,edge)} onPointerMove={move} onPointerUp={end} onPointerCancel={cancel} onClick={e=>e.stopPropagation()}/>)}</div>;};
 return <section className="wave-tracks" aria-label="Code tracks">
  <div className="wave-tracks-bar"><strong>Code tracks</strong><div className="wave-tracks-zoom" role="group" aria-label="Track zoom"><button type="button" aria-label="Zoom out" disabled={zoom<=1} onClick={()=>setZoom(Math.max(1,zoom/2))}>−</button><input type="range" aria-label="Zoom level" min="0" max="4" step="1" value={Math.log2(zoom)} onChange={e=>setZoom(2**Number(e.target.value))}/><button type="button" aria-label="Zoom in" disabled={zoom>=16} onClick={()=>setZoom(Math.min(16,zoom*2))}>+</button><span aria-live="polite">{zoom}×</span></div>{canWrite&&onRange&&addable.length>0&&<select aria-label="Add a code track" value="" onChange={e=>e.target.value&&setExtra([...extra,e.target.value])}><option value="">Add code track…</option>{addable.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}</div>
  <div className="wave-tracks-frame">
   <div className="wave-tracks-labels" aria-hidden="true"><div className="wave-row-ruler">Time</div>{strip&&<div className="wave-row-strip">Waveform</div>}{layout.lanes.map(l=><div key={l.codeId} className="wave-row-lane" style={{'--rows':l.rows}}><i style={{background:l.color}}/><span>{l.name}</span><small>{l.segments.length}</small></div>)}{layout.approximate&&<div className="wave-row-lane approx" style={{'--rows':layout.approximate.rows}}><span>≈ Transcript timing</span></div>}</div>
   <div className="wave-tracks-scroll" ref={scroller}><div className="wave-tracks-inner" ref={inner} style={{width:zoom*100+'%'}}>
    <div className="wave-row-ruler" onClick={e=>seek(at(e))}>{ticks.map(t=><span key={t} style={{left:pct(t)}}>{clock(t).replace(/\.0$/,'')}</span>)}</div>
    {strip&&<svg className="wave-row-strip" viewBox={`0 0 ${Math.min(6000,1600*zoom,peaks.min.length)} 100`} preserveAspectRatio="none" aria-hidden="true" onClick={e=>seek(at(e))}><path d={strip}/></svg>}
    {layout.lanes.map(lane=><div key={lane.codeId} role="group" aria-label={lane.name+' track, '+lane.segments.length+' segments'+(canWrite&&lane.codable?'; drag on empty space to propose a new range':'')} className="wave-row-lane" style={{'--rows':lane.rows}} onPointerDown={e=>startLane(e,lane)} onPointerMove={move} onPointerUp={end} onPointerCancel={cancel}>{lane.segments.map(s=>segment(lane,s))}{creating?.codeId===lane.codeId&&<div className="wave-seg proposed" aria-hidden="true" style={{left:pct(creating.start),width:pct(creating.end-creating.start),'--row':0,'--seg':lane.color}}/>}</div>)}
    {layout.approximate&&<div role="group" aria-label="Transcript codings, approximate from transcript timing, read only" className="wave-row-lane approx" style={{'--rows':layout.approximate.rows}}>{layout.approximate.segments.map(s=>{const label='Approximate from transcript timing: '+s.name+', '+clock(s.start)+' to '+clock(s.end)+', read only.';return <div key={s.id} role="button" tabIndex="0" aria-label={label} title={label} aria-pressed={selectedId===s.id} className={'wave-seg approx'+(selectedId===s.id?' selected':'')} style={{left:pct(s.start),width:`calc(${pct(s.end-s.start)} + 1px)`,'--row':s.row,'--seg':s.color}} onClick={()=>select(s)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(s);}}}/>;})}</div>}
    <div className="wave-playhead" aria-hidden="true" style={{left:pct(position)}}/>
   </div></div>
  </div>
  {!layout.lanes.length&&<p className="wave-tracks-note">No recording codings on this recording yet.{canWrite&&onRange?' Add a code track, then drag across it to propose a range.':''}</p>}
  <p className="wave-tracks-note">{canWrite?'Click a segment to play from its start. Drag its edges, or focus it and use arrow keys (Shift for the end), to retime. Drag empty track space to propose a new range for that code.':'Read only: your project role cannot change recording codings. Click a segment to play from its start.'}{layout.approximate?' Transcript lane positions are approximate from transcript turn timing and cannot be edited here.':''}{layout.otherRecording?' '+layout.otherRecording+' recording coding(s) belong to an earlier recording and are not shown.':''}</p>
  {status&&<p className="wave-tracks-note" role="status">{status}</p>}
 </section>;
}
