import React,{useEffect,useMemo,useRef,useState} from 'react';
import {layoutCloud,cloudSVG,cloudCaption,clampWords,sourceLegend,dominantSource,backgroundColor,SCALES,ROTATIONS,SCHEMES,MIN_WORDS,MAX_WORDS} from '../word-cloud.mjs';
import {download} from '../exchange.js';
import './word-cloud.css';
const DEFAULTS={view:'cloud',maxWords:100,scale:'sqrt',minSize:14,maxSize:64,rotation:'none',scheme:'top',background:'light',reverse:false,topN:10,accent:''},FONT='system-ui, -apple-system, "Segoe UI", sans-serif',SCHEME_NAMES={accent:'Single accent',top:'Top words accent',categorical:'Categorical by rank',sequential:'Ramp by count',source:'By main source'},ROTATION_NAMES={none:'Horizontal',mixed:'Mixed 0° / 90°',vertical:'Vertical'},SCALE_NAMES={linear:'Linear',sqrt:'Square root',log:'Logarithmic'};
const pick=(v,list,d)=>list.includes(v)?v:d,num=(v,a,b,d)=>Number.isFinite(Number(v))?Math.max(a,Math.min(b,Number(v))):d;
function clean(x={}){return {view:pick(x.view,['cloud','bars','table'],'cloud'),maxWords:clampWords(x.maxWords??100),scale:pick(x.scale,SCALES,'sqrt'),minSize:num(x.minSize,8,40,14),maxSize:num(x.maxSize,16,120,64),rotation:pick(x.rotation,ROTATIONS,'none'),scheme:pick(x.scheme,SCHEMES,'top'),background:pick(x.background,['light','dark'],'light'),reverse:!!x.reverse,topN:num(x.topN,1,50,10),accent:/^#[0-9a-f]{6}$/i.test(x.accent||'')?x.accent:''};}
function load(key){try{return clean({...DEFAULTS,...JSON.parse(localStorage.getItem(key)||'{}')});}catch{return clean(DEFAULTS);}}
let ruler;function measure(text,size,weight){try{ruler??=document.createElement('canvas').getContext('2d');ruler.font=weight+' '+size+'px '+FONT;return ruler.measureText(text).width;}catch{return Array.from(text).length*size*.6;}}
// Small inline SVG→PNG conversion. A shared src/image-export.mjs is being written separately; unify with it later.
async function svgToPng(svg,scale=2){const [,w,h]=svg.match(/<svg[^>]*?width="(\d+)" height="(\d+)"/)||[0,800,480],url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml;charset=utf-8'}));try{const img=new Image();await new Promise((ok,no)=>{img.onload=ok;img.onerror=()=>no(new Error('The cloud image could not be drawn.'));img.src=url;});const c=document.createElement('canvas');c.width=w*scale;c.height=h*scale;const x=c.getContext('2d');x.scale(scale,scale);x.drawImage(img,0,0,w,h);return await new Promise((ok,no)=>c.toBlob(b=>b?ok(b):no(new Error('PNG export failed.')),'image/png'));}finally{URL.revokeObjectURL(url);}}
/** Reusable word cloud with Cloud / Bars / Table views. rows: [{term,count,hits:[{documentId}]}] sorted or not; onWord(term,row) opens concordance. */
export function WordCloud({rows=[],sources=[],onWord,scope='',stopList='',ngram,onNgram,storageKey='research-weave.word-cloud',filename='word-cloud',title='Word cloud'}){const [o,setO]=useState(()=>load(storageKey)),[hidden,setHidden]=useState([]),[include,setInclude]=useState(''),[tip,setTip]=useState(null),[width,setWidth]=useState(0),[note,setNote]=useState(''),box=useRef(null);const set=(k,v)=>setO(x=>clean({...x,[k]:v}));
 useEffect(()=>{try{localStorage.setItem(storageKey,JSON.stringify(o));}catch{}},[o,storageKey]);
 useEffect(()=>{const el=box.current;if(!el)return;const update=()=>setWidth(Math.max(280,Math.round(el.clientWidth/20)*20));update();if(typeof ResizeObserver==='undefined')return;const ob=new ResizeObserver(update);ob.observe(el);return ()=>ob.disconnect();},[]);
 const includeList=useMemo(()=>[...new Set(include.toLocaleLowerCase().split(/[\s,;]+/).filter(Boolean))],[include]),names=useMemo(()=>new Map(sources.map(d=>[d.id,d.name])),[sources]);
 const visible=useMemo(()=>{const hide=new Set(hidden),inc=new Set(includeList);return rows.filter(r=>!hide.has(r.term)&&(!inc.size||inc.has(r.term)||String(r.term).split(' ').some(w=>inc.has(w))));},[rows,hidden,includeList]);
 const W=width||800,H=Math.round(W<560?W*1.1:W*(o.maxWords>150?.7:.58)),k=Math.max(.5,Math.min(1,W/800)),layout=useMemo(()=>width?layoutCloud(visible,{width:W,height:H,maxWords:o.maxWords,scale:o.scale,minSize:Math.min(o.minSize,o.maxSize*k),maxSize:o.maxSize*k,rotation:o.rotation,scheme:o.scheme,background:o.background,reverse:o.reverse,topN:o.topN,accent:o.accent||undefined,sources,measure,seed:7}):null,[visible,o,width,sources]);
 const ranked=useMemo(()=>[...visible].sort((a,b)=>b.count-a.count||String(a.term).localeCompare(String(b.term))).slice(0,o.maxWords),[visible,o.maxWords]),top=ranked[0]?.count||1;
 const caption=cloudCaption({scope,stopList,hidden,include:includeList,layout,total:visible.length}),srcCount=r=>new Set((r.hits||[]).map(h=>h.documentId)).size;
 const open=r=>onWord?.(r.term,r),hide=t=>{setHidden(h=>h.includes(t)?h:[...h,t]);setTip(null);},legend=o.scheme==='source'&&layout?sourceLegend(layout.sourceOrder.map(id=>({id,name:names.get(id)||id})),o.background).filter(l=>layout.words.some(w=>dominantSource(w.hits,layout.sourceOrder)===l.id)):[];
 const exportSVG=()=>layout&&download(filename+'.svg',cloudSVG(layout,{title,caption,fontFamily:FONT}),'image/svg+xml'),exportPNG=async()=>{if(!layout)return;try{download(filename+'.png',await svgToPng(cloudSVG(layout,{title,caption,fontFamily:FONT})),'image/png');setNote('');}catch(e){setNote(e.message);}};
 const key=(e,r)=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(r);}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();hide(r.term);}else if(e.key==='Escape')setTip(null);};
 return <section className={'wc wc-'+o.background} aria-label={title}>
  <div className="wc-controls">
   <div className="wc-views" role="group" aria-label="Word view">{[['cloud','Cloud'],['bars','Bars'],['table','Table']].map(([v,n])=><button key={v} type="button" aria-pressed={o.view===v} className={o.view===v?'selected':''} onClick={()=>set('view',v)}>{n}</button>)}</div>
   <label>Max words<input type="number" aria-label="Maximum words" min={MIN_WORDS} max={MAX_WORDS} step="25" value={o.maxWords} onChange={e=>set('maxWords',e.target.value)}/></label>
   {onNgram&&<label>Phrase size<select aria-label="Cloud phrase size" value={ngram} onChange={e=>onNgram(Number(e.target.value))}>{[1,2,3,4].map(v=><option value={v} key={v}>{v} word{v>1?'s':''}</option>)}</select></label>}
   <label>Colour<select aria-label="Colour scheme" value={o.scheme} onChange={e=>set('scheme',e.target.value)}>{SCHEMES.map(v=><option key={v} value={v}>{SCHEME_NAMES[v]}</option>)}</select></label>
   <label>Background<select aria-label="Cloud background" value={o.background} onChange={e=>set('background',e.target.value)}><option value="light">Light</option><option value="dark">Dark</option></select></label>
   <label className="wc-include">Include only<input aria-label="Include only these words" placeholder="Comma or space separated" value={include} onChange={e=>setInclude(e.target.value)}/></label>
  </div>
  <details className="wc-more"><summary>Size, rotation and colour options</summary><div className="wc-controls">
   <label>Size scale<select aria-label="Size scale" value={o.scale} onChange={e=>set('scale',e.target.value)}>{SCALES.map(v=><option key={v} value={v}>{SCALE_NAMES[v]}</option>)}</select></label>
   <label>Smallest size (px)<input type="number" aria-label="Smallest size" min="8" max="40" value={o.minSize} onChange={e=>set('minSize',e.target.value)}/></label>
   <label>Largest size (px)<input type="number" aria-label="Largest size" min="16" max="120" value={o.maxSize} onChange={e=>set('maxSize',e.target.value)}/></label>
   <label>Rotation<select aria-label="Rotation" value={o.rotation} onChange={e=>set('rotation',e.target.value)}>{ROTATIONS.map(v=><option key={v} value={v}>{ROTATION_NAMES[v]}</option>)}</select></label>
   {o.scheme==='top'&&<label>Accent top<input type="number" aria-label="Accent top words" min="1" max="50" value={o.topN} onChange={e=>set('topN',e.target.value)}/></label>}
   {(o.scheme==='top'||o.scheme==='accent')&&<label>Accent colour<input type="color" aria-label="Accent colour" value={o.accent||(o.background==='dark'?'#7cb7ff':'#0b5cad')} onChange={e=>set('accent',e.target.value)}/></label>}
   {o.scheme==='sequential'&&<label className="checkbox"><input type="checkbox" checked={o.reverse} onChange={e=>set('reverse',e.target.checked)}/> Reverse ramp</label>}
   <p className="muted">Colours are adjusted to keep at least 4.5:1 contrast with the background. Sizes shrink on narrow screens.</p>
  </div></details>
  {hidden.length>0&&<div className="wc-chips" aria-label="Hidden words"><span>Hidden:</span>{hidden.map(t=><button type="button" key={t} onClick={()=>setHidden(h=>h.filter(x=>x!==t))} aria-label={'Restore '+t}>{t} <b aria-hidden="true">×</b></button>)}<button type="button" className="subtle" onClick={()=>setHidden([])}>Restore all</button></div>}
  <div ref={box} className="wc-stage">
   {o.view==='cloud'&&layout&&<div className="wc-canvas" style={{background:backgroundColor(o.background)}} onMouseLeave={()=>setTip(null)}>
    <svg viewBox={'0 0 '+layout.width+' '+layout.height} role="group" aria-label={title+'. Larger words appear more often. Press Enter to read the concordance, Delete to hide a word. The Table view lists exact counts.'} style={{fontFamily:FONT}}>
     {layout.words.map(w=><text key={w.term} x={w.x} y={w.y} fontSize={w.size} fontWeight={w.weight} fill={w.color} textAnchor="middle" dominantBaseline="central" transform={w.rotate?'rotate('+w.rotate+' '+w.x+' '+w.y+')':undefined} tabIndex={0} role="button" aria-label={w.term+', '+w.count+' occurrences in '+w.sources+' source'+(w.sources===1?'':'s')} onClick={e=>e.shiftKey||e.altKey||e.metaKey||e.ctrlKey?hide(w.term):open(w)} onKeyDown={e=>key(e,w)} onMouseEnter={()=>setTip(w)} onFocus={()=>setTip(w)} onBlur={()=>setTip(null)}>{w.term}</text>)}
    </svg>
    {tip&&<div className="wc-tip" aria-hidden="true" style={{left:(tip.x/layout.width*100)+'%',top:(Math.max(0,tip.y-tip.height/2)/layout.height*100)+'%'}}><strong>{tip.term}</strong><span>{tip.count} occurrence{tip.count===1?'':'s'} · {tip.sources} source{tip.sources===1?'':'s'}</span><small>Enter opens concordance · Shift-click or Delete hides</small></div>}
    {!layout.words.length&&<p className="wc-empty">No words to show in this scope.</p>}
   </div>}
   {o.view==='bars'&&<ol className="wc-bars">{ranked.map(r=><li key={r.term}><button type="button" className="wc-bar" onClick={()=>open(r)} title={r.count+' occurrences · '+srcCount(r)+' sources'}><span>{r.term}</span><i><b style={{width:(r.count/top*100)+'%'}}/></i><strong>{r.count}</strong></button><button type="button" className="subtle" aria-label={'Hide '+r.term} onClick={()=>hide(r.term)}>Hide</button></li>)}</ol>}
   {o.view==='table'&&<div className="table-wrap"><table className="wc-table"><caption className="muted">Top {ranked.length} terms by occurrences</caption><thead><tr><th>Rank</th><th>Term</th><th>Occurrences</th><th>Sources</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{ranked.map((r,i)=><tr key={r.term}><td>{i+1}</td><td><button type="button" className="quote-link" onClick={()=>open(r)}>{r.term}</button></td><td>{r.count}</td><td>{srcCount(r)}</td><td><button type="button" className="subtle" onClick={()=>hide(r.term)}>Hide</button></td></tr>)}</tbody></table></div>}
  </div>
  {o.view==='cloud'&&layout?.dropped.length>0&&<p className="muted wc-dropped">{layout.dropped.length} less frequent term{layout.dropped.length===1?'':'s'} did not fit: {layout.dropped.slice(0,12).map(d=>d.term).join(', ')}{layout.dropped.length>12?'…':''}. Lower the largest size or max words, or use the Bars or Table view to see them all.</p>}
  {legend.length>0&&<ul className="wc-legend" aria-label="Main source colours">{legend.map(l=><li key={l.id}><i style={{background:l.color}}/>{l.name}</li>)}</ul>}
  {o.scheme==='sequential'&&<p className="muted">{o.reverse?'Lower':'Higher'}-contrast colours mark more frequent terms.</p>}
  <div className="wc-actions"><button type="button" onClick={exportSVG} disabled={!layout?.words.length}>Export SVG</button><button type="button" onClick={exportPNG} disabled={!layout?.words.length}>Export PNG</button>{note&&<span className="error">{note}</span>}</div>
  <p className="muted wc-caption">{caption}</p>
 </section>;}
