import React,{useMemo,useRef,useState} from 'react';
import {taskAnchor} from '../processing-domain.mjs';
import {citationRestricted} from '../analysis-memos.mjs';
import {canSeekTurn} from '../transcript-alignment.mjs';
import {fmt} from '../components/ui.jsx';
import './wording-review-queue.css';

export function WordingReviewQueue({state,document:doc,mediaRef,onSelect,onTask}){
 const [selectedId,setSelectedId]=useState(''),[filter,setFilter]=useState('open'),[notice,setNotice]=useState(''),detail=useRef(null);
 const tasks=useMemo(()=>(state.reviewTasks||[]).filter(t=>t.documentId===doc.id&&t.kind==='transcript-wording'),[state,doc.id]);
 const rows=tasks.filter(t=>filter==='all'||!['accepted','revised','rejected'].includes(t.status)),task=rows.find(t=>t.id===selectedId)||rows[0],current=task&&taskAnchor(state,task),restricted=task&&citationRestricted(state,task);
 const turn=task&&(doc.turns||[]).find(t=>t.start<=task.start&&t.end>task.start);
 function listen(){setNotice('');if(!current||!canSeekTurn(doc,turn)||!mediaRef.current)return;mediaRef.current.currentTime=Math.max(0,turn.timeStart-3);mediaRef.current.play()?.catch(()=>setNotice('Use the recording controls to start playback.'));}
 return <section className="wording-queue" aria-label="Meaning-changing wording review"><header><h2>Wording review queue</h2><p>Listen around the question and response before changing wording. A suggested correction remains a proposal.</p></header><div className="wq-controls"><label className="field"><span>Review status</span><select aria-label="Wording task status" value={filter} onChange={e=>{setFilter(e.target.value);setSelectedId('');}}><option value="open">Open and deferred tasks</option><option value="all">All wording tasks</option></select></label><label className="field"><span>Passage to check</span><select aria-label="Wording review passage" value={task?.id||''} onChange={e=>{setSelectedId(e.target.value);setNotice('');}}>{rows.map((t,i)=><option key={t.id} value={t.id}>{i+1}. {citationRestricted(state,t)?'Passage restricted':taskAnchor(state,t)?t.issue:'Source changed — anchor review needed'}</option>)}</select></label></div><p className="muted">{rows.length} matching tasks · {tasks.length} saved wording tasks. Reviewing a task does not itself correct the transcript.</p>{task?<article ref={detail}><small>{task.priority||'Review'} · {task.status}</small>{!current?<p role="status">This saved passage no longer matches the source. Re-anchor it in the passage review desk before using its wording proposal.</p>:restricted?<p>Passage details are withheld pending scope review. Check its source permissions before using it in the analysis.</p>:<><h3>{task.issue}</h3><blockquote>{task.text}</blockquote><p>{task.rationale}</p>{task.proposedCorrection&&<details><summary>Unverified wording proposal</summary><p>{typeof task.proposedCorrection==='string'?task.proposedCorrection:'Inspect the saved proposal in the review desk.'}</p></details>}</>}<div className="actions"><button disabled={!current||!canSeekTurn(doc,turn)||!doc.mediaKey} onClick={listen}>Listen before {Number.isFinite(turn?.timeStart)?fmt(turn.timeStart):'this passage'}</button><button disabled={!current} onClick={()=>onSelect(task)}>Open exact source passage</button><button onClick={()=>onTask(task.id)}>Review task & record reasoning</button></div>{notice&&<p role="status">{notice}</p>}</article>:<p>No wording tasks match this filter. This does not establish transcript accuracy.</p>}</section>;
}
