import test from 'node:test';
import assert from 'node:assert/strict';
import {unzipSync,strFromU8} from 'fflate';
import {annotatedSourceModel,annotatedSourceHTML,annotatedSourceDOCX} from '../src/annotated-source-export.mjs';
import {teamAccess,visibleProjectState} from '../src/team-policy.mjs';

function fixture(){const text='😀 Public ABC <script>alert("x")</script> PRIVATE end';return {name:'Synthetic export',settings:{},documents:[{id:'d',name:'Interview <one>',text,revision:2,reviewStatus:'Pending',attributes:{secret:'UNRELATED-METADATA'},versions:[{text:'OLD-VERSION-SECRET'}]}],codes:[{id:'parent',name:'Parent',color:'#227799'},{id:'a',name:'Experience',parentId:'parent',color:'#227799'},{id:'b',name:'Risk',color:'red;background:url(https://unsafe)'}],codings:[],memos:[{content:'PRIVATE-MEMO'}]};}
function coding(state,id,start,end,codeId='a',coder='alice',status='accepted'){const text=Array.from(state.documents[0].text).slice(start,end).join('');state.codings.push({id,documentId:'d',start,end,text,sourceRevision:2,codeId,coder,status});return state.codings.at(-1);}

test('annotated source retains complete Unicode text and all overlapping applications',()=>{const s=fixture();coding(s,'c1',0,12);coding(s,'c2',4,15,'b','bob','provisional');const m=annotatedSourceModel(s,'d');assert.equal(m.segments.map(c=>c.text).join(''),s.documents[0].text);assert.deepEqual(m.segments.find(c=>c.start===4).applications,[1,2]);assert.equal(m.applications[0].text,'😀 Public ABC');assert.equal(m.applications[0].code,'Parent / Experience');assert.equal(m.applications[1].color,'#537a92');const html=annotatedSourceHTML(s,'d');assert.ok(html.includes('&lt;'));assert.ok(html.includes('&gt;'));assert.ok(!html.includes('<script>'));assert.ok(html.includes('href="#application-2"'));assert.ok(!html.includes('UNRELATED-METADATA'));assert.ok(!html.includes('OLD-VERSION-SECRET'));assert.ok(!html.includes('PRIVATE-MEMO'));});

test('restricted overlapping intervals suppress text, intersecting full quotes, rationale and arbitrary metadata in both formats',()=>{const s=fixture(),d=s.documents[0],start=Array.from(d.text).join('').indexOf('PRIVATE')-1;d.reviewFlags=[{start,end:start+7,reason:'PRIVATE-REASON'},{start:start+3,end:start+8}];coding(s,'public',0,12);const privateCoding=coding(s,'private',start-2,start+8);privateCoding.reviewNote='PRIVATE-REVIEW';const m=annotatedSourceModel(s,'d');assert.equal(m.applications.length,1);assert.equal(m.segments.filter(c=>c.restricted).length,1);const html=annotatedSourceHTML(s,'d');const docx=unzipSync(annotatedSourceDOCX(s,'d'));for(const exported of [html,strFromU8(docx['word/document.xml'])]){assert.ok(!exported.includes('PRIVATE'));assert.ok(!exported.includes('UNRELATED-METADATA'));assert.ok(!exported.includes('OLD-VERSION-SECRET'));assert.ok(exported.includes('Passage withheld'));}assert.ok(docx['[Content_Types].xml']);assert.ok(strFromU8(docx['word/_rels/document.xml.rels']).includes('styles.xml'));});

test('filters coder and layer and excludes mismatched, stale, deleted and media applications',()=>{const s=fixture();coding(s,'a',0,1);coding(s,'b',2,8,'a','bob');coding(s,'c',2,8,'b','alice','provisional');coding(s,'stale',2,8).sourceRevision=1;coding(s,'bad',2,8).text='MISMATCH';coding(s,'deleted',2,8).deletedAt='now';coding(s,'media',2,8).kind='media';const m=annotatedSourceModel(s,'d',{coder:'alice',status:'accepted'});assert.deepEqual(m.applications.map(c=>c.id),['a']);assert.equal(m.excludedApplications,3);assert.throws(()=>annotatedSourceModel(s,'d',{status:'rejected'}),/supported/);});

test('blind coder export accepts only authenticated projection and cannot reconstruct another coder from metadata',()=>{const s=fixture();s.settings.teamAccess={blindCoding:true};coding(s,'own',0,1,'a','alice');coding(s,'other',2,8,'b','bob');s.documents[0].analysis={quote:'HIDDEN-ANALYSIS'};const visible=visibleProjectState(s,teamAccess(s,'coder',{id:'alice'}));const m=annotatedSourceModel(visible,'d');assert.deepEqual(m.applications.map(c=>c.coder),['alice']);assert.ok(!annotatedSourceHTML(visible,'d').includes('bob'));assert.ok(!annotatedSourceHTML(visible,'d').includes('HIDDEN-ANALYSIS'));});

test('malformed restricted anchors fail closed and overlapping out of date coding never leaks old quotation',()=>{const s=fixture();s.documents[0].reviewFlags=[{start:3,end:9999}];assert.throws(()=>annotatedSourceHTML(s,'d'),/invalid consent anchors/);assert.throws(()=>annotatedSourceDOCX(s,'d'),/invalid consent anchors/);delete s.documents[0].reviewFlags;coding(s,'a',0,1).text='OLD-QUOTATION';assert.ok(!annotatedSourceHTML(s,'d').includes('OLD-QUOTATION'));});

test('DOCX word content preserves whitespace, line breaks and escaped text',()=>{const s=fixture();s.documents[0].text='Line 1\nLine 2\t& < > 😀';s.documents[0].direction='rtl';const files=unzipSync(annotatedSourceDOCX(s,'d')),xml=strFromU8(files['word/document.xml']);assert.ok(xml.includes('<w:bidi/>'));assert.ok(xml.includes('<w:br/>'));assert.ok(xml.includes('&amp; &lt; &gt; 😀'));assert.ok(xml.includes('xml:space="preserve"'));});


test('independent DOCX reader extracts Unicode, overlap references and redacted source',async()=>{const {default:mammoth}=await import('mammoth');const s=fixture(),d=s.documents[0];coding(s,'a',0,12);coding(s,'b',4,15,'b','bob');d.reviewFlags=[{start:39,end:46}];const {value}=await mammoth.extractRawText({buffer:Buffer.from(annotatedSourceDOCX(s,'d'))});assert.ok(value.includes('😀 Public ABC'));assert.ok(value.includes('[1][2]'));assert.ok(value.includes('Parent / Experience'));assert.ok(value.includes('Passage withheld'));assert.ok(!value.includes('PRIVATE'));assert.ok(!value.includes('PRIVATE-MEMO'));});


test('explicit included scope restores annotation eligibility while a stale included restriction stays withheld',()=>{const s=fixture();coding(s,'a',0,12);s.documents[0].reviewFlags=[{start:0,end:12,status:'included',anchorStatus:'current'}];assert.equal(annotatedSourceModel(s,'d').applications.length,1);s.documents[0].reviewFlags[0].anchorStatus='needs_review';assert.equal(annotatedSourceModel(s,'d').applications.length,0);assert.ok(annotatedSourceHTML(s,'d').includes('Passage withheld'));});
