import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,applyOperation} from '../src/domain.mjs';
import {scopedCodings,analysisMatrix} from '../src/analysis-domain.mjs';
import {validateProjectMap,mapInScope,mapGraphML,codePortrait,matrixRows,reorderCodes} from '../src/project-map.mjs';
import {hierarchyLayout} from '../src/hierarchy-layout.mjs';
import {xlsx} from '../src/report-export.mjs';
import {unzipSync,strFromU8} from 'fflate';
function sample(){const s=emptyState();s.documents=[{id:'d',name:'Interview',text:'0123456789ABCDEFGHIJ',revision:1,mediaKey:'audio',turns:[{start:0,end:10,timeStart:0,timeEnd:2.25}]},{id:'e',name:'Second',text:'abcdef',revision:1}];s.codes=[{id:'parent',name:'Root',codable:false},{id:'a',name:'A',parentId:'parent',color:'#123456'},{id:'b',name:'B',parentId:'parent'}];s.cases=[{id:'c',name:'Case',documentIds:['d']}];s.codings=[{id:'one',documentId:'d',codeId:'a',start:0,end:10,text:'0123456789',sourceRevision:1,coder:'coder',status:'accepted'},{id:'two',documentId:'d',codeId:'b',start:5,end:15,text:'56789ABCDE',sourceRevision:1,coder:'coder',status:'coded'},{id:'other',documentId:'e',codeId:'a',start:0,end:3,text:'abc',sourceRevision:1,coder:'coder',status:'coded'}];return s;}
const map=()=>({nodes:[{id:'n1',label:'Theme',kind:'code',refId:'a',x:0,y:0},{id:'n2',label:'Interpretation',kind:'concept',x:100,y:200}],links:[{id:'l',from:'n1',to:'n2',label:'supports',codingIds:['one']}]});
test('concept map saves exact positions and human links without changing sources or timing',()=>{const s=sample(),before=JSON.stringify(s.documents);const saved=applyOperation(s,{type:'map.save',data:{map:map()}},'human','owner');assert.equal(saved.conceptMap.nodes[0].x,0);assert.equal(saved.conceptMap.links[0].codingIds[0],'one');assert.equal(saved.conceptMap.modifiedBy,'human');assert.equal(JSON.stringify(saved.documents),before);assert.throws(()=>applyOperation(s,{type:'map.save',data:{map:map()}},'reader','viewer'),/Read-only/);});
test('map validation rejects dangling records, nonfinite positions, duplicate edges and consent-pending evidence',()=>{const s=sample();s.documents[0].reviewFlags=[{start:0,end:2}];assert.throws(()=>validateProjectMap(s,map()),/consent-cleared/);s.documents[0].reviewFlags=[];const m=map();m.nodes[0].x=Infinity;assert.throws(()=>validateProjectMap(s,m),/node/);m.nodes[0].x=0;m.links.push({...m.links[0]});assert.throws(()=>validateProjectMap(s,m),/Duplicate/);m.links.pop();m.nodes[0].refId='missing';assert.throws(()=>validateProjectMap(s,m),/reference/);});
test('map exported evidence respects coder/source scope and XML escaping',()=>{const s=sample(),m=map();m.links[0].label='a < b & c';const view=mapInScope(m,scopedCodings(s,{sourceId:'e'}));assert.deepEqual(view.links[0].codingIds,[]);const xml=mapGraphML(view);assert.match(xml,/a &lt; b &amp; c/);assert.match(xml,/\[\]/);assert.doesNotMatch(xml,/0123456789/);});
test('hierarchy allocation reports summed code coverage separately from true scope union',()=>{const s=sample(),rows=scopedCodings(s),h=hierarchyLayout(s,rows,'characters');assert.equal(h.total,23);assert.equal(h.scopeTotal,18);assert.equal(h.segments.find(x=>x.code.id==='parent').weight,23);assert.equal(h.tiles.reduce((n,t)=>n+t.weight,0),23);const applications=hierarchyLayout(s,rows);assert.equal(applications.total,3);assert.equal(applications.scopeTotal,3);});
test('hierarchy seconds excludes text turn timing and obsolete recording ranges',()=>{const s=sample();s.codings.push({id:'timed',documentId:'d',codeId:'a',kind:'media',recordingKey:'audio',timeStart:0,timeEnd:2.25,coder:'coder',status:'coded'},{id:'old',documentId:'d',codeId:'b',kind:'media',recordingKey:'old',timeStart:0,timeEnd:10,coder:'coder',status:'coded'});const h=hierarchyLayout(s,scopedCodings(s),'seconds');assert.equal(h.total,2.25);assert.equal(h.scopeTotal,2.25);});
test('multi-source portrait normalizes codepoint positions and follows consent-filtered evidence',()=>{const s=sample();s.documents[0].reviewFlags=[{start:0,end:10}];const p=codePortrait(s,scopedCodings(s),{bins:4});assert.deepEqual(p[0].cells.map(c=>[c.start,c.end]),[[0,5],[5,10],[10,15],[15,20]]);assert.equal(p[0].cells.flatMap(c=>c.rows).length,0);assert.equal(p[1].cells.flatMap(c=>c.rows).length,2);});
test('matrix XLSX preserves zero numeric values, selected metric and deduplicated union totals',()=>{const s=sample(),matrix=analysisMatrix(s,scopedCodings(s),{metric:'characters',rowMode:'direct'}),table=matrixRows(matrix,{metric:'characters',scope:'scope',group:'source',rowMode:'direct'});assert.equal(table.at(-1).at(-1),18);assert.equal(table[0][1],'Text coverage (codepoints)');const sheet=strFromU8(unzipSync(xlsx(table))['xl/worksheets/sheet1.xml']);assert.match(sheet,/<v>0<\/v>/);assert.match(sheet,/Deduplicated scope total/);});
test('code drag order is a full deterministic permutation and partial orders are rejected',()=>{const s=sample();assert.deepEqual(reorderCodes(s.codes,'b','a'),['parent','b','a']);assert.throws(()=>applyOperation(s,{type:'code.order',data:{ids:['a']}},'owner','owner'),/Invalid code order/);});
test('case memo binds to actual caseId and researcher edit provenance',()=>{const s=sample(),saved=applyOperation(s,{type:'memo.save',data:{caseId:'c',title:'Case interpretation',content:'Analytical note'}},'writer','coder');assert.equal(saved.memos[0].caseId,'c');assert.equal(saved.memos[0].author,'writer');const next=applyOperation(saved,{type:'memo.save',data:{...saved.memos[0],content:'Revised interpretation'}},'writer','coder');assert.equal(next.memos[0].versions.length,1);assert.throws(()=>applyOperation(s,{type:'memo.save',data:{caseId:'missing',content:'a'}},'writer','coder'),/case is missing/);});

test('code merge retains saved concept map positions, links and resolvable evidence',()=>{let s=applyOperation(sample(),{type:'map.save',data:{map:map()}},'owner','owner');const docs=JSON.stringify(s.documents),links=JSON.stringify(s.conceptMap.links);s=applyOperation(s,{type:'code.merge',data:{from:'a',into:'b'}},'owner','owner');assert.equal(s.conceptMap.nodes[0].refId,'b');assert.equal(s.conceptMap.nodes[0].label,'Theme');assert.equal(s.conceptMap.nodes[0].x,0);assert.equal(JSON.stringify(s.conceptMap.links),links);s=applyOperation(s,{type:'map.save',data:{map:s.conceptMap}},'owner','owner');assert.equal(JSON.stringify(s.documents),docs);});
