import test from 'node:test';import assert from 'node:assert/strict';import {decisionDiff,DECISION_DIFF_MAX_BYTES} from '../server/decision-diff.mjs';
const base=()=>({documents:[{id:'d',name:'Synthetic interview',text:'Alpha beta',revision:1,turns:[{start:0,end:10,timeStart:0,timeEnd:0.125}]}],codes:[{id:'c',name:'Theme',description:'Working definition'}],codings:[{id:'a',documentId:'d',codeId:'c',start:0,end:5,text:'Alpha',status:'coded',sourceRevision:1}],memos:[],cases:[],categories:[]});
test('Coding review captures target quotation, exact before/after status and source revision without copying unrelated fields',()=>{const a=base(),b=structuredClone(a);b.codings[0].status='accepted';b.codings[0].reviewNote='Supported by source';b.codings[0].reviewer='reviewer';const diff=decisionDiff(a,b,{type:'coding.review',data:{ids:['a']}}),target=diff.targets.find(t=>t.id==='a');assert.equal(target.quotation,'Alpha');assert.deepEqual(target.revision,{before:1,after:1});assert.deepEqual(target.fields.find(f=>f.field==='status'),{field:'status',before:{present:true,value:'coded'},after:{present:true,value:'accepted'}});assert.equal(target.fields.find(f=>f.field==='reviewNote').before.present,false);assert.equal(diff.changedTargets,1);assert.equal(diff.omittedTargets,0);});
test('Source revision focuses changed long quotation text and preserves original zero/fractional timing',()=>{const a=base(),b=structuredClone(a);a.documents[0].text='x'.repeat(10000)+'Original';b.documents[0].text='x'.repeat(10000)+'Corrected';b.documents[0].revision=2;const sourceHash=JSON.stringify(a),afterHash=JSON.stringify(b),diff=decisionDiff(a,b,{type:'source.revise',data:{id:'d'}}),target=diff.targets[0],field=target.fields.find(f=>f.field==='text');assert.deepEqual(target.revision,{before:1,after:2});assert.ok(field.before.value.preview.includes('Original'));assert.ok(field.after.value.preview.includes('Corrected'));assert.equal(field.before.truncated,true);assert.equal(JSON.stringify(a),sourceHash);assert.equal(JSON.stringify(b),afterHash);assert.deepEqual(a.documents[0].turns[0],{start:0,end:10,timeStart:0,timeEnd:0.125});assert.ok(!target.fields.some(f=>f.field==='turns'));});
test('Added/removed memo and changed case attributes distinguish absent values, null, false and numeric zero',()=>{const a=base(),b=structuredClone(a);a.memos=[{id:'old',title:'Old memo',content:'Working text'}];b.memos=[{id:'new',title:'New memo',content:'Updated interpretation'}];a.cases=[{id:'case',name:'Case',attributes:{zero:null,flag:true}}];b.cases=[{id:'case',name:'Case',attributes:{zero:0,flag:false}}];const diff=decisionDiff(a,b,{type:'case.save',data:{id:'case'}}),target=diff.targets.find(t=>t.id==='case');assert.deepEqual(target.fields[0].before.value,{zero:null,flag:true});assert.deepEqual(target.fields[0].after.value,{zero:0,flag:false});assert.equal(diff.targets.find(t=>t.id==='old').change,'removed');assert.equal(diff.targets.find(t=>t.id==='new').change,'created');});
test('Mass changes and long Unicode values stay under 4 KB with explicit omissions and secret keys redacted',()=>{const a=base(),b=structuredClone(a);b.codings=Array.from({length:500},(_,i)=>({id:'code-'+i,documentId:'d',text:'研究🙂'.repeat(2000),status:'accepted',sourceRevision:1,start:0,end:5}));b.documents[0].attributes={apiKey:'fixture-secret',group:'A'};const diff=decisionDiff(a,b,{type:'autocoding.apply',data:{}});assert.ok(new TextEncoder().encode(JSON.stringify(diff)).byteLength<=DECISION_DIFF_MAX_BYTES);assert.ok(diff.omittedTargets>0);assert.equal(diff.changedTargets,502);assert.ok(!JSON.stringify(diff).includes('fixture-secret'));assert.ok(JSON.stringify(diff).includes('[redacted]'));});
test('Unknown or configuration operations never log request secrets, and unchanged records yield no false differences',()=>{const a=base();for(const type of ['connections.update','settings.save','permissions.update','unknown.action','coding.'+'x'.repeat(5000)])assert.equal(decisionDiff(a,a,{type,data:{token:'fixture-secret'}}),null);assert.deepEqual(decisionDiff(a,a,{type:'coding.review',data:{token:'fixture-secret'}}).targets,[]);});

test('Framework changes expose bounded interpretation and review differences',()=>{const a=base();a.frameworkCells=[{id:'chart',sourceRevision:1,summary:'Provisional summary',status:'draft'}];const b=structuredClone(a);b.frameworkCells[0].status='agent-reviewed';b.frameworkCells[0].reviews=[{note:'Independent synthetic interpretation review.',reviewer:'agent'}];const diff=decisionDiff(a,b,{type:'framework.cell.review',data:{id:'chart'}});assert.equal(diff.changedTargets,1);assert.equal(diff.targets[0].collection,'frameworkCells');assert.equal(diff.targets[0].fields.find(f=>f.field==='status').after.value,'agent-reviewed');assert.ok(new TextEncoder().encode(JSON.stringify(diff)).byteLength<=DECISION_DIFF_MAX_BYTES);});
