import test from 'node:test';import assert from 'node:assert/strict';
import {intervalOverlapMeasures,rectangleOverlapMeasures,compareMediaCoders,mediaComparisonScope,mediaComparisonExportRows} from '../src/media-comparison.mjs';
const rect=(x,y,width,height)=>({x,y,width,height});
const near=(actual,expected)=>assert.ok(Math.abs(actual-expected)<1e-10,`${actual} != ${expected}`);
function fixture(){return {documents:[{id:'audio',text:'',revision:1,mediaKey:'rec',mediaType:'audio/wav'},{id:'image',text:'',revision:1,mediaKey:'pic',mediaType:'image/png',mediaWidth:100,mediaHeight:80},{id:'pdf',text:'',revision:1,mediaKey:'doc',mediaType:'application/pdf'}],codes:[{id:'c',name:'Synthetic code'},{id:'other',name:'Other code'}],codings:[]};}
function add(s,id,kind,coder,extent,extra={}){s.codings.push({id,kind,coder,documentId:kind==='media'?'audio':kind,codeId:'c',status:'coded',sourceRevision:1,...(kind==='media'?{recordingKey:'rec',timeStart:extent[0],timeEnd:extent[1]}:{mediaKey:kind==='image'?'pic':'doc',region:extent}),...extra});}
test('Recording seconds union duplicates and fractional zero ranges and returns correct Jaccard',()=>{const m=intervalOverlapMeasures([[0,1.25],[1,2],[0,1.25]],[[.5,1],[3,4]]);assert.equal(m.left,2);assert.equal(m.right,1.5);assert.equal(m.intersection,.5);assert.equal(m.union,3);assert.equal(m.jaccard,1/6);assert.equal(intervalOverlapMeasures([],[]).jaccard,null);});
test('Rectangle sweep unions overlapping selections instead of adding duplicate area',()=>{const m=rectangleOverlapMeasures([rect(0,0,.5,1),rect(.25,0,.5,1),rect(0,0,.5,1)],[rect(.5,0,.5,1)]);near(m.left,.75);near(m.right,.5);near(m.intersection,.25);near(m.union,1);near(m.jaccard,.25);assert.equal(rectangleOverlapMeasures([],[]).jaccard,null);});
test('Checkerboard crossing rectangle partitions give true two-dimensional union and intersection',()=>{const m=rectangleOverlapMeasures([rect(0,0,1,.25),rect(0,.5,1,.25)],[rect(0,0,.25,1),rect(.5,0,.25,1)]);near(m.left,.5);near(m.right,.5);near(m.intersection,.25);near(m.union,.75);near(m.jaccard,1/3);});
test('Media pair metrics keep seconds, image area, PDF pages and code identities separate',()=>{const s=fixture();add(s,'a','media','one',[0,2]);add(s,'b','media','two',[1,3]);add(s,'ia','image','one',rect(0,0,.5,1));add(s,'ib','image','two',rect(0,0,.5,1));add(s,'pa','pdf','one',{...rect(0,0,50,100),page:1,pageWidth:100,pageHeight:100});add(s,'pb','pdf','two',{...rect(0,0,50,100),page:2,pageWidth:100,pageHeight:100});const r=compareMediaCoders(s,'one','two');const [audio,image,pdf]=r.kinds;near(audio.jaccard,1/3);near(image.jaccard,1);assert.equal(pdf.intersection,0);assert.equal(pdf.union,1);assert.equal(pdf.jaccard,0);assert.equal(image.exact.percent,100);assert.equal(audio.exact.percent,0);assert.equal(r.kappa,undefined);assert.ok(mediaComparisonExportRows(r)[0].includes('Units'));});
test('Exact media code-set agreement detects absent coder and multiple codes without duplicating units',()=>{const s=fixture();add(s,'a','media','one',[0,2]);add(s,'a-dup','media','one',[0,2]);add(s,'b','media','two',[0,2]);add(s,'b-other','media','two',[0,2],{codeId:'other'});const r=compareMediaCoders(s,'one','two');assert.equal(r.kinds[0].exact.units,1);assert.equal(r.kinds[0].exact.matched,0);assert.equal(compareMediaCoders(s,'one','two',{codeId:'c'}).kinds[0].exact.percent,100);assert.throws(()=>compareMediaCoders(s,'one','one'),/distinct/);});
test('Current keys, source revisions and consent/reference/stale sources are excluded before metrics',()=>{const s=fixture();add(s,'good','media','one',[0,1]);add(s,'old-record','media','two',[0,1],{recordingKey:'old'});add(s,'missing-time','media','two',[null,1]);add(s,'stale','media','two',[0,1],{sourceRevision:0});add(s,'deleted','media','two',[0,1],{deletedAt:'today'});add(s,'pending','media','two',[0,1],{status:'needs_review'});assert.deepEqual(mediaComparisonScope(s).codings.map(c=>c.id),['good']);s.documents[0].reviewFlags=[{start:0,end:1}];assert.equal(mediaComparisonScope(s).codings.length,0);s.documents[0].reviewFlags=[];s.documents[0].sourceRole='reference';assert.equal(mediaComparisonScope(s).codings.length,0);});
test('Image/PDF geometry binds media keys; legacy regions after replacement are withheld',()=>{const s=fixture();add(s,'legacy','image','one',rect(0,0,.5,.5),{mediaKey:undefined});add(s,'pinned','image','two',rect(0,0,.5,.5));assert.equal(mediaComparisonScope(s).codings.length,2);s.documents[1].versions=[{mediaKey:'old-pic'}];assert.deepEqual(mediaComparisonScope(s).codings.map(c=>c.id),['pinned']);s.codings[1].mediaKey='old-pic';assert.equal(mediaComparisonScope(s).codings.length,0);});
test('PDF dimension mismatch within a source/page is withheld and dimensions of separate pages may differ',()=>{const s=fixture();add(s,'p1','pdf','one',{...rect(0,0,50,50),page:1,pageWidth:100,pageHeight:100});add(s,'p2','pdf','two',{...rect(0,0,100,100),page:1,pageWidth:200,pageHeight:200});assert.equal(mediaComparisonScope(s).codings.length,0);assert.equal(mediaComparisonScope(s).excluded.dimensionConflict,2);s.codings[1].region.page=2;assert.equal(mediaComparisonScope(s).codings.length,2);s.documents[2].pages=[{number:1,width:200,height:200}];assert.deepEqual(mediaComparisonScope(s).codings.map(c=>c.id),['p2']);});
test('Source, code and decision scopes do not alter original coding or leak other rows',()=>{const s=fixture();add(s,'a','media','one',[0,2],{status:'accepted'});add(s,'b','media','two',[0,2]);add(s,'i','image','two',rect(0,0,1,1));const before=JSON.stringify(s);const r=compareMediaCoders(s,'one','two',{sourceId:'audio',status:'accepted'});assert.equal(r.kinds[0].applicationCount,1);assert.equal(r.kinds[1].applicationCount,0);assert.equal(r.kinds[0].jaccard,0);assert.equal(JSON.stringify(s),before);});
test('Rectangle sweep matches a discrete independent grid oracle across random overlapping regions',()=>{let seed=51;const rand=n=>{seed=(1664525*seed+1013904223)>>>0;return seed%n;};for(let run=0;run<100;run++){const left=[],right=[];for(let j=0;j<8;j++){const x=rand(5),y=rand(5),r=rect(x,y,1+rand(5-x),1+rand(5-y));(j<4?left:right).push(r);}let a=0,b=0,i=0;for(let x=0;x<5;x++)for(let y=0;y<5;y++){const inside=list=>list.some(r=>r.x<=x&&r.x+r.width>x&&r.y<=y&&r.y+r.height>y),l=inside(left),r=inside(right);a+=l;b+=r;i+=l&&r;}const m=rectangleOverlapMeasures(left,right);assert.equal(m.left,a);assert.equal(m.right,b);assert.equal(m.intersection,i);assert.equal(m.union,a+b-i);}});
