import test from 'node:test';import assert from 'node:assert/strict';
import {referenceToken,tokenizeMemo,resolveMemoReference,memoReferenceMetadata,insertMemoReference} from '../src/memo-references.mjs';import {emptyState,applyOperation} from '../src/domain.mjs';import {teamAccess,visibleProjectState} from '../src/team-policy.mjs';import {exportQDPX} from '../src/refi.mjs';import {unzipSync,strFromU8} from 'fflate';
function fixture(){return {...emptyState('Synthetic stable memo links'),documents:[{id:'d:1',name:'Source',revision:1,text:'😀 evidence'}],codes:[{id:'c',name:'Theme'},{id:'c2',name:'Theme'}],cases:[{id:'k',name:'Case',documentIds:['d:1'],attributes:{}}],memos:[{id:'m',author:'a',title:'Visible',content:'Plain text'},{id:'hidden',author:'b',title:'Hidden private title',content:'Other decision'}]};}
test('Explicit Unicode record IDs tokenize with exact codepoint offsets; malformed tokens remain plain text',()=>{const id='source 😀 /:{}',token=referenceToken('source',id),text='😀 intro '+token+'\n<script>unsafe()</script> @memo{%ZZ}';const parts=tokenizeMemo(text),r=parts.find(p=>p.kind==='reference');assert.equal(r.id,id);assert.equal(r.start,8);assert.equal(Array.from(text).slice(r.start,r.end).join(''),token);assert.equal(parts.map(p=>p.text).join(''),text);assert.equal(parts.filter(p=>p.kind==='reference').length,1);assert.throws(()=>referenceToken('coding','x'));assert.equal(tokenizeMemo(referenceToken('source','😀'.repeat(200)))[0].id,'😀'.repeat(200));});
test('Resolution follows record ID through rename and never redirects duplicate names or missing/deleted records',()=>{const s=fixture();assert.equal(resolveMemoReference(s,'code','c').record.id,'c');s.codes[0].name='Renamed';assert.equal(resolveMemoReference(s,'code','c').label,'Renamed');s.codes[0].deletedAt='now';assert.equal(resolveMemoReference(s,'code','c').available,false);assert.equal(resolveMemoReference(s,'code','missing').available,false);assert.equal(resolveMemoReference(s,'memo','hidden',{blind:true,actor:'a'}).available,false);});
test('Editor insertion never splits an astral character and preserves the remaining text',()=>{const r=insertMemoReference('😀 tail','code','c',1);assert.equal(r.content,'😀'+referenceToken('code','c')+' tail');assert.equal(r.cursor,2+referenceToken('code','c').length);});
test('Memo saves derive metadata rather than accepting spoofed references and retain version provenance',()=>{const s=fixture(),content='😀 '+referenceToken('source','d:1')+' '+referenceToken('code','c'),op={type:'memo.save',data:{title:'Link memo',content,references:[{kind:'memo',id:'hidden',labelAtSave:'Spoofed'}]}},before=structuredClone(op);const saved=applyOperation(s,op,'a');assert.deepEqual(op,before);const m=saved.memos.at(-1);assert.deepEqual(m.references.map(r=>[r.kind,r.id]),[['source','d:1'],['code','c']]);const edited=applyOperation(saved,{type:'memo.save',data:{id:m.id,title:'Edited',content:'New '+content}},'a');assert.equal(edited.memos.at(-1).versions[0].references.length,2);});
test('Blind memo saves and projection cannot reveal names of another author through reference metadata',()=>{let s=fixture();s.settings.teamAccess={blindCoding:true};const content=referenceToken('memo','hidden'),refs=memoReferenceMetadata(s,content,'a','coder');assert.equal(refs[0].availableAtSave,false);assert.ok(!JSON.stringify(refs).includes('Hidden private'));s.memos[0].content=content;s.memos[0].references=[{kind:'memo',id:'hidden',labelAtSave:'Hidden private title',availableAtSave:true}];const v=visibleProjectState(s,teamAccess(s,'coder',{id:'a'}));assert.ok(!JSON.stringify(v).includes('Hidden private title'));assert.equal(v.memos[0].references[0].availableAtSave,false);});
test('Native JSON preserves link IDs and REFI loss sidecar identifies plain-text-only standard notes',()=>{const s=applyOperation(fixture(),{type:'memo.save',data:{title:'Link export',content:referenceToken('code','c')}},'a'),files=unzipSync(exportQDPX(s)),native=JSON.parse(strFromU8(files['research-weave.json'])).state,scope=JSON.parse(strFromU8(files['research-weave-exchange-scope.json']));assert.equal(native.memos.at(-1).references[0].id,'c');assert.ok(scope.nativeOnly.some(v=>v.includes('Memo @code')));});

test('Blind projection reconstructs legacy/spoofed reference metadata and cannot expose stored hidden titles',()=>{const s=fixture();s.settings.teamAccess={blindCoding:true};for(const references of [{legacy:'Hidden private title'},[{kind:'memo',id:'hidden',labelAtSave:'Hidden private title'}]]){s.memos[0].content=referenceToken('memo','hidden');s.memos[0].references=references;const projected=visibleProjectState(s,teamAccess(s,'coder',{id:'a'}));assert.equal(projected.memos[0].references[0].availableAtSave,false);assert.ok(!JSON.stringify(projected).includes('Hidden private title'));assert.deepEqual(s.memos[0].references,references);}});
