import test from 'node:test';import assert from 'node:assert/strict';
import initSqlJs from 'sql.js';
import {normalizeNativeTables,nativeProjectChoices,readNativeProject,utf8Boundary,isSQLite} from '../src/native-project-import.mjs';
const SQL=await initSqlJs();
const plain=html=>html.replace(/<[^>]+>/g,'').replaceAll('&amp;','&');
function aqda(){return {project:[{id:1,name:'Study',description:'Research',shared_folder:'SECRET_PATH'}],document:[{id:1,project_id:1,name:'Interview',source_type:'text',content:'A😀éB',exclude_from_ai:0}],code:[{id:1,project_id:1,name:'Theme',parent_id:null}],coding:[{id:1,document_id:1,code_id:1,start_pos:1,end_pos:3,selected_text:'😀é',coder:'Original coder',offset_unit:'codepoint'}],memo:[{id:1,project_id:1,document_id:1,code_id:1,start_pos:1,end_pos:3,title:'Analytical memo',content:'Interpretation',offset_unit:'codepoint'}],document_variable:[{document_id:1,key:'Region',value:'North'}],setting:[{key:'token',value:'SECRET_TOKEN'}]};}
function taguette(){return {projects:[{id:1,name:'Study'}],documents:[{id:1,project_id:1,name:'Interview',contents:'<p>A😀é</p><p>β &amp; C<br>tail</p>'}],tags:[{id:1,project_id:1,path:'Community > participation',description:'Meaning'}],highlights:[{id:1,document_id:1,start_offset:1,end_offset:7,snippet:'<p>😀é</p>'}],highlight_tags:[{highlight_id:1,tag_id:1}],users:[{login:'secret',hashed_password:'SECRET_PASSWORD'}]};}
test('AQDA Unicode codepoints, authorship, memo links and variables survive without credentials or permissions',()=>{const s=normalizeNativeTables('aqda',aqda());assert.equal(s.codings[0].text,'😀é');assert.equal(s.codings[0].start,1);assert.equal(s.codings[0].status,'coded');assert.equal(s.codings[0].coder,'Original coder');assert.equal(s.memos[0].documentId,s.documents[0].id);assert.equal(s.memos[0].codeId,s.codes[0].id);assert.equal(s.memos[0].citations[0].text,'😀é');assert.equal(s.documents[0].attributes.Region,'North');assert.equal(s.documents[0].excludeAI,true);assert.equal(s.nativeImport.permissionsImported,false);assert.doesNotMatch(JSON.stringify(s),/SECRET_TOKEN|SECRET_PATH/);});
test('AQDA deleted layers excluded and uncertain/repaired anchors withheld, without quotation search',()=>{const t=aqda();t.code.push({id:2,project_id:1,name:'Removed',deleted_at:'2026-01-01'});t.coding.push({id:2,document_id:1,code_id:2,start_pos:0,end_pos:1,selected_text:'A',offset_unit:'codepoint'});t.coding[0].offset_unit='legacy_utf16';t.memo[0].repair_status='converted_utf16_unverified';const s=normalizeNativeTables('aqda',t);assert.equal(s.codes.length,1);assert.equal(s.codings.length,1);assert.equal(s.codings[0].status,'needs_review');assert.equal(s.memos[0].anchorStatus,'needs_review');assert.equal(s.memos[0].start,undefined);assert.ok(s.nativeImport.excluded.length);});
test('AQDA audio transcript retained without binary payload or inferred turn times',()=>{const t=aqda();t.document[0].source_type='audio';t.document[0].transcript='A😀éB';t.document[0].content='data:audio/wav;base64,PRIVATE_BINARY';const s=normalizeNativeTables('aqda',t);assert.equal(s.documents[0].text,'A😀éB');assert.deepEqual(s.documents[0].turns,[]);assert.doesNotMatch(JSON.stringify(s),/PRIVATE_BINARY/);assert.ok(s.nativeImport.losses.some(l=>l.kind==='media'));});
test('Taguette byte offsets convert at exact UTF8 boundaries over concatenated text nodes',()=>{const s=normalizeNativeTables('taguette',taguette(),{htmlText:plain});assert.equal(s.documents[0].text,'A😀éβ & Ctail');assert.equal(s.codings[0].start,1);assert.equal(s.codings[0].end,3);assert.equal(s.codings[0].status,'coded');assert.match(s.codings[0].coder,/author unidentified/);assert.equal(s.codings[0].date,null);assert.equal(s.codes[0].parentId,null);assert.doesNotMatch(JSON.stringify(s),/SECRET_PASSWORD/);assert.equal(utf8Boundary('A😀é',2),null);assert.equal(utf8Boundary('A😀é',7),3);});
test('Taguette partial bytes and inaccurate snippets are withheld, not rounded or reanchored',()=>{const t=taguette();t.highlights[0].start_offset=2;let s=normalizeNativeTables('taguette',t,{htmlText:plain});assert.equal(s.codings[0].status,'needs_review');t.highlights[0].start_offset=1;t.highlights[0].snippet='<p>incorrect</p>';s=normalizeNativeTables('taguette',t,{htmlText:plain});assert.equal(s.codings[0].status,'needs_review');assert.equal(s.codings[0].text,'incorrect');assert.ok(s.nativeImport.losses.some(l=>l.kind==='anchor'));});
test('selection rejects multiple projects and isolates exact selected project',()=>{const t=aqda();t.project.push({id:2,name:'Other private study'});t.document.push({id:2,project_id:2,name:'Other',content:'secret'});assert.throws(()=>normalizeNativeTables('aqda',t),/multiple projects/);const s=normalizeNativeTables('aqda',t,{projectId:'1'});assert.equal(s.documents.length,1);assert.doesNotMatch(JSON.stringify(s),/Other private study|secret/);assert.throws(()=>normalizeNativeTables('aqda',t,{projectId:3}),/missing or deleted/);});
test('schema-detected SQL reader allows safe table columns only and leaves database unchanged',()=>{const db=new SQL.Database();db.run(`CREATE TABLE project(id INTEGER,name TEXT,description TEXT,shared_folder TEXT);CREATE TABLE document(id INTEGER,project_id INTEGER,name TEXT,content TEXT);CREATE TABLE code(id INTEGER,project_id INTEGER,name TEXT);CREATE TABLE coding(id INTEGER,document_id INTEGER,code_id INTEGER,start_pos INTEGER,end_pos INTEGER,selected_text TEXT,offset_unit TEXT);CREATE TABLE setting(key TEXT,value TEXT);INSERT INTO project VALUES(1,'Study','Research','SECRET_SHARE');INSERT INTO document VALUES(1,1,'Transcript','Unicode 😀');INSERT INTO code VALUES(1,1,'Code');INSERT INTO coding VALUES(1,1,1,8,9,'😀','codepoint');INSERT INTO setting VALUES('api_key','SECRET_CREDENTIAL');`);const before=db.export();assert.equal(isSQLite(before),true);assert.equal(nativeProjectChoices(db).format,'aqda');const statements=[];const original=db.exec.bind(db);db.exec=(sql,params)=>{statements.push(sql);return original(sql,params);};const s=readNativeProject(db);assert.equal(s.codings[0].status,'coded');assert.doesNotMatch(statements.join('\n'),/SELECT \*|FROM "setting"|shared_folder/);assert.doesNotMatch(JSON.stringify(s),/SECRET_SHARE|SECRET_CREDENTIAL/);assert.deepEqual(db.export(),before);db.close();});
test('Taguette schema reader maps shared highlights without importing user tables',()=>{const db=new SQL.Database();db.run(`CREATE TABLE projects(id INTEGER,name TEXT);CREATE TABLE documents(id INTEGER,project_id INTEGER,name TEXT,contents TEXT);CREATE TABLE tags(id INTEGER,project_id INTEGER,path TEXT);CREATE TABLE highlights(id INTEGER,document_id INTEGER,start_offset INTEGER,end_offset INTEGER,snippet TEXT);CREATE TABLE highlight_tags(highlight_id INTEGER,tag_id INTEGER);CREATE TABLE users(login TEXT,hashed_password TEXT);INSERT INTO projects VALUES(1,'Study');INSERT INTO documents VALUES(1,1,'Transcript','<p>A😀é</p>');INSERT INTO tags VALUES(1,1,'Theme');INSERT INTO highlights VALUES(1,1,1,7,'<p>😀é</p>');INSERT INTO highlight_tags VALUES(1,1);INSERT INTO users VALUES('alice','SECRET_PASSWORD');`);const s=readNativeProject(db,{htmlText:plain});assert.equal(s.codings[0].status,'coded');assert.doesNotMatch(JSON.stringify(s),/SECRET_PASSWORD|alice/);db.run("INSERT INTO projects VALUES(2,'Other')");assert.throws(()=>readNativeProject(db,{htmlText:plain}),/multiple projects/);assert.equal(readNativeProject(db,{projectId:1,htmlText:plain}).documents.length,1);db.close();});

test('untagged Taguette highlights become source-linked memos without inferred coding',()=>{const t=taguette();t.highlight_tags=[];const s=normalizeNativeTables('taguette',t,{htmlText:plain});assert.equal(s.codings.length,0);assert.equal(s.memos[0].content,'😀é');assert.equal(s.memos[0].citations[0].start,1);assert.equal(s.memos[0].anchorStatus,'current');assert.equal(s.memos[0].author,'Imported highlight (author unidentified)');});
