import test from 'node:test';import assert from 'node:assert/strict';
import {passageDraft,passageIsCurrent,transcriptUnits} from '../src/passage-selection.mjs';
import {emptyState,applyOperation,slice} from '../src/domain.mjs';
const document=()=>({id:'d',revision:1,text:'A😀 café\r\n\nمرحبا\nLast line',turns:[]});
test('Source-line units preserve Unicode offsets, blank lines and CRLF without recoding wrapped lines',()=>{const d=document(),units=transcriptUnits(d,'lines');assert.deepEqual(units.map(u=>[u.number,u.start,u.end,u.text]),[[1,0,7,'A😀 café'],[3,10,15,'مرحبا'],[4,16,25,'Last line']]);for(const u of units)assert.equal(slice(d.text,u.start,u.end),u.text);assert.equal(d.text,'A😀 café\r\n\nمرحبا\nLast line');});
test('Turn navigation excludes stale or mismatched anchors and retains missing supplied timing',()=>{const d=document();d.turns=[{id:'t',start:0,end:7,speaker:'One',timeStart:0,timeEnd:null},{id:'bad',start:10,end:15,text:'wrong'},{id:'review',start:16,end:25,anchorStatus:'needs_review'}];const units=transcriptUnits(d);assert.equal(units.length,1);assert.equal(units[0].timeStart,0);assert.equal(units[0].timeEnd,null);assert.equal(units[0].speaker,'One');});
test('Bound drafts reject source switches, changed revisions and mismatched quotation content',()=>{const d=document(),draft=passageDraft(d,1,2);assert.equal(draft.text,'😀');assert.ok(passageIsCurrent(d,draft));assert.equal(passageIsCurrent({...d,id:'other'},draft),false);assert.equal(passageIsCurrent({...d,revision:2},draft),false);assert.equal(passageIsCurrent({...d,text:d.text.replace('😀','X')},draft),false);assert.equal(passageIsCurrent(d,{...draft,stale:true}),false);});
test('Cross-line range preserves exact intervening separators; invalid boundaries are refused',()=>{const d=document();assert.equal(passageDraft(d,5,12).text,'fé\r\n\nمر');for(const [a,b] of [[-1,2],[0,26],[2,2],[1.5,2],[0,NaN]])assert.equal(passageDraft(d,a,b),null);});
const state=()=>({...emptyState('Bound draft regression'),documents:[document()],codes:[{id:'a',name:'A'},{id:'b',name:'B'}]});
test('Write boundary refuses stale revision or quote after transcript changes',()=>{const s=state(),draft=passageDraft(s.documents[0],1,2);for(const data of [{...draft,sourceRevision:0},{...draft,text:'X'},{...draft,start:-1},{...draft,end:99}])assert.throws(()=>applyOperation(s,{type:'coding.create',data:{...data,codeIds:['a']}},'alice'),/Source changed|valid exact source range/);assert.equal(s.codings.length,0);});
test('One exact Unicode passage supports multiple code assignments and independent coder layers',()=>{let s=state(),draft=passageDraft(s.documents[0],1,2);for(const actor of ['alice','bob'])s=applyOperation(s,{type:'coding.create',data:{...draft,codeIds:['a','b']}},actor,'coder');assert.equal(s.codings.length,4);assert.ok(s.codings.every(c=>c.text==='😀'&&c.sourceRevision===1));assert.deepEqual(s.documents,state().documents);});

test('Same-text transcript replacement carries exact current coding forward without promoting stale anchors',()=>{let s=state();s=applyOperation(s,{type:'coding.create',data:{...passageDraft(s.documents[0],1,2),codeIds:['a']}},'alice');s.codings.push({...s.codings[0],id:'stale',status:'needs_review',sourceRevision:0});s=applyOperation(s,{type:'source.transcript',data:{id:'d',text:s.documents[0].text,turns:[]}},'owner');assert.equal(s.documents[0].revision,2);assert.equal(s.codings[0].sourceRevision,2);assert.equal(s.codings[0].text,'😀');assert.equal(s.codings[1].sourceRevision,0);assert.equal(s.codings[1].status,'needs_review');});
