import test from 'node:test';import assert from 'node:assert/strict';import {Miniflare} from 'miniflare';import{readFile,readdir}from'node:fs/promises';import{emptyState}from'../src/domain.mjs';
test('analysis service saves through normal revision/event/backups and closes independently from source loading',async()=>{
 const token='synthetic-analysis-api-token-1234567890',bindings={PRIVATE_IMPORT_TOKEN:token,PRIVATE_ANALYSIS_TOKEN:token},options={modules:true,scriptPath:'dist/server/index.js',compatibilityDate:'2025-10-01',compatibilityFlags:['nodejs_compat'],bindings,d1Databases:['DB'],r2Buckets:['BUCKET']},mf=new Miniflare(options);
 try{
 let db=await mf.getD1Database('DB');for(const file of(await readdir('drizzle')).filter(n=>n.endsWith('.sql')).sort())for(const sql of(await readFile('drizzle/'+file,'utf8')).split('--> statement-breakpoint'))if(sql.trim())await db.prepare(sql).run();
 await db.prepare('INSERT INTO site_settings (key,value) VALUES (?,?)').bind('calibration_owner','owner').run();
 const call=(path,body)=>mf.dispatchFetch('https://app.test/api'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','x-qualityer-import-token':token,'x-qualityer-analysis-token':token},body:body?JSON.stringify(body):undefined});
 const state=emptyState('Synthetic service study');state.documents=['a','b'].map(id=>({id,name:'Synthetic '+id,text:'😀 claim. Contrast.',revision:1}));state.codes=[{id:'code',name:'Synthetic category'}];state.frameworkStudies=[{id:'base',name:'Base',researchQuestion:'What qualifies the accounts?',documentIds:['a','b'],themes:Array.from({length:6},(_,n)=>({id:'t'+n,title:'Category '+n,codeIds:['code']}))}];state.frameworkCells=[];
 assert.equal((await call('/private-import',{state})).status,201);await mf.setOptions({...options,bindings:{...bindings,PRIVATE_IMPORT_TOKEN:'disabled'}});db=await mf.getD1Database('DB');
 const baseline=await(await call('/private-analysis')).json(),quote=id=>({documentId:id,sourceRevision:1,start:0,end:8,text:'😀 claim.',relation:'support'});
 const run={id:'run',name:'Synthetic continuation',method:'Framework Method',scope:'Synthetic two-source account.',documentIds:['a','b'],baseStudyId:'base',meaningUnits:['a','b'].map(id=>({id:'u'+id,documentId:id,lenses:['experiences'],description:'A claim is reported.',interpretation:'A provisional reading.',qualifications:['Unverified claim.'],accountType:'reported-account',citations:[quote(id)]})),contrasts:[],propositions:[{id:'p',title:'Provisional account',descriptions:[{documentId:'a',text:'Claim.'},{documentId:'b',text:'Claim.'}],interpretation:'Shared wording is not an effect.',context:[],alternatives:[],limits:['No effect verified.'],checks:[],citations:[quote('a'),quote('b')]}],limits:['Synthetic.'],review:{mode:'independent-agent-review',note:'Synthetic agent review only.'},cells:['a','b'].flatMap(documentId=>state.frameworkStudies[0].themes.map(t=>({documentId,themeId:t.id,summary:'Description and provisional interpretation.',limitations:['Unverified.'],evidence:[quote(documentId)]})))};
 const payload={revision:baseline.revision,operation:{type:'framework.continuation.add',data:run}};
 assert.equal((await call('/private-analysis',{...payload,revision:99})).status,409);
 const saved=await call('/private-analysis',payload);assert.equal(saved.status,200);const after=await saved.json();assert.equal(after.revision,1);assert.deepEqual(after.state.documents,state.documents);assert.equal(after.state.frameworkCells.length,12);assert.equal(after.state.analysisContinuations[0].status,'agent-reviewed');
 const retry=await(await call('/private-analysis',payload)).json();assert.equal(retry.revision,1);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM events').first()).n,1);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM backups').first()).n,2);
 const altered=structuredClone(payload);altered.operation.data.meaningUnits[0].description='Different account.';assert.equal((await call('/private-analysis',altered)).status,409);
 assert.equal((await call('/me')).status,401);assert.equal((await call('/private-import')).status,401);
 await mf.setOptions({...options,bindings:{PRIVATE_IMPORT_TOKEN:'disabled',PRIVATE_ANALYSIS_TOKEN:'disabled'}});assert.equal((await call('/private-analysis')).status,401);assert.equal((await call('/me')).status,401);
 }finally{await mf.dispose();}
});
