import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeQualCoder} from '../src/qualcoder-import.mjs';
import {scopedCodings} from '../src/analysis-domain.mjs';
import {applyOperation} from '../src/domain.mjs';

function fixture(){return {
 project:[{memo:'Synthetic project memo'}],
 source:[{id:0,name:'Synthetic source',fulltext:'début milieu fin',memo:'Source memo'},{id:1,name:'Emoji source',fulltext:'😀 début fin'},{id:2,name:'External media',fulltext:null,mediapath:'/not-attached.wav'}],
 code_cat:[{catid:0,name:'Category'},{catid:1,name:'Child category',supercatid:0}],
 code_name:[{cid:0,name:'Parent',catid:0},{cid:1,name:'Child',supercid:0,catid:1}],
 code_text:[{ctid:0,cid:1,fid:0,pos0:0,pos1:5,seltext:'début',owner:'historical'},{ctid:1,cid:1,fid:0,pos0:6,pos1:12,seltext:'milieu',owner:'historical'}],
 cases:[{caseid:0,name:'Passage case',memo:'Case memo'},{caseid:1,name:'Whole case'},{caseid:2,name:'Ambiguous case'}],
 case_text:[{id:0,caseid:0,fid:0,pos0:6,pos1:12,owner:'historical',memo:'Link memo'},{id:1,caseid:1,fid:1,pos0:0,pos1:11},{id:2,caseid:1,fid:2,pos0:0,pos1:0},{id:3,caseid:2,fid:1,pos0:2,pos1:7},{id:4,caseid:2,fid:0,pos0:100,pos1:101},{id:5,caseid:2,fid:404,pos0:0,pos1:3}],
 attribute_type:[{name:'Age',valuetype:'numeric',caseOrFile:'case'},{name:'Score',valuetype:'numeric',caseOrFile:'file'},{name:'Text',valuetype:'character',caseOrFile:'file'}],
 attribute:[{id:0,attr_type:'case',name:'Age',value:'0'},{id:1,attr_type:'case',name:'Age',value:''},{id:2,attr_type:'case',name:'Age',value:'unverified'},{id:0,attr_type:'file',name:'Score',value:'3.5'},{id:1,attr_type:'file',name:'Score',value:' '},{id:0,attr_type:'file',name:'Text',value:'évidence'}],
 stored_sql:[{title:'Do not execute',sql:'DROP TABLE source'}],code_av:[{avid:0,fid:2,pos0:1,pos1:20}],annotation:[{anid:0,fid:0,pos0:0,pos1:5,memo:'Passage note',owner:'historical'}],journal:[{jid:0,name:'Journal',jentry:'A synthetic observation',owner:'historical'}]
};}

test('Native zero identifiers remain parent/category references instead of disappearing',()=>{const s=normalizeQualCoder(fixture());assert.equal(s.categories[1].parentId,'0');assert.equal(s.codes[0].categoryId,'0');assert.equal(s.codes[1].parentId,'0');});
test('A case passage retrieves only overlapping coding and never becomes whole-source membership',()=>{const s=normalizeQualCoder(fixture()),c=s.cases[0];assert.deepEqual(c.documentIds,[]);assert.equal(c.passages.length,1);assert.equal(c.passages[0].text,'milieu');assert.equal(c.passages[0].memo,'Link memo');assert.deepEqual(scopedCodings(s,{caseId:'0'}).map(c=>c.id),['1']);const revised=applyOperation(s,{type:'source.revise',data:{id:'0',text:'préfixe '+s.documents[0].text}},'reviewer');assert.equal(revised.cases[0].passages[0].start,14);assert.equal(revised.cases[0].passages[0].sourceRevision,2);});
test('Whole-source links use native Python length and explicit empty media bounds without invented timing',()=>{const s=normalizeQualCoder(fixture());assert.deepEqual(s.cases[1].documentIds,['1','2']);assert.deepEqual(s.cases[1].passages,[]);assert.equal(s.codings.length,2);assert.ok(s.documents.every(d=>d.turns.length===0&&!d.mediaKey));assert.ok(s.importNotes.some(n=>n.includes('does not attach archive media')));});
test('Ambiguous non-BMP, out-of-range and missing-source case passages stay inert with losses',()=>{const t=fixture(),s=normalizeQualCoder(t);assert.deepEqual(s.cases[2].documentIds,[]);assert.deepEqual(s.cases[2].passages,[]);assert.equal(s.nativeImport.records.caseLinks.filter(l=>!l.active).length,3);assert.equal(s.nativeImport.losses.filter(l=>l.kind==='case-anchor').length,3);assert.deepEqual(s.legacy.caseLinks,t.case_text);assert.equal(scopedCodings(s,{caseId:'2'}).length,0);});
test('Declared native numeric types preserve zero/decimal/missing and quarantine invalid values',()=>{const t=fixture(),s=normalizeQualCoder(t);assert.equal(s.cases[0].attributes.Age,0);assert.equal(s.cases[1].attributes.Age,null);assert.equal(s.cases[2].attributes.Age,null);assert.equal(s.documents[0].attributes.Score,3.5);assert.equal(s.documents[1].attributes.Score,null);assert.equal(s.documents[0].attributes.Text,'évidence');assert.equal(s.attributeTypes[0].valueType,'number');assert.equal(s.attributeTypes[2].valueType,'text');assert.deepEqual(s.legacy.attributes,t.attribute);assert.equal(s.nativeImport.losses.filter(l=>l.kind==='attribute').length,1);});
test('Project/source/code/case annotations journals and inert queries survive without importing permissions',()=>{const t=fixture(),before=structuredClone(t),s=normalizeQualCoder(t);assert.equal(s.description,'Synthetic project memo');assert.equal(s.documents[0].memo,'Source memo');assert.equal(s.cases[0].memo,'Case memo');assert.equal(s.memos[0].content,'Passage note');assert.equal(s.journals[0].text,'A synthetic observation');assert.deepEqual(s.legacy.storedQueries,t.stored_sql);assert.equal(s.nativeImport.permissionsImported,false);assert.ok(s.documents.every(d=>d.excludeAI===true));assert.equal(s.settings.teamAccess,undefined);assert.deepEqual(t,before);});

test('stale native quotations remain explicit review records rather than rejecting the study or moving offsets',()=>{const tables={source:[{id:1,name:'Interview',fulltext:'A😀éZ'}],code_name:[{cid:1,name:'Code'}],code_text:[{ctid:1,cid:1,fid:1,pos0:1,pos1:3,seltext:'😀é',owner:'Historic'},{ctid:2,cid:1,fid:1,pos0:1,pos1:3,seltext:'old quotation',owner:'Historic'}]};const s=normalizeQualCoder(tables);assert.equal(s.codings[0].status,'coded');assert.equal(s.codings[1].status,'needs_review');assert.equal(s.codings[1].text,'old quotation');assert.equal(s.codings[1].start,1);assert.equal(s.codings[1].end,3);assert.equal(s.nativeImport.losses.filter(x=>x.kind==='anchor').length,1);assert.equal(s.legacy.originalTextCodings[1].seltext,'old quotation');});
