import test from 'node:test';
import assert from 'node:assert/strict';
import {intervalQuery,literalCorpusSearch,resultIdentity} from '../src/query-intervals.mjs';
import {applyOperation,emptyState} from '../src/domain.mjs';
function fixture(){const s=emptyState('Synthetic query study');s.documents=[{id:'d',text:'😀ABCDEFGHIJKLM abc ABC uncoded',revision:1,mediaKey:'recording-current',alignment:{status:'matched',recordingKey:'recording-current'}}];s.codes=[{id:'a',name:'A'},{id:'child',name:'A child',parentId:'a'},{id:'b',name:'B'}];return s;}
function add(s,id,code,start,end,extra={}){s.codings.push({id,codeId:code,documentId:'d',start,end,text:Array.from(s.documents[0].text).slice(start,end).join(''),coder:'one',status:'coded',sourceRevision:1,...extra});}
const ext=rows=>rows.map(r=>r.kind==='media'?[r.timeStart,r.timeEnd]:[r.start,r.end]);
test('AND splits precise intersections, OR unions touching spans, NOT subtracts islands with retained provenance',()=>{const s=fixture();add(s,'left','a',0,12);add(s,'b1','b',2,4);add(s,'b2','b',7,9);const spec={codeA:'a',codeB:'b'};assert.deepEqual(ext(intervalQuery(s,{...spec,operator:'and'})),[[2,4],[7,9]]);assert.deepEqual(ext(intervalQuery(s,{...spec,operator:'or'})),[[0,12]]);const rows=intervalQuery(s,{...spec,operator:'not'});assert.deepEqual(ext(rows),[[0,2],[4,7],[9,12]]);for(const r of rows){assert.equal(r.text,Array.from(s.documents[0].text).slice(r.start,r.end).join(''));assert.equal(r.provenance[0].codingId,'left');assert.deepEqual(r.relatedProvenance.map(p=>p.codingId),['b1','b2']);assert.equal(r.id,undefined);}add(s,'touch','a',12,14);assert.deepEqual(ext(intervalQuery(s,{codeA:'a'})),[[0,14]]);});
test('NEAR keeps matching original A spans rather than the intersection; zero distance includes touching',()=>{const s=fixture();add(s,'a1','a',0,3);add(s,'a2','a',8,12);add(s,'b1','b',3,6);assert.deepEqual(ext(intervalQuery(s,{codeA:'a',codeB:'b',operator:'near',near:0})),[[0,3]]);assert.deepEqual(ext(intervalQuery(s,{codeA:'a',codeB:'b',operator:'near',near:2})),[[0,3],[8,12]]);assert.deepEqual(intervalQuery(s,{codeA:'a',codeB:'b',operator:'and'}),[]);});
test('Current revision, exact anchors, consent, source, coder, status and descendants define eligibility',()=>{const s=fixture();add(s,'ok','child',0,2,{status:'accepted'});add(s,'wrongrev','a',0,2,{sourceRevision:0});add(s,'wrongtext','a',0,2,{text:'Wrong'});add(s,'deleted','a',0,2,{deletedAt:'today'});add(s,'othercoder','a',0,2,{coder:'two'});add(s,'review','a',0,2,{status:'needs_review'});add(s,'blocked','a',5,7);s.documents[0].reviewFlags=[{start:6,end:8}];assert.equal(intervalQuery(s,{codeA:'a',coder:'one',status:'accepted'})[0].provenance[0].codingId,'ok');assert.equal(intervalQuery(s,{codeA:'a',includeDescendants:false,coder:'one'}).length,0);assert.equal(intervalQuery(s,{source:'missing'}).length,0);s.documents[0].sourceRole='reference';assert.equal(intervalQuery(s).length,0);});
test('Seconds include true zero and fractions, recordings and text units never cross boundaries',()=>{const s=fixture();add(s,'text','a',0,8);add(s,'audioA','a',0,8,{kind:'media',recordingKey:'recording-current',timeStart:0,timeEnd:2.125});add(s,'audioB','b',0,8,{kind:'media',recordingKey:'recording-current',timeStart:.25,timeEnd:.5});add(s,'wrongrecording','b',0,8,{kind:'media',recordingKey:'old-recording',timeStart:1,timeEnd:2});add(s,'missingtime','b',0,8,{kind:'media',recordingKey:'recording-current',timeStart:null,timeEnd:1});assert.deepEqual(ext(intervalQuery(s,{codeA:'a',codeB:'b',operator:'not',kind:'media'})),[[0,.25],[.5,2.125]]);assert.deepEqual(ext(intervalQuery(s,{codeA:'a',codeB:'b',kind:'text'})),[]);s.documents[0].reviewFlags=[{start:1,end:2}];s.documents[0].alignment.status='unbound';assert.equal(intervalQuery(s,{kind:'media'}).length,0);});
test('Passage cases clip exact text and cannot infer audio membership; stale cases are excluded',()=>{const s=fixture();add(s,'a1','a',0,10);s.cases=[{id:'case',documentIds:[],passages:[{documentId:'d',start:3,end:7,text:'CDEF',sourceRevision:1}]}];assert.deepEqual(ext(intervalQuery(s,{caseId:'case'})),[[3,7]]);s.cases[0].passages[0].sourceRevision=0;assert.deepEqual(intervalQuery(s,{caseId:'case'}),[]);});
test('Literal corpus search includes uncoded text, preserves astral/case-folding anchors and case-sensitive matching',()=>{const s=fixture();const insensitive=literalCorpusSearch(s,{text:'abc'});assert.equal(insensitive.length,3);for(const r of insensitive){assert.equal(r.text,Array.from(s.documents[0].text).slice(r.start,r.end).join(''));assert.equal(r.timeStart,null);assert.equal(r.timeEnd,null);assert.deepEqual(r.provenance,[]);}assert.equal(literalCorpusSearch(s,{text:'abc',caseSensitive:true}).length,1);assert.equal(literalCorpusSearch(s,{text:'uncoded'}).length,1);s.documents[0].text='😀İ X i';const r=literalCorpusSearch(s,{text:'i'});assert.equal(r.length,1);assert.equal(r[0].start,5);assert.equal(literalCorpusSearch(s,{text:'i\u0307'})[0].start,1);assert.equal(literalCorpusSearch(s,{text:'😀'})[0].end,1);});
test('Literal exclusions and passage-case scope protect matching and keep missing timing null',()=>{const s=fixture();s.documents[0].turns=[{start:0,end:10,timeStart:0,timeEnd:null}];s.documents[0].reviewFlags=[{start:17,end:19}];assert.equal(literalCorpusSearch(s,{text:'abc'}).length,2);const first=literalCorpusSearch(s,{text:'ABC',caseSensitive:true})[0];assert.equal(first.timeStart,null);s.cases=[{id:'c',passages:[{documentId:'d',start:19,end:22,text:'ABC',sourceRevision:1}]}];assert.equal(literalCorpusSearch(s,{text:'abc',caseId:'c'}).length,1);assert.equal(literalCorpusSearch(s,{text:'abc',caseId:'missing'}).length,0);});
test('Freeze recomputes fragment IDs, creates own exact decisions with provenance and preserves media seconds',()=>{let s=fixture();add(s,'a1','a',0,10);add(s,'b1','b',3,6);const spec={mode:'intervals',codeA:'a',codeB:'b',operator:'not'};const rows=intervalQuery(s,spec),original=structuredClone(s.codings);s=applyOperation(s,{type:'query.results.materialize',data:{name:'Subtracted evidence',spec,resultIds:rows.map(r=>r.queryResultId)}},'researcher','coder');assert.deepEqual(s.codings.slice(0,2),original);const fresh=s.codings.slice(2);assert.deepEqual(ext(fresh),[[0,3],[6,10]]);assert.ok(fresh.every(c=>c.coder==='researcher'&&c.querySources[0]==='a1'&&c.queryResult.relatedProvenance[0].codingId==='b1'));assert.ok(fresh.every(c=>c.id!=='a1'&&c.id!==c.queryResult.resultId));assert.throws(()=>applyOperation(s,{type:'query.results.materialize',data:{name:'Stale',spec,resultIds:['forged']}},'researcher'),/changed/);assert.throws(()=>applyOperation(s,{type:'query.results.save',data:{name:'View query',spec}},'viewer','viewer'),/Read-only/);});
test('Literal freeze has no fabricated original coding IDs and rejects reused-revision changed source',()=>{let s=fixture(),spec={mode:'literal',text:'uncoded'},row=literalCorpusSearch(s,spec)[0];const saved=applyOperation(s,{type:'query.results.materialize',data:{name:'Literal evidence',spec,resultIds:[row.queryResultId]}},'researcher');assert.deepEqual(saved.codings[0].querySources,[]);assert.equal(saved.codings[0].text,'uncoded');s.documents[0].text=s.documents[0].text.replace('uncoded','UNCODED');assert.throws(()=>applyOperation(s,{type:'query.results.materialize',data:{name:'Stale',spec,resultIds:[row.queryResultId]}},'researcher'),/changed/);assert.notEqual(row.queryResultId,resultIdentity({...row,text:'UNCODED'}));});
test('Random NOT fragments match a boolean coverage oracle without negative or overlapping ranges',()=>{let seed=43;const rand=n=>{seed=(seed*1664525+1013904223)>>>0;return seed%n;};for(let run=0;run<100;run++){const s=fixture();for(let i=0;i<8;i++){const a=rand(15),b=a+1+rand(15-a);add(s,'c'+i,i<4?'a':'b',a,b);}const result=intervalQuery(s,{codeA:'a',codeB:'b',operator:'not'});for(let i=0;i<15;i++){const original=s.codings.filter(c=>c.start<=i&&c.end>i);assert.equal(result.some(r=>r.start<=i&&r.end>i),original.some(c=>c.codeId==='a')&&!original.some(c=>c.codeId==='b'));}for(let i=1;i<result.length;i++)assert.ok(result[i-1].end<result[i].start);}});
