import test from 'node:test';import assert from 'node:assert/strict';
import {applyOperation,emptyState,slice} from '../src/domain.mjs';
import {scopedCodings,analysisMatrix,measure,relates,words,reportRows} from '../src/analysis-domain.mjs';
import {xlsx,graphML,htmlReport,safeCSV,odtReport} from '../src/report-export.mjs';
import {parseCSV,casesFromTable} from '../src/tabular-import.mjs';import {unzipSync,strFromU8} from 'fflate';
function fixture(){const s=emptyState('Test');s.documents=[{id:'d',name:'Interview',text:'😀 one two three four five',revision:1,attributes:{Score:0},turns:[{start:0,end:24,timeStart:0,timeEnd:6}],alignment:{status:'unbound'}},{id:'e',name:'Other',text:'one two',revision:1}];s.codes=[{id:'p',name:'Parent'},{id:'a',name:'A',parentId:'p'},{id:'b',name:'B',parentId:'p'}];s.codings=[{id:'1',documentId:'d',codeId:'a',start:2,end:9,text:slice(s.documents[0].text,2,9),coder:'alice',status:'accepted'},{id:'2',documentId:'d',codeId:'b',start:2,end:9,text:slice(s.documents[0].text,2,9),coder:'bob',status:'coded'},{id:'3',documentId:'d',codeId:'a',start:6,end:15,text:slice(s.documents[0].text,6,15),coder:'alice',status:'coded'},{id:'4',documentId:'e',codeId:'a',start:0,end:7,text:'one two',coder:'alice',status:'provisional'}];return s;}
test('Analysis distinguishes application count, exact excerpts and union coverage; parent totals do not sum overlapping children',()=>{const s=fixture(),rows=scopedCodings(s,{sourceId:'d'});assert.equal(rows.length,3);assert.equal(measure(s,rows,'excerpts'),2);assert.equal(measure(s,rows,'characters'),13);const p=analysisMatrix(s,rows).rows.find(r=>r.id==='p');assert.equal(p.total,3);assert.equal(analysisMatrix(s,rows,{metric:'characters'}).rows.find(r=>r.id==='p').total,13);assert.equal(scopedCodings(s,{attribute:'Score',attributeValue:'0'}).length,3);s.documents[0].reviewFlags=[{start:2,end:4}];assert.equal(scopedCodings(s).length,2);assert.equal(reportRows(s,s.codings).length,3);s.documents[1].sourceRole='reference';assert.equal(scopedCodings(s).length,1);});
test('Recording coverage unions only matching recording ranges; text timing bounds retain genuine zero',()=>{const s=fixture();s.documents[0].mediaKey='r';const media=[{kind:'media',documentId:'d',recordingKey:'r',timeStart:0,timeEnd:4},{kind:'media',documentId:'d',recordingKey:'r',timeStart:2,timeEnd:7},{kind:'media',documentId:'d',recordingKey:'wrong',timeStart:0,timeEnd:10}];assert.equal(measure(s,media,'seconds'),7);assert.equal(measure(s,s.codings,'seconds'),0);const r=reportRows(s,[s.codings[0]])[1];assert.equal(r[13],0);assert.equal(r[14],6);assert.match(r[15],/no interpolation/);});
test('Range relationships retain direction only for containment and reject incompatible recording identities',()=>{const a={id:'a',documentId:'d',start:2,end:10},b={id:'b',documentId:'d',start:10,end:15};assert.equal(relates(a,b,'touch'),true);assert.equal(relates(a,b,'overlap'),false);assert.equal(relates(a,b,'near',0),true);assert.equal(relates(a,{...b,start:3,end:5},'contains'),true);assert.equal(relates({...a,kind:'media',recordingKey:'a',timeStart:0,timeEnd:5},{...b,kind:'media',recordingKey:'b',timeStart:1,timeEnd:3},'overlap'),false);const relation=[{a:{id:'a',name:'A'},b:{id:'b',name:'B'},count:2}];assert.match(graphML(relation),/edgedefault="undirected"/);assert.match(graphML(relation,true),/edgedefault="directed"/);});
test('Unicode concordance and adjacent phrase boundaries remain exact without ASCII word assumptions',()=>{const s=fixture(),doc={id:'f',text:'😀 éclair café éclair café'};const v=words(s,[doc],{language:'none',n:2});const phrase=v.find(v=>v.term==='éclair café');assert.equal(phrase.count,2);assert.equal(phrase.hits[0].start,2);for(const h of phrase.hits)assert.equal(slice(doc.text,h.start,h.end),h.text);});
test('Passage case membership and linked anchors shift with edits and become uncertain across corrections',()=>{let s=fixture();s=applyOperation(s,{type:'case.save',data:{name:'Passage case',documentIds:[]}},'alice');const id=s.cases[0].id,a=s.codings[0];s=applyOperation(s,{type:'case.passage',data:{caseId:id,documentId:'d',start:a.start,end:a.end,text:a.text}},'alice');assert.equal(scopedCodings(s,{caseId:id}).length,3);s=applyOperation(s,{type:'passage.pin',data:{...a,label:'A'}},'alice');s=applyOperation(s,{type:'source.revise',data:{id:'d',text:'Prefix '+s.documents[0].text}},'owner');assert.equal(s.cases[0].passages[0].start,a.start+7);assert.equal(s.cases[0].passages[0].sourceRevision,2);s=applyOperation(s,{type:'source.revise',data:{id:'d',text:s.documents[0].text.replace('one','changed')}},'owner');assert.equal(s.cases[0].passages[0].anchorStatus,'needs_review');assert.equal(s.passagePins[0].anchorStatus,'needs_review');assert.equal(scopedCodings(s,{caseId:id}).length,0);});
test('Code merge remaps linked records, partial memo edit retains linkage, case saves reject absent sources',()=>{let s=fixture();s.memos=[{id:'m',title:'M',content:'Before',author:'alice',codeId:'a',documentId:'d',start:2,end:9}];s.savedQueries=[{id:'q',spec:{codeA:'a',codeB:'b'}}];s.reviewTasks=[{suggestedCodeIds:['a','b']}];s=applyOperation(s,{type:'code.merge',data:{from:'a',into:'b'}},'owner');assert.equal(s.memos[0].codeId,'b');assert.equal(s.savedQueries[0].spec.codeA,'b');assert.deepEqual(s.reviewTasks[0].suggestedCodeIds,['b']);s=applyOperation(s,{type:'memo.save',data:{id:'m',title:'Changed',content:'After'}},'alice');assert.equal(s.memos[0].documentId,'d');assert.equal(s.memos[0].versions[0].content,'Before');assert.throws(()=>applyOperation(s,{type:'case.save',data:{name:'Bad',documentIds:['absent']}},'alice'),/missing source/);});
test('Typed attributes coerce zero, reject invalid dates atomically, and category cycles cannot be saved',()=>{let s=fixture();s=applyOperation(s,{type:'attribute.type',data:{name:'Score',scope:'file',valueType:'number'}},'owner');s=applyOperation(s,{type:'source.attributes',data:{id:'d',attributes:{Score:'0'}}},'alice');assert.equal(s.documents[0].attributes.Score,0);assert.throws(()=>applyOperation(s,{type:'source.attributes',data:{id:'d',attributes:{Score:'NaN'}}},'alice'),/numeric/);s=applyOperation(s,{type:'category.save',data:{name:'First'}},'owner');const id=s.categories[0].id;assert.throws(()=>applyOperation(s,{type:'category.save',data:{id,name:'Cycle',parentId:id}},'owner'),/hierarchy/);s=applyOperation(s,{type:'code.update',data:{id:'a',categoryId:id}},'alice');assert.equal(s.codes.find(c=>c.id==='a').categoryId,id);});
test('Frozen query code uses exactly selected text results and attribution without copying reviewer acceptance',()=>{const s=fixture(),next=applyOperation(s,{type:'query.materialize',data:{name:'Scoped result',spec:{},codingIds:['1']}},'alice');const id=next.codes.at(-1).id,rows=next.codings.filter(c=>c.codeId===id);assert.equal(rows.length,1);assert.equal(rows[0].status,'coded');assert.equal(rows[0].coder,'alice');assert.deepEqual(rows[0].querySources,['1']);assert.equal(s.codes.length,3);});
test('Spreadsheet and document exports carry literal text; CSV neutralizes formulas; case table preview resolves sources exactly',()=>{const rows=[['Name','Value'],['=SUM(1,2)',0],['<script>bad</script>',-2]];const z=unzipSync(xlsx(rows)),sheet=strFromU8(z['xl/worksheets/sheet1.xml']);assert.ok(!sheet.includes('<f>'));assert.match(sheet,/&lt;script&gt;/);assert.match(sheet,/<v>0<\/v>/);assert.match(safeCSV(rows),/"'=SUM/);assert.match(safeCSV(rows),/"-2"/);assert.ok(!htmlReport('Report',rows,'scope').includes('<script>'));assert.equal(strFromU8(unzipSync(odtReport('R',rows,'Scope')).mimetype),'application/vnd.oasis.opendocument.text');const table=parseCSV('name,sources,memo\r\n"A, B",Interview,"two\nlines"');assert.equal(casesFromTable(table,fixture())[0].documentIds[0],'d');assert.equal(table[1][2],'two\nlines');});

test('Imported and saved passage links reject invented current anchors and blank numeric attributes stay missing',()=>{const s=fixture();assert.throws(()=>applyOperation(s,{type:'case.save',data:{name:'Invented',documentIds:[],passages:[{documentId:'missing',start:0,end:3,text:'bad',sourceRevision:1}]}},'alice'),/passage link anchor/);assert.throws(()=>applyOperation(s,{type:'case.batch',data:{rows:[{name:'Invented',passages:[{documentId:'d',start:0,end:3,text:'bad',sourceRevision:1}]}]}},'alice'),/saved source revision/);const typed=applyOperation(s,{type:'attribute.type',data:{scope:'file',name:'Score',valueType:'number'}},'owner');assert.equal(applyOperation(typed,{type:'source.attributes',data:{id:'d',attributes:{Score:'   '}}},'alice').documents[0].attributes.Score,null);assert.throws(()=>applyOperation(typed,{type:'source.attributes',data:{id:'d',attributes:{Score:[]}}},'alice'),/numeric/);});

test('Hierarchy area partitions add up to applications and geometry equality ignores field order',async()=>{const {hierarchyLayout}=await import('../src/hierarchy-layout.mjs');const s=fixture(),layout=hierarchyLayout(s,s.codings);assert.equal(layout.total,4);assert.equal(layout.tiles.reduce((n,t)=>n+t.box.width*t.box.height,0),500000);assert.equal(layout.segments.find(n=>n.code.id==='p').weight,4);const a={id:'x',documentId:'d',kind:'image',region:{x:0,y:0,width:.5,height:.5}},b={id:'y',documentId:'d',kind:'image',region:{height:.5,width:.5,y:0,x:0}};assert.equal(relates(a,b,'exact'),true);assert.equal(measure(s,[a,b],'excerpts'),1);const doc={id:'x',text:'visible restricted words visible',reviewFlags:[{start:8,end:24}]};assert.ok(!words(s,[doc],{language:'none'}).some(w=>w.term==='restricted'));});

test('Typed numeric filtering supports thresholds and case-attribute columns include passage membership',()=>{const s=fixture();assert.equal(scopedCodings(s,{attribute:'Score',attributeValue:'0',attributeOperator:'gte'}).length,3);assert.equal(scopedCodings(s,{attribute:'Score',attributeValue:'0',attributeOperator:'gt'}).length,0);s.cases=[{id:'c',name:'Passage case',documentIds:[],attributes:{Group:'A'},passages:[{documentId:'d',start:2,end:9,text:slice(s.documents[0].text,2,9),sourceRevision:1}]}];const m=analysisMatrix(s,s.codings,{group:'attribute:Group',rowMode:'all'});assert.equal(m.columns.length,1);assert.equal(m.rows[0].cells[0].value,3);});

test('REFI variables distinguish file/case scope and preserve zero, false, dates and non-scientific decimal values',async()=>{const {exportQDPX}=await import('../src/refi.mjs');const s=fixture();s.documents[0].attributes={Score:0,Consent:false,Date:'2026-01-02',Tiny:1e-7};s.attributeTypes=[{scope:'file',name:'Score',valueType:'number'},{scope:'file',name:'Consent',valueType:'boolean'},{scope:'file',name:'Date',valueType:'date'},{scope:'file',name:'Tiny',valueType:'number'},{scope:'case',name:'Score',valueType:'number'}];s.cases=[{id:'case',name:'Case',documentIds:['d'],attributes:{Score:2.5}}];const z=unzipSync(exportQDPX(s)),xml=strFromU8(z['project.qde']);assert.match(xml,/<FloatValue>0<\/FloatValue>/);assert.match(xml,/<FloatValue>0.0000001<\/FloatValue>/);assert.match(xml,/<FloatValue>2.5<\/FloatValue>/);assert.match(xml,/<BooleanValue>false<\/BooleanValue>/);assert.match(xml,/<DateValue>2026-01-02<\/DateValue>/);assert.equal((xml.match(/name="Score" typeOfVariable="Float"/g)||[]).length,2);assert.ok(z['research-weave-exchange-scope.json']);});
