import test from 'node:test';import assert from 'node:assert/strict';import initSqlJs from 'sql.js';
import {normalizeRQDA,readRQDA} from '../src/rqda-import.mjs';import {nativeSchema,nativeProjectChoices,readNativeProject} from '../src/native-project-import.mjs';
const SQL=await initSqlJs();
function fixture(){return {project:[{databaseversion:'0.2.2',memo:'Research context',imageDir:'SECRET_PATH'}],source:[{id:1,name:'Interview',file:'A😀éβB',memo:'Source memo',owner:'Researcher',status:1},{id:2,name:'Deleted',file:'secret deleted text',status:0}],freecode:[{id:1,name:'Theme',memo:'Definition',status:1,color:'blue'}],coding:[{__rowid:1,cid:1,fid:1,selfirst:1,selend:3,seltext:'😀é',owner:'Original researcher',memo:'Interpretation',status:1}],cases:[{id:1,name:'Case',memo:'Case context',status:1}],caselinkage:[{caseid:1,fid:1,selfirst:1,selend:3,status:1,owner:'Original researcher'}],codecat:[{catid:1,name:'Category',memo:'Category definition',status:1}],treecode:[{cid:1,catid:1,status:1}],journal:[{name:'Decision log',journal:'Researcher reflection',owner:'Original researcher',status:1}]};}
test('documented RQDA 0.2.2 character offsets preserve Unicode coding, memo and historical owner',()=>{const s=normalizeRQDA(fixture());assert.equal(s.codings[0].start,1);assert.equal(s.codings[0].end,3);assert.equal(s.codings[0].text,'😀é');assert.equal(s.codings[0].status,'coded');assert.equal(s.codings[0].coder,'Original researcher');assert.equal(s.documents.length,1);assert.equal(s.documents[0].memo,'Source memo');assert.equal(s.codes[0].description,'Definition');assert.equal(s.memos[0].citations[0].text,'😀é');assert.equal(s.journals[0].text,'Researcher reflection');assert.equal(s.documents[0].excludeAI,true);assert.deepEqual(s.documents[0].turns,[]);assert.doesNotMatch(JSON.stringify(s),/SECRET_PATH|secret deleted text/);});
test('case passage links are precise; only a complete source span becomes whole-source membership',()=>{const t=fixture();let s=normalizeRQDA(t);assert.deepEqual(s.cases[0].documentIds,[]);assert.equal(s.cases[0].passages[0].text,'😀é');assert.equal(s.cases[0].memo,'Case context');t.caselinkage[0].selfirst=0;t.caselinkage[0].selend=5;s=normalizeRQDA(t);assert.equal(s.cases[0].documentIds[0],s.documents[0].id);assert.deepEqual(s.cases[0].passages,[]);});
test('missing case bounds stay inert and multi-category membership is preserved without duplication',()=>{const t=fixture();delete t.caselinkage[0].selfirst;delete t.caselinkage[0].selend;t.codecat.push({catid:2,name:'Second category',status:1});t.treecode.push({cid:1,catid:2,status:1});const s=normalizeRQDA(t);assert.deepEqual(s.cases[0].documentIds,[]);assert.deepEqual(s.cases[0].passages,[]);assert.equal(s.nativeImport.records.caseLinks[0].active,false);assert.equal(s.codes.length,1);assert.equal(s.codes[0].categoryId,undefined);assert.equal(s.nativeImport.records.categoryLinks.length,2);assert.ok(s.nativeImport.losses.some(l=>l.kind==='category-membership'));});
test('unknown versions, byte-like bounds and mismatched selected text are quarantined without reanchoring',()=>{const t=fixture();t.project[0].databaseversion='future-9';let s=normalizeRQDA(t);assert.equal(s.codings[0].status,'needs_review');assert.equal(s.codings[0].text,'😀é');assert.equal(s.memos[0].anchorStatus,'needs_review');assert.equal(s.cases[0].passages.length,0);t.project[0].databaseversion='0.2.2';t.coding[0].selfirst=2;t.coding[0].selend=7;s=normalizeRQDA(t);assert.equal(s.codings[0].status,'needs_review');assert.equal(s.codings[0].start,2);assert.equal(s.codings[0].text,'😀é');});
test('missing seltext derives from source only under the documented offset contract',()=>{const t=fixture();delete t.coding[0].seltext;let s=normalizeRQDA(t);assert.equal(s.codings[0].text,'😀é');assert.equal(s.codings[0].status,'coded');assert.match(s.codings[0].importProvenance.quoteBasis,/documented/);t.project[0].databaseversion='unknown';s=normalizeRQDA(t);assert.equal(s.codings[0].text,'');assert.equal(s.codings[0].status,'needs_review');});
test('secondary coding preserves explicit owner while multiple project records are rejected',()=>{const t=fixture();t.coding2=[{...t.coding[0],owner:'Second original researcher'}];const s=normalizeRQDA(t);assert.equal(s.codings.length,2);assert.notEqual(s.codings[0].id,s.codings[1].id);assert.equal(s.codings[1].coder,'Second original researcher');t.project.push({databaseversion:'0.2.2'});assert.throws(()=>normalizeRQDA(t),/exactly one/);});
test('schema reader imports allowlisted RQDA records only, without SQL or auth settings activation',()=>{const db=new SQL.Database();db.run(`CREATE TABLE project(databaseversion TEXT,memo TEXT,imageDir TEXT);CREATE TABLE source(id INTEGER,name TEXT,file TEXT,memo TEXT,status INTEGER);CREATE TABLE freecode(id INTEGER,name TEXT,memo TEXT,status INTEGER);CREATE TABLE coding(cid INTEGER,fid INTEGER,selfirst REAL,selend REAL,seltext TEXT,status INTEGER,owner TEXT);CREATE TABLE stored_sql(query TEXT);CREATE TABLE settings(token TEXT);INSERT INTO project VALUES('0.2.2','Research','SECRET_PATH');INSERT INTO source VALUES(1,'Interview','A😀éB','Context',1);INSERT INTO freecode VALUES(1,'Theme','Definition',1);INSERT INTO coding VALUES(1,1,1,3,'😀é',1,'Researcher');INSERT INTO stored_sql VALUES('DROP TABLE source');INSERT INTO settings VALUES('SECRET_TOKEN');`);const before=db.export(),statements=[],exec=db.exec.bind(db);db.exec=sql=>{statements.push(sql);return exec(sql);};assert.equal(nativeSchema(db).format,'rqda');assert.equal(nativeProjectChoices(db).projects[0].id,'1');const s=readNativeProject(db);assert.equal(s.codings[0].status,'coded');assert.equal(s.nativeImport.application,'rqda');assert.doesNotMatch(statements.join('\n'),/SELECT \*|FROM "settings"|FROM "stored_sql"|imageDir/);assert.doesNotMatch(JSON.stringify(s),/SECRET_PATH|SECRET_TOKEN|DROP TABLE/);assert.deepEqual(db.export(),before);db.close();});
test('malformed optional tables and fractional offsets fail safely',()=>{const t=fixture();t.coding[0].selfirst=1.5;const s=normalizeRQDA(t);assert.equal(s.codings[0].status,'needs_review');const db=new SQL.Database();db.run(`CREATE TABLE project(databaseversion TEXT);CREATE TABLE source(id INTEGER,name TEXT,file TEXT,status INTEGER);CREATE TABLE freecode(id INTEGER,name TEXT,status INTEGER);CREATE TABLE coding(cid INTEGER,fid INTEGER,selfirst REAL,selend REAL,status INTEGER);CREATE TABLE cases(id INTEGER,name TEXT);INSERT INTO project VALUES('0.2.2');`);assert.throws(()=>readRQDA(db),/Invalid RQDA cases/);db.close();});

test('documented SQLite source-slice expression independently confirms half-open Unicode bounds',()=>{const db=new SQL.Database();db.run("CREATE TABLE source(id INTEGER,file TEXT);CREATE TABLE coding(fid INTEGER,selfirst REAL,selend REAL,seltext TEXT);INSERT INTO source VALUES(1,'A😀éβB');INSERT INTO coding VALUES(1,1,3,'😀é');");const r=db.exec('SELECT substr(source.file,coding.selfirst+1,coding.selend-coding.selfirst),seltext FROM coding JOIN source ON coding.fid=source.id')[0].values[0];assert.equal(r[0],'😀é');assert.equal(r[0],r[1]);db.close();});
