import test from 'node:test';
import assert from 'node:assert/strict';
import initSqlJs from 'sql.js';
import {sqliteTextEncoding,sqliteTextSelection,decodeSQLiteTextRows} from '../src/sqlite-text.mjs';
import {readRQDA} from '../src/rqda-import.mjs';
import {readRequal} from '../src/requal-import.mjs';
const SQL=await initSqlJs();
function textBytes(text,encoding='UTF-8'){if(encoding==='UTF-8')return new TextEncoder().encode(text);const bytes=new Uint8Array(text.length*2),view=new DataView(bytes.buffer);for(let i=0;i<text.length;i++)view.setUint16(i*2,text.charCodeAt(i),encoding==='UTF-16le');return bytes;}
function rows(db,sql){const result=db.exec(sql)[0];return result?result.values.map(values=>Object.fromEntries(result.columns.map((name,i)=>[name,values[i]]))):[];}
test('SQLite UTF8/UTF16 text retains leading FEFF, CRLF, emoji, combining marks and embedded NUL',()=>{const original='\uFEFFé😀 e\u0301\r\nleft\0right';for(const encoding of ['UTF-8','UTF-16le','UTF-16be']){const db=new SQL.Database();db.run('PRAGMA encoding="'+encoding+'"');db.run('CREATE TABLE source(id INTEGER,text TEXT,missing_value TEXT,number REAL,bytes BLOB)');db.run('INSERT INTO source VALUES(?,? || char(0) || ?,?,?,?)',[1,...original.split('\0'),null,0.5,Uint8Array.of(255,0,254)]);const imported=decodeSQLiteTextRows(rows(db,'SELECT '+sqliteTextSelection(['id','text','missing_value','number','bytes'])+' FROM source'),null,sqliteTextEncoding(db))[0];assert.equal(imported.text,original);assert.equal(imported.id,1);assert.equal(imported.missing_value,null);assert.equal(imported.number,0.5);assert.deepEqual(imported.bytes,Uint8Array.of(255,0,254));assert.equal(Object.keys(imported).some(name=>name.startsWith('__rw_sqlite_type_')),false);db.close();}});
test('invalid stored TEXT bytes are rejected while genuine BLOBs stay binary',()=>{const db=new SQL.Database();db.run("CREATE TABLE source(text TEXT);INSERT INTO source VALUES(CAST(x'FF' AS TEXT));");assert.throws(()=>decodeSQLiteTextRows(rows(db,'SELECT '+sqliteTextSelection(['text'])+' FROM source'),null,sqliteTextEncoding(db)),/invalid text bytes/);db.close();});
test('identifier escaping prevents SQL syntax injection through schema-derived column names',()=>{const db=new SQL.Database(),name='odd"name';db.run('CREATE TABLE source("odd""name" TEXT)');db.run('INSERT INTO source VALUES(?)',['\uFEFFsafe']);const record=decodeSQLiteTextRows(rows(db,'SELECT '+sqliteTextSelection([name])+' FROM source'),null,sqliteTextEncoding(db))[0];assert.equal(record[name],'\uFEFFsafe');assert.throws(()=>sqliteTextSelection(['__rw_sqlite_type_bad']),/identifier/);db.close();});
test('RQDA native source with stored FEFF/NUL keeps exact text and formerly shifted coding becomes active',()=>{const db=new SQL.Database(),text='\uFEFFA😀\0B\r\n';db.run('CREATE TABLE project(databaseversion TEXT);CREATE TABLE source(id INTEGER,name TEXT,file TEXT,status INTEGER);CREATE TABLE freecode(id INTEGER,name TEXT,status INTEGER);CREATE TABLE coding(cid INTEGER,fid INTEGER,seltext TEXT,selfirst INTEGER,selend INTEGER,status INTEGER);INSERT INTO project VALUES("0.2.2");INSERT INTO freecode VALUES(1,"Code",1);');db.run('INSERT INTO source VALUES(1,?,? || char(0) || ?,1)',['Source',...text.split('\0')]);db.run('INSERT INTO coding VALUES(1,1,?,1,3,1)',['A😀']);const s=readRQDA(db);assert.equal(s.documents[0].text,text);assert.equal(s.codings[0].status,'coded');assert.equal(s.codings[0].start,1);assert.equal(s.codings[0].end,3);db.close();});
test('Requal native source and exact quotation preserve stored FEFF/NUL independently',()=>{const db=new SQL.Database(),text='\uFEFFA😀\0B\r\n';db.run('CREATE TABLE projects(project_id INTEGER,project_name TEXT);CREATE TABLE requal_version(project_id INTEGER,version TEXT);CREATE TABLE documents(project_id INTEGER,doc_id INTEGER,doc_name TEXT,doc_text TEXT);CREATE TABLE codes(project_id INTEGER,code_id INTEGER,code_name TEXT);CREATE TABLE segments(project_id INTEGER,segment_id INTEGER,doc_id INTEGER,code_id INTEGER,segment_start INTEGER,segment_end INTEGER,segment_text TEXT);INSERT INTO projects VALUES(1,"Project");INSERT INTO requal_version VALUES(1,"1.0.0");INSERT INTO codes VALUES(1,1,"Code");');db.run('INSERT INTO documents VALUES(1,1,?,? || char(0) || ?)',['Source',...text.split('\0')]);db.run('INSERT INTO segments VALUES(1,1,1,1,1,4,? || char(0))',['\uFEFFA😀']);const s=readRequal(db);assert.equal(s.documents[0].text,text);assert.equal(s.codings[0].text,'\uFEFFA😀\0');assert.equal(s.codings[0].status,'coded');db.close();});

test('generic table projection preserves runtime types, exact text, quoted identifiers and record limits',async()=>{const {readSQLiteTable}=await import('../src/sqlite-text.mjs');const db=new SQL.Database();db.run('CREATE TABLE sample(id INTEGER,text TEXT,raw BLOB,missing TEXT)');db.run('INSERT INTO sample VALUES(1,? || char(0) || ?,?,NULL)',['\uFEFFA😀','tail',Uint8Array.of(255,0)]);const row=readSQLiteTable(db,'sample',['id','text','raw','missing'])[0];assert.equal(row.text,'\uFEFFA😀\0tail');assert.equal(row.id,1);assert.deepEqual(row.raw,Uint8Array.of(255,0));assert.equal(row.missing,null);db.run('INSERT INTO sample(id,text) VALUES(2,"second")');assert.throws(()=>readSQLiteTable(db,'sample',['id'],{limit:1}),/record limit/);db.close();});
