import test from 'node:test';import assert from 'node:assert/strict';import {Miniflare} from 'miniflare';import {readFile,readdir} from 'node:fs/promises';
import {emptyState} from '../src/domain.mjs';
test('Server isolates blind decisions on every state/history/AI/recovery path and enforces owner role presets',async()=>{
 const sent=[];const mf=new Miniflare({modules:true,scriptPath:'dist/server/index.js',compatibilityDate:'2025-10-01',compatibilityFlags:['nodejs_compat'],bindings:{LOCAL_DEV:'true',AI_BASE_URL:'https://fixture.test'},d1Databases:['DB'],r2Buckets:['BUCKET'],outboundService:async req=>{const b=await req.json();if(new URL(req.url).pathname==='/v1/embeddings')return Response.json({data:b.input.map((_,index)=>({index,embedding:[1,1]}))});const data=JSON.parse(b.messages[1].content);sent.push(data);return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify({title:'Synthetic review',text:'Own evidence only',citations:data.evidence?.map(e=>e.id)||[]})}}]});}});
 try{const db=await mf.getD1Database('DB');for(const name of (await readdir('drizzle')).filter(n=>n.endsWith('.sql')).sort())for(const sql of (await readFile('drizzle/'+name,'utf8')).split('--> statement-breakpoint'))if(sql.trim())await db.prepare(sql).run();
 const call=async(path,actor='owner',method='GET',body)=>{const r=await mf.dispatchFetch('https://app.test/api'+path,{method,headers:{'Content-Type':'application/json','x-local-user':actor},body:body&&!['GET','HEAD'].includes(method)?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};};
 const state=emptyState('Synthetic blind team');state.documents=[{id:'d',name:'Interview',text:'Alpha beta',revision:1,sourceRole:'interview',turns:[{start:0,end:10,timeStart:0,timeEnd:1.25,speaker:'SPEAKER_00'}]}];state.codes=[{id:'c',name:'Theme'}];state.codings=[{id:'a',documentId:'d',codeId:'c',start:0,end:5,text:'Alpha',coder:'coder-a',sourceRevision:1,status:'coded'},{id:'b',documentId:'d',codeId:'c',start:6,end:10,text:'beta',coder:'coder-b',sourceRevision:1,status:'coded',memo:'Hidden decision'}];state.memos=[{id:'ma',title:'Hidden decision',content:'Hidden decision',author:'coder-b'}];
 const {data:{id}}=await call('/projects','owner','POST',{state}),p='/projects/'+id;
 for(const [actor,role] of [['coder-a','coder'],['coder-b','coder'],['reviewer','reviewer']])assert.equal((await call(p+'/members','owner','POST',{email:actor+'@local.test',role})).status,200);
 let policy={blindCoding:true,roles:{coder:{ai:true}}};assert.equal((await call(p+'/operate','coder-a','POST',{revision:0,operation:{type:'permissions.update',data:policy},role:'owner',actor:'owner'})).status,403);
 assert.equal((await call(p+'/operate','owner','POST',{revision:0,operation:{type:'permissions.update',data:policy}})).status,200);
 const a=(await call(p,'coder-a')).data;assert.deepEqual(a.state.codings.map(c=>c.id),['a']);assert.ok(!JSON.stringify(a).includes('Hidden decision'));assert.equal(a.access.blind,true);assert.deepEqual((await call(p,'reviewer')).data.state.codings.map(c=>c.id),['a','b']);
 const summary=await call(p+'/ai-review','coder-a','POST',{mode:'summary'});assert.equal(summary.status,200);assert.deepEqual(sent[0].evidence.map(e=>e.id),['a']);assert.deepEqual(summary.data.citations.map(c=>c.id),['a']);assert.equal((await call(p+'/semantic','coder-a','POST',{query:'Alpha'})).status,200);
 const changed=await call(p+'/operate','coder-a','POST',{revision:1,operation:{type:'coding.create',data:{documentId:'d',start:0,end:10,codeIds:['c'],coder:'coder-b'}}});assert.equal(changed.status,200);assert.equal(changed.data.state.codings.length,2);assert.ok(changed.data.state.codings.every(c=>c.coder==='coder-a'));assert.equal((await call(p,'owner')).data.state.codings.length,3);assert.equal((await call(p,'owner')).data.state.codings.find(c=>c.id==='b').memo,'Hidden decision');
 for(const operation of [{type:'coding.delete',data:{id:'b'}},{type:'memo.save',data:{id:'ma',title:'Taken'}},{type:'code.create',data:{name:'Global influence'}},{type:'settings.save',data:{teamAccess:{blindCoding:false}}}])assert.equal((await call(p+'/operate','coder-a','POST',{revision:2,operation})).status,403);
 assert.equal((await call(p+'/operate','coder-a','POST',{revision:1,operation:{type:'reading.mark',data:{documentId:'d',start:0,end:5,status:'read'}}})).status,409);
 const historyDb=await mf.getD1Database('DB');await historyDb.prepare('INSERT INTO events (id,project_id,actor,action,detail,created_at) VALUES (?,?,?,?,?,?)').bind('old-own-encoded',id,'coder-a@local.test','query.results.materialize',JSON.stringify({operation:{data:{resultIds:['OTHER-CODER-ENCODED-PROVENANCE']}}}),new Date().toISOString()).run();
 for(const historyPath of ['/events','/events?paginated=true']){const response=await call(p+historyPath,'coder-a');assert.ok(!JSON.stringify(response.data).includes('OTHER-CODER-ENCODED-PROVENANCE'));}assert.ok(JSON.stringify((await call(p+'/events','owner')).data).includes('OTHER-CODER-ENCODED-PROVENANCE'));
 const history=await call(p+'/events','coder-a');assert.ok(history.data.every(e=>e.actor==='coder-a@local.test'));const paged=await call(p+'/events?paginated=true&actor=coder-b','coder-a');assert.equal(paged.data.total,0);
 const points=(await call(p+'/backups','owner')).data;assert.equal((await call(p+'/backups','coder-a')).status,403);assert.equal((await call(p+'/backups/'+points[0].id,'coder-a','POST',{download:true})).status,403);assert.equal((await call(p+'/jobs','coder-a')).status,403);assert.equal((await call(p+'/uploads','coder-a','POST',{type:'audio/wav',size:6,name:'fixture.wav'})).status,403);
 const textHistory=await call(p+'/events?paginated=true&text=OTHER-CODER-ENCODED-PROVENANCE','owner');assert.equal(textHistory.data.total,1);assert.equal((await call(p+'/events?paginated=true&text=OTHER-CODER-ENCODED-PROVENANCE','coder-a')).status,403);
 assert.equal((await call(p+'/private-notes','coder-a','POST',{title:'Own reflection',content:'Private note'})).status,200);assert.deepEqual((await call(p+'/private-notes','coder-b')).data,[]);
 policy={blindCoding:true,roles:{coder:{coding:false,memos:false,history:false,ai:false}}};assert.equal((await call(p+'/operate','owner','POST',{revision:2,operation:{type:'permissions.update',data:policy}})).status,200);
 for(const endpoint of ['events','semantic','ai-review'])assert.equal((await call(p+'/'+endpoint,'coder-a',endpoint==='events'?'GET':'POST',{query:'Alpha',mode:'summary'})).status,403);
 assert.equal((await call(p+'/operate','coder-a','POST',{revision:3,operation:{type:'coding.create',data:{documentId:'d',start:0,end:5,codeIds:['c']}}})).status,403);assert.equal((await call(p+'/private-notes','coder-a','POST',{title:'No',content:'No'})).status,403);
 // A pre-policy recovery point cannot undo the current access policy.
 const initial=points.find(x=>x.revision===0),restored=await call(p+'/backups/'+initial.id,'owner','POST',{restore:true,revision:3});assert.equal(restored.status,200);assert.equal(restored.data.state.settings.teamAccess.roles.coder.ai,false);assert.equal((await call(p,'coder-a')).data.state.codings.length,1);
 }finally{await mf.dispose();}
});
