import test from 'node:test';import assert from 'node:assert/strict';
import {emptyState,applyOperation} from '../src/domain.mjs';
import {normalizeTeamPolicy,teamAccess,authorizeOperation,visibleProjectState} from '../src/team-policy.mjs';
import {evidenceSet} from '../server/research-ai.mjs';
import {exportQDPX} from '../src/refi.mjs';import {unzipSync,strFromU8} from 'fflate';
function fixture(){const s=emptyState('Synthetic independent coding');s.documents=[{id:'d',name:'Interview',text:'Alpha beta',revision:1,turns:[{start:0,end:10,timeStart:0,timeEnd:1.25,speaker:'SPEAKER_00'}],alignment:{recordingKey:null,status:'unbound',units:'seconds'}}];s.codes=[{id:'c',name:'Theme',querySnapshot:{selectedApplicationIds:['other']},definitionHistory:[{description:'Hidden decision'}]}];s.codings=[{id:'own',documentId:'d',codeId:'c',start:0,end:5,text:'Alpha',coder:'a',status:'coded',sourceRevision:1},{id:'other',documentId:'d',codeId:'c',start:6,end:10,text:'beta',coder:'b',status:'coded',sourceRevision:1,memo:'Hidden decision'}];s.memos=[{id:'ma',author:'a',title:'Own',content:'Own note'},{id:'mb',author:'b',title:'Hidden decision',content:'Hidden decision'}];s.documents[0].legacyAnalysis={memo:'Hidden decision'};s.categories=[{id:'cat',name:'Shared category',memo:'Hidden decision',legacy:{codingIds:['other']}}];s.cases=[{id:'case',name:'Shared case',documentIds:['d'],attributes:{},legacy:{codingIds:['other']}}];s.legacy={codedText:[{memo:'Hidden decision'}]};s.demo={themes:[{rationale:'Hidden decision'}]};s.consensus=[{reviewer:'b',reason:'Hidden decision'}];return s;}
test('Blind projection hides imported/derived decisions, retains exact source and zero/fractional times, and filters AI evidence',async()=>{const s=fixture();s.settings.teamAccess={blindCoding:true};const access=teamAccess(s,'coder',{id:'a'}),v=visibleProjectState(s,access);assert.equal(v.codings.length,1);assert.equal(v.memos.length,1);assert.ok(!JSON.stringify(v).includes('Hidden decision'));assert.deepEqual(v.documents,s.documents.map(({legacyAnalysis,...d})=>({...d,versions:[]})));assert.equal(v.documents[0].turns[0].timeStart,0);assert.equal(v.documents[0].turns[0].timeEnd,1.25);assert.equal(evidenceSet(v).evidence[0].id,'own');assert.equal(evidenceSet(v).total,1);assert.deepEqual(visibleProjectState(s,teamAccess(s,'reviewer',{id:'r'})),s);const archive=unzipSync(exportQDPX(v)),recovered=JSON.parse(strFromU8(archive['research-weave.json'])).state;assert.equal((strFromU8(archive['project.qde']).match(/<Coding /g)||[]).length,1);assert.deepEqual(recovered.codings.map(c=>c.coder),['a']);assert.equal(recovered.codings.length,1);assert.ok(!JSON.stringify(recovered).includes('Hidden decision'));});
test('Blind operations cannot access hidden records, replace shared structure, materialize hidden queries, or spoof policy updates',()=>{const s=fixture();s.settings.teamAccess={blindCoding:true};const a=teamAccess(s,'coder',{id:'a'});for(const op of [{type:'coding.delete',data:{id:'other'}},{type:'suggestion.accept',data:{id:'sb'}},{type:'memo.save',data:{id:'mb',title:'Taken'}},{type:'case.save',data:{name:'Case'}},{type:'query.materialize',data:{name:'Copy all'}},{type:'permissions.update',data:{blindCoding:false}},{type:'settings.save',data:{teamAccess:{blindCoding:false}}},{type:'memo.save',data:{citations:[{codingId:'other'}]}}]){s.suggestions=[{id:'sb',createdBy:'b'}];assert.throws(()=>authorizeOperation(s,op,a));}authorizeOperation(s,{type:'coding.create',data:{}},a);const after=applyOperation(s,{type:'coding.create',data:{documentId:'d',start:0,end:5,codeIds:['c']}},'a','coder');assert.equal(after.codings.length,2);assert.equal(after.codings[1].id,'other');});
test('Owner policies validate known Boolean capabilities and preserve role authority',()=>{const s=fixture();const changed=applyOperation(s,{type:'permissions.update',data:{blindCoding:true,roles:{coder:{ai:false,codebook:false}}}},'owner','owner');assert.equal(teamAccess(changed,'coder',{id:'a'}).capabilities.ai,false);assert.throws(()=>normalizeTeamPolicy({blindCoding:true,roles:{coder:{ai:'no'}}}));assert.throws(()=>normalizeTeamPolicy({blindCoding:true,roles:{viewer:{coding:true}}}));assert.throws(()=>normalizeTeamPolicy({blindCoding:true,roles:{coder:{admin:true}}}));assert.throws(()=>applyOperation(s,{type:'settings.save',data:{teamAccess:{blindCoding:true}}},'reviewer','reviewer'));assert.deepEqual(teamAccess(s,'coder',{id:'a'}).policy.blindCoding,false);});
