import test from 'node:test';import assert from 'node:assert/strict';
import {timestampedTranscript} from '../src/transcript.mjs';
import {applyOperation,emptyState} from '../src/domain.mjs';
import {canSeekTurn,transcriptExport} from '../src/transcript-alignment.mjs';
import {exportQDPX} from '../src/refi.mjs';import {unzipSync,strFromU8} from 'fflate';
const raw={model:'fixture',language:'en',segments:[{id:'raw-id',speaker:'SPEAKER_00',start:0,end:1.125,text:'😀 café',words:[{word:'😀',start:0,end:.125,speaker:'SPEAKER_00'},{word:'café',start:null,end:null}]}]};
function fixture(){return applyOperation(emptyState('Synthetic timestamps'),{type:'source.import',data:{name:'Synthetic',...timestampedTranscript(raw)}},'researcher');}
test('Timing parser separates zero, missing and codepoint anchors and retains raw words/provenance',()=>{const parsed=timestampedTranscript(raw),t=parsed.turns[0];assert.equal(timestampedTranscript([{text:'x',timeStart:null,start:20,timeEnd:null,end:21}]).turns[0].timeStart,null);assert.equal(t.timeStart,0);assert.equal(t.timeEnd,1.125);assert.equal(t.end,7);assert.equal(t.sourceId,'raw-id');assert.deepEqual(t.raw,raw.segments[0]);assert.deepEqual(t.words,raw.segments[0].words);assert.equal(t.wordTiming[1].timeStart,null);assert.equal(parsed.transcriptMetadata.provider.language,'en');for(const value of [false,true,{},[],NaN,-1])assert.throws(()=>timestampedTranscript([{text:'x',start:value}]));for(const value of [null,undefined,'',' '])assert.equal(timestampedTranscript([{text:'x',start:value}]).turns[0].timeStart,null);assert.equal(timestampedTranscript({turns:[{text:'x',start:20,end:21}]}).turns[0].timeStart,null);});
test('Retranscription and speaker corrections retain full timing history through JSON and native QDPX',async()=>{let s=fixture(),d=s.documents[0];s=applyOperation(s,{type:'source.speaker',data:{id:d.id,from:'SPEAKER_00',to:'Participant'}},'reviewer');d=s.documents[0];assert.equal(d.turns[0].rawSpeaker,'SPEAKER_00');assert.equal(d.turns[0].words[0].speaker,'SPEAKER_00');s=applyOperation(s,{type:'source.transcript',data:{id:d.id,...timestampedTranscript([{text:'Corrected words',start:0,end:2}])}},'reviewer');d=s.documents[0];assert.equal(d.versions.at(-1).turns[0].timeEnd,1.125);assert.equal(d.versions.at(-1).turns[0].speaker,'Participant');assert.deepEqual(d.versions.at(-1).turns[0].words,raw.segments[0].words);const round=JSON.parse(JSON.stringify(transcriptExport(d)));assert.deepEqual(timestampedTranscript(round).versions,d.versions);const zip=unzipSync(exportQDPX(s));assert.deepEqual(JSON.parse(strFromU8(zip['research-weave.json'])).state.documents[0].versions,d.versions);});
test('Recording replacement keeps old alignment but prevents seeking the wrong audio; untimed never becomes timed',()=>{let s=fixture(),id=s.documents[0].id;const op=(type,data)=>{s=applyOperation(s,{type,data:{id,...data}},'reviewer');return s.documents[0];};let d=op('source.media.attach',{mediaKey:'project/A',mediaType:'audio/wav'});assert.equal(canSeekTurn(d,d.turns[0]),false);d=op('source.alignment.bind',{recordingKey:'project/A',note:'Checked start and end against the original recording.'});assert.equal(canSeekTurn(d,d.turns[0]),true);d=op('source.media.attach',{mediaKey:'project/B',mediaType:'audio/wav'});assert.equal(d.turns[0].timeStart,0);assert.equal(canSeekTurn(d,d.turns[0]),false);assert.equal(d.versions.at(-1).mediaKey,'project/A');assert.throws(()=>op('source.transcript',{...timestampedTranscript(raw),recordingKey:'project/A'}),/different recording/);let u=applyOperation(emptyState(),{type:'source.import',data:{name:'Untimed',...timestampedTranscript([{text:'No supplied time'}])}},'reviewer');u=applyOperation(u,{type:'source.media.attach',data:{id:u.documents[0].id,mediaKey:'project/A',mediaType:'audio/wav'}},'reviewer');assert.equal(u.documents[0].turns[0].timeStart,null);assert.equal(u.documents[0].alignment.status,'untimed');});
test('Text edits crossing a turn preserve times and mark its alignment uncertain',()=>{let s=fixture(),d=s.documents[0];s=applyOperation(s,{type:'source.revise',data:{id:d.id,text:'😀 corrected café\n'}},'reviewer');d=s.documents[0];assert.equal(d.turns[0].timeStart,0);assert.equal(d.turns[0].timingStatus,'needs_review');assert.deepEqual(d.versions[0].turns[0].words,raw.segments[0].words);});

test('Media code selections pin their recording and become review-required on replacement',()=>{let s=fixture(),d=s.documents[0];s.codes=[{id:'code',name:'Theme'}];s=applyOperation(s,{type:'source.media.attach',data:{id:d.id,mediaKey:'project/A',mediaType:'audio/wav'}},'researcher');s=applyOperation(s,{type:'coding.create',data:{documentId:d.id,kind:'media',timeStart:0,timeEnd:1.125,codeIds:['code']}},'researcher');assert.equal(s.codings[0].recordingKey,'project/A');s=applyOperation(s,{type:'source.media.attach',data:{id:d.id,mediaKey:'project/B',mediaType:'audio/wav'}},'reviewer');assert.equal(s.codings[0].status,'needs_review');assert.equal(s.codings[0].recordingKey,'project/A');assert.equal(s.codings[0].timeStart,0);});
