import {normalizeAudioOptions,audioStage} from './audio-options.mjs';
import {uid} from '../src/domain.mjs';
import {validateAudioResult} from './audio-result.mjs';
const problem=(message,status=400)=>{throw Object.assign(Error(message),{status});};
const now=()=>new Date().toISOString();
const headers=env=>env.AUDIO_WORKER_TOKEN?{Authorization:'Bearer '+env.AUDIO_WORKER_TOKEN}:{};
async function remote(env,path,options={}){if(!env.AUDIO_WORKER_URL)problem('Connect a transcription worker to run recording jobs.',503);const r=await fetch(env.AUDIO_WORKER_URL.replace(/\/$/,'')+path,{...options,headers:{...headers(env),...options.headers},signal:AbortSignal.timeout(120000)});if(!r.ok)throw Object.assign(Error('The recording worker could not accept this operation.'),{status:502,workerStatus:r.status});return r.json();}
export async function audioRoutes(req,env,pid,p,role,u,tail){const db=env.DB;
 if(tail==='uploads'&&req.method==='POST'){if(role==='viewer')problem('Read-only project.',403);const b=await req.json();if(!/^(audio\/(mpeg|wav|x-wav|mp4|quicktime|ogg|flac|webm)|video\/(mp4|webm|ogg|quicktime)|image\/(png|jpeg|webp|gif)|application\/pdf)$/.test(b.type)||!Number.isSafeInteger(b.size)||b.size<=0||b.size>2000000000)problem('Choose a supported file up to 2 GB.');const key=pid+'/'+uid(),upload=await env.BUCKET.createMultipartUpload(key,{httpMetadata:{contentType:b.type},customMetadata:{name:String(b.name).slice(0,200)}});await db.prepare('INSERT INTO site_settings (key,value) VALUES (?,?)').bind('upload:'+key,JSON.stringify({actor:u.id,uploadId:upload.uploadId,type:b.type,name:b.name,size:b.size,created:Date.now()})).run();return {data:{key,uploadId:upload.uploadId}};}
 if(tail.startsWith('uploads/')&&req.method==='POST'){if(role==='viewer')problem('Read-only project.',403);const local=tail.slice(8).split('/'),key=pid+'/'+local[0],row=await db.prepare('SELECT value FROM site_settings WHERE key=?').bind('upload:'+key).first();if(!row)problem('Upload session not found.',404);const session=JSON.parse(row.value);if(session.actor!==u.id)problem('This upload belongs to another researcher.',403);const upload=env.BUCKET.resumeMultipartUpload(key,session.uploadId);if(local[1]==='complete'){const b=await req.json();if(!Array.isArray(b.parts)||b.parts.length>400)problem('Invalid upload parts.');await upload.complete(b.parts);const object=await env.BUCKET.head(key);if(object.size!==session.size){await env.BUCKET.delete(key);problem('Upload size check failed. Upload again.');}await db.prepare('DELETE FROM site_settings WHERE key=?').bind('upload:'+key).run();return {data:{mediaKey:key,mediaType:session.type,name:session.name}};}if(local[1]==='cancel'){await upload.abort();await db.prepare('DELETE FROM site_settings WHERE key=?').bind('upload:'+key).run();return {data:{ok:true}};}const n=Number(local[1]);if(!Number.isInteger(n)||n<1||n>400||Number(req.headers.get('Content-Length'))>8388608)problem('Invalid upload part.');return {data:await upload.uploadPart(n,req.body)};}
 if(tail==='jobs'&&req.method==='GET'&&new URL(req.url).searchParams.get('paginated')==='true'){const q=new URL(req.url).searchParams,offset=Math.max(0,Number(q.get('offset'))||0),limit=Math.max(1,Math.min(200,Number(q.get('limit'))||100)),total=await db.prepare('SELECT COUNT(*) AS n FROM jobs WHERE project_id=?').bind(pid).first(),rows=await db.prepare('SELECT id,source_id,recording_key,status,progress,error,created_at,updated_at FROM jobs WHERE project_id=? ORDER BY created_at DESC,id DESC LIMIT ? OFFSET ?').bind(pid,limit,offset).all();return {data:{records:rows.results,total:total.n,offset}};}
 if(tail==='jobs'&&req.method==='GET'){return {data:(await db.prepare('SELECT id,source_id,recording_key,status,progress,error,created_at,updated_at FROM jobs WHERE project_id=? ORDER BY created_at DESC LIMIT 100').bind(pid).all()).results};}
 if(tail==='jobs'&&req.method==='POST'){if(role==='viewer')problem('Read-only project.',403);if(!env.AUDIO_WORKER_URL)problem('Connect a transcription worker to run recording jobs.',503);const b=await req.json();let options;try{options=normalizeAudioOptions(b);}catch(e){problem(e.message);}const state=JSON.parse(p.state),d=state.documents.find(d=>d.id===b.documentId);if(!d?.mediaKey?.startsWith(pid+'/')||!/^(audio|video)\//.test(d.mediaType))problem('Choose an uploaded recording.');const id=uid();await db.prepare('INSERT INTO jobs (id,project_id,source_id,status,progress,created_by,created_at,updated_at,remote_id,recording_key) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(id,pid,d.id,'submitting',0,u.id,now(),now(),id,d.mediaKey).run();try{const object=await env.BUCKET.get(d.mediaKey);if(!object)problem('Recording not found.',404);const result=await remote(env,'/jobs?project_id='+encodeURIComponent(pid)+'&job_id='+id+'&name='+encodeURIComponent(d.name)+'&'+new URLSearchParams(Object.entries(options).map(([key,value])=>[({numSpeakers:'num_speakers',minSpeakers:'min_speakers',maxSpeakers:'max_speakers',batchSize:'batch_size'}[key]||key),String(value)])),{method:'POST',headers:{'Content-Type':d.mediaType,'Idempotency-Key':id},body:object.body});if(typeof result.id!=='string')problem('The worker returned no durable job identifier.',502);await db.prepare('UPDATE jobs SET remote_id=?,status=?,updated_at=? WHERE id=?').bind(result.id,'queued',now(),id).run();return {data:{id,status:'queued'},status:202};}catch(e){await db.prepare('UPDATE jobs SET status=?,error=?,updated_at=? WHERE id=?').bind('submitting','Submission acknowledgement was interrupted. Check progress using this job before retrying.',now(),id).run();throw e;}}
 if(tail.startsWith('jobs/')){const id=tail.slice(5).split('/')[0],row=await db.prepare('SELECT * FROM jobs WHERE id=? AND project_id=?').bind(id,pid).first();if(!row)problem('Recording job not found.',404);if(req.method==='DELETE'){if(role==='viewer'||(u.id!==row.created_by&&!['owner','reviewer'].includes(role)))problem('Only the author or reviewer may cancel this job.',403);if(['completed','cancelled','failed'].includes(row.status))return {data:{id,status:row.status}};if(row.remote_id)await remote(env,'/jobs/'+encodeURIComponent(row.remote_id)+'?project_id='+encodeURIComponent(pid),{method:'DELETE'});await db.prepare('UPDATE jobs SET status=?,updated_at=? WHERE id=?').bind('cancelled',now(),id).run();return {data:{id,status:'cancelled'}};}
 if(req.method==='GET'){if(['completed','cancelled','failed'].includes(row.status)){const result=row.result_key?await env.BUCKET.get(row.result_key):null;return {data:{...row,result:result?await result.json():undefined}};}if(!row.remote_id)return {data:row};let r;try{r=await remote(env,'/jobs/'+encodeURIComponent(row.remote_id)+'?project_id='+encodeURIComponent(pid));}catch(e){if(row.status==='submitting'&&e.workerStatus===404){if(Date.now()-Date.parse(row.created_at)>180000){await db.prepare('UPDATE jobs SET status=?,error=?,updated_at=? WHERE id=?').bind('failed','The worker did not retain this submission. Retry the stored recording.',now(),id).run();return {data:{...row,status:'failed',error:'The worker did not retain this submission. Retry the stored recording.'}};}return {data:row};}throw e;}if(!['queued','running','completed','failed','cancelled'].includes(r.status))problem('Worker returned an unknown job state.',502);let key=null;if(r.status==='completed'){validateAudioResult(r.result);key='jobs/'+pid+'/'+id+'.json';await env.BUCKET.put(key,JSON.stringify(r.result),{httpMetadata:{contentType:'application/json'}});}const update=await db.prepare("UPDATE jobs SET status=?,progress=?,result_key=?,error=?,updated_at=? WHERE id=? AND status NOT IN ('completed','cancelled','failed')").bind(r.status,Math.max(0,Math.min(100,Number(r.progress)||0)),key,String(r.error||''),now(),id).run();if(update.meta.changes!==1){const current=await db.prepare('SELECT status FROM jobs WHERE id=?').bind(id).first();return {data:{id,source_id:row.source_id,recording_key:row.recording_key,status:current.status}};}return {data:{id,source_id:row.source_id,recording_key:row.recording_key,status:r.status,...audioStage(r.status,r),options:r.options,result:r.result,error:r.error}};}}
 return null;
}
