import {validateSubcodeDrafts} from '../src/subcode-proposals.mjs';
import {modelBudget,promptBytes,RESEARCH_POLICY} from './ai-budget.mjs';
import {intersects} from '../src/processing-domain.mjs';
import {sha256} from './storage.mjs';
import {cp,slice,uid} from '../src/domain.mjs';
export function cosine(a,b){if(!Array.isArray(a)||!Array.isArray(b)||a.length!==b.length||!a.length)throw Error('Embedding dimensions do not match.');let dot=0,x=0,y=0;for(let i=0;i<a.length;i++){if(!Number.isFinite(a[i])||!Number.isFinite(b[i]))throw Error('Invalid embedding vector.');dot+=a[i]*b[i];x+=a[i]*a[i];y+=b[i]*b[i];}return x&&y?dot/Math.sqrt(x*y):0;}
export function chunks(s,sourceId='',size=650,mode='fixed'){
 if(!Number.isInteger(size)||size<=100||size>10000)throw Error('Chunk size must be an integer between 101 and 10,000.');
 if(!['fixed','paragraph'].includes(mode))throw Error('Choose fixed or paragraph chunking.');
 const out=[];
 for(const d of s.documents.filter(d=>!d.excludeAI&&d.sourceRole!=='reference'&&(!sourceId||d.id===sourceId))){
  const points=cp(d.text);
  const emit=(start,end)=>{if(start<end&&!(d.reviewFlags||[]).some(f=>intersects(f,{start,end})))out.push({id:d.id+':'+d.revision+':'+start,documentId:d.id,sourceRevision:d.revision,start,end,text:points.slice(start,end).join('')});};
  const window=(start,end)=>{for(let a=start;a<end;a+=size-100){const b=Math.min(end,a+size);emit(a,b);if(b===end)break;}};
  if(mode==='fixed')window(0,points.length);
  else{
   let lineStart=0;
   for(let i=0;i<=points.length;i++)if(i===points.length||points[i]==='\n'){
    let a=lineStart,b=i;
    while(a<b&&/\s/u.test(points[a]))a++;
    while(b>a&&/\s/u.test(points[b-1]))b--;
    window(a,b);lineStart=i+1;
   }
  }
 }
 return out;
}
export function outlierCutoff(scores){
 if(scores.length<4)return null;
 if(scores.some(x=>!Number.isFinite(x)))throw Error('Invalid outlier scores.');
 const mean=scores.reduce((n,x)=>n+x,0)/scores.length;
 const spread=Math.sqrt(scores.reduce((n,x)=>n+(x-mean)**2,0)/scores.length);
 return mean-Math.max(1.5*spread,0.05);
}
function auth(env){return {'Content-Type':'application/json',...(env.AI_API_KEY?{'Authorization':'Bearer '+env.AI_API_KEY}:{})};}
export async function embed(env,texts){const base=env.EMBEDDING_BASE_URL||env.AI_BASE_URL;if(!base)throw Object.assign(Error('Connect an embedding service to use semantic search.'),{status:503});const response=await fetch(base.replace(/\/$/,'')+'/v1/embeddings',{method:'POST',headers:auth({...env,AI_API_KEY:env.EMBEDDING_API_KEY||((!env.EMBEDDING_BASE_URL||new URL(env.EMBEDDING_BASE_URL).origin===new URL(env.AI_BASE_URL||env.EMBEDDING_BASE_URL).origin)?env.AI_API_KEY:'')}),body:JSON.stringify({model:env.EMBEDDING_MODEL||'nomic-embed-text',input:texts}),signal:AbortSignal.timeout(45000)});if(!response.ok)throw Error('The embedding service could not complete this request.');const data=await response.json();const rows=data.data?.sort((a,b)=>(a.index||0)-(b.index||0));if(!rows||rows.length!==texts.length||rows.some(r=>!Array.isArray(r.embedding)||!r.embedding.length||r.embedding.some(v=>!Number.isFinite(v))))throw Error('The service returned invalid embedding vectors.');return rows.map(r=>r.embedding);}
export async function semantic(env,pid,s,request){if(!request.query?.trim())throw Error('Enter a topic or question.');const model=(env.EMBEDDING_BASE_URL||env.AI_BASE_URL||'')+'|'+(env.EMBEDDING_MODEL||'nomic-embed-text')+'|chunks:'+(request.chunkMode||'fixed')+':v1',all=chunks(s,request.documentId,650,request.chunkMode||'fixed'),scope=all.slice(request.offset||0,(request.offset||0)+120);const docs=s.documents.filter(d=>!d.excludeAI&&d.sourceRole!=='reference'&&(!request.documentId||d.id===request.documentId));const hashes=new Map(await Promise.all(docs.map(async d=>[d.id,await sha256(new TextEncoder().encode(d.text))])));for(const c of all){c.contentHash=hashes.get(c.documentId);c.id=c.documentId+':'+c.sourceRevision+':'+c.contentHash+':'+c.start;}const records=await env.DB.prepare('SELECT source_id,revision,start,end,vector,content_hash FROM embeddings WHERE project_id=? AND model=?').bind(pid,model).all();const cache=new Map(records.results.map(r=>[r.source_id+':'+r.revision+':'+r.content_hash+':'+r.start,r]));const missing=scope.filter(c=>!cache.has(c.id)||cache.get(c.id).end!==c.end);for(let i=0;i<missing.length;i+=24){const batch=missing.slice(i,i+24),vectors=await embed(env,batch.map(c=>c.text));await env.DB.batch(batch.map((c,j)=>env.DB.prepare('INSERT OR REPLACE INTO embeddings (id,project_id,source_id,revision,model,start,end,vector,created_at,content_hash) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(pid+':'+model+':'+c.id,pid,c.documentId,c.sourceRevision,model,c.start,c.end,JSON.stringify(vectors[j]),new Date().toISOString(),c.contentHash)));batch.forEach((c,j)=>cache.set(c.id,{vector:JSON.stringify(vectors[j]),source_id:c.documentId,revision:c.sourceRevision,start:c.start,end:c.end,content_hash:c.contentHash}));}
 const [q]=await embed(env,[request.query]);const allowed=new Map(docs.map(d=>[d.id,d]));const valid=[...cache.values()].filter(r=>allowed.get(r.source_id)?.revision===r.revision&&hashes.get(r.source_id)===r.content_hash&&all.some(c=>c.documentId===r.source_id&&c.start===r.start&&c.end===r.end));const hits=valid.map(r=>({documentId:r.source_id,sourceRevision:r.revision,start:r.start,end:r.end,text:slice(allowed.get(r.source_id).text,r.start,r.end),score:cosine(q,JSON.parse(r.vector))})).sort((a,b)=>b.score-a.score).slice(0,20);return {hits,indexed:valid.length,total:all.length,nextOffset:(request.offset||0)+scope.length<all.length?(request.offset||0)+scope.length:null,model};}
export async function chatJSON(env,system,content){if(!env.AI_BASE_URL)throw Object.assign(Error('Connect a language model to use this review.'),{status:503});const budget=modelBudget(env),policy=system+RESEARCH_POLICY;if(promptBytes(policy,content)>budget.inputBytes)throw Object.assign(Error('Evidence exceeds the configured model context budget. Choose a smaller scope; no evidence was silently truncated.'),{status:400});const response=await fetch(env.AI_BASE_URL.replace(/\/$/,'')+'/v1/chat/completions',{method:'POST',headers:auth(env),body:JSON.stringify({model:env.AI_MODEL||'qwen3.5:9b',temperature:0,max_tokens:budget.responseTokens,messages:[{role:'system',content:policy},{role:'user',content:JSON.stringify(content)}]}),signal:AbortSignal.timeout(45000)});if(!response.ok)throw Object.assign(Error('The language model could not complete this review.'),{status:502});const result=await response.json();const choice=result.choices?.[0];if(choice?.finish_reason&&choice.finish_reason!=='stop')throw Object.assign(Error('The model response was incomplete or withheld ('+choice.finish_reason+'). No research decisions changed. Retry with a smaller evidence scope.'),{status:502});try{const parsed=JSON.parse(choice.message.content.replace(/^```(?:json)?\s*|\s*```$/g,''));if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw Error('Expected object');Object.defineProperty(parsed,'__provider',{value:{finishReason:choice.finish_reason||'unspecified',model:result.model||env.AI_MODEL||'qwen3.5:9b',usage:result.usage||null,budget},enumerable:false});return parsed;}catch{throw Object.assign(Error('The model returned invalid structured output. No research decisions changed.'),{status:502});}}
export function evidenceSet(s,codeId,documentId,decisionScope='all',maxInputBytes=32000){const code=s.codes.find(c=>c.id===codeId),sources=new Map(s.documents.filter(d=>!d.excludeAI&&d.sourceRole!=='reference'&&(!documentId||d.id===documentId)).map(d=>[d.id,d]));const used=new Set(),all=s.codings.filter(c=>!c.deletedAt&&c.status!=='needs_review'&&c.status!=='flagged'&&(decisionScope!=='accepted'||c.status==='accepted')&&!c.kind&&sources.has(c.documentId)&&slice(sources.get(c.documentId).text,c.start,c.end)===c.text&&(c.sourceRevision==null||c.sourceRevision===(sources.get(c.documentId).revision||1))&&!(sources.get(c.documentId).reviewFlags||[]).some(f=>intersects(f,c))&&(!codeId||c.codeId===codeId)).filter(c=>{const key=c.documentId+':'+c.start+':'+c.end;if(used.has(key))return false;used.add(key);return true;});const bySource=new Map();for(const c of all){if(!bySource.has(c.documentId))bySource.set(c.documentId,[]);bySource.get(c.documentId).push(c);}const ordered=[];for(const list of bySource.values()){list.sort((a,b)=>a.start-b.start);const count=Math.min(80,list.length);bySource.set(list[0]?.documentId,list.length<=count?list:Array.from({length:count},(_,i)=>list[Math.floor(i*(list.length-1)/(count-1))]));}const lists=[...bySource.values()];for(let i=0;i<Math.max(0,...lists.map(l=>l.length));i++)for(const list of lists)if(list[i])ordered.push(list[i]);const selected=[];let units=0;for(const c of ordered){if(selected.length>=80||units+new TextEncoder().encode(JSON.stringify(c)).length+500>maxInputBytes)continue;selected.push({id:c.id,documentId:c.documentId,start:c.start,end:c.end,text:c.text,sourceRevision:sources.get(c.documentId).revision,status:c.status,labels:s.codings.filter(x=>!x.deletedAt&&x.documentId===c.documentId&&x.start===c.start&&x.end===c.end&&x.coder===c.coder).map(x=>s.codes.find(k=>k.id===x.codeId)?.name).filter(Boolean),sourceReview:Object.fromEntries(Object.entries(sources.get(c.documentId).attributes||{}).filter(([k])=>/consent|attribution|review/i.test(k)))});units+=new TextEncoder().encode(JSON.stringify(selected.at(-1))).length;}return {code,evidence:selected,total:all.length,decisionScope,sampling:'Spread across source positions, round-robin across sources; maximum 80 passages, constrained by conservative model input-byte budget'};}
export async function advancedReview(env,s,b){const mode=b.mode||'summary';if(!['summary','definition','consistency','hierarchy','embedding-outliers','subcodes'].includes(mode))throw Error('Choose a supported review operation.');if(['definition','consistency','subcodes'].includes(mode)&&!s.codes.some(c=>c.id===b.codeId))throw Error('Choose a code for definition or consistency review.');const decisionScope=b.decisionScope==='accepted'?'accepted':'all';const {code,evidence,total,sampling}=evidenceSet(s,b.codeId,b.documentId,decisionScope,Math.max(1000,modelBudget(env).inputBytes-2200));if(mode==='hierarchy'){const available=s.codes.filter(c=>c.codable!==false).map(c=>({id:c.id,name:c.name,definition:c.description}));const result=await chatJSON(env,'Suggest defensible parent groups for the supplied codes, without changing names or merging codes. Return {groups:[{name,reason,codeIds:[]}]}. Each child must reference a supplied ID and appear in at most one group.',{codes:available});const allowed=new Set(available.map(c=>c.id)),seen=new Set();const groups=[];for(const g of result.groups||[]){if(typeof g.name==='string'&&g.name.trim()&&Array.isArray(g.codeIds)&&g.codeIds.length>1&&new Set(g.codeIds).size===g.codeIds.length&&g.codeIds.every(id=>allowed.has(id)&&!seen.has(id))){g.codeIds.forEach(id=>seen.add(id));groups.push({name:g.name,reason:String(g.reason||''),codeIds:g.codeIds});}}return {mode,groups,budget:modelBudget(env),providerResponses:[result.__provider],model:env.AI_MODEL||'qwen3.5:9b'};}
 if(!evidence.length)throw Error('No eligible evidence in this decision scope. Code passages or select a different scope.');if(mode==='subcodes'){
 const parent=s.codes.find(c=>c.id===b.codeId&&!c.archivedAt&&c.codable!==false);if(!parent)throw Error('Choose an active parent code.');
 const existing=s.codes.filter(c=>c.parentId===parent.id).map(c=>c.name);
 const result=await chatJSON(env,'Propose specific subcodes supported by the supplied parent-code evidence. Return {proposals:[{name,description,citations:[evidenceId]}]} with at most 8 entries. Each definition must explain inclusion criteria, each proposal must cite supplied evidence, and names must be new relative to existing subcodes. Do not code passages or infer facts outside the evidence.',{parent:{id:parent.id,name:parent.name,description:parent.description||''},existing,evidence});
 if(!Array.isArray(result.proposals))throw Error('The model returned no structured subcode proposals.');
 const ids=new Map(evidence.map(e=>[e.id,e]));const proposals=[];let invalidProposalsRejected=0;
 for(const p of result.proposals.slice(0,8)){try{
  if(!Array.isArray(p.citations)||p.citations.some(id=>!ids.has(id)))throw Error('Unknown evidence citation.');
  const candidate={name:p.name,description:p.description,citations:[...new Set(p.citations)].map(id=>ids.get(id))};
  validateSubcodeDrafts(s,parent.id,[...proposals,candidate]);proposals.push(candidate);
 }catch{invalidProposalsRejected++;}}
 return {mode,codeId:parent.id,proposals,sent:evidence.length,total,decisionScope,sampling,coverage:{sent:evidence.length,total,sampled:evidence.length<total,invalidProposalsRejected},budget:modelBudget(env),providerResponses:[result.__provider],model:env.AI_MODEL||'qwen3.5:9b'};
 }
 if(mode==='embedding-outliers'){if(!b.codeId||evidence.length<4)throw Error('Choose a code with at least four eligible excerpts.');const vectors=[];for(let i=0;i<evidence.length;i+=24)vectors.push(...await embed(env,evidence.slice(i,i+24).map(e=>e.text)));const dimension=vectors[0].length;if(vectors.some(v=>v.length!==dimension))throw Error('Embedding dimensions do not match.');const normalized=vectors.map(v=>{const norm=Math.sqrt(v.reduce((a,x)=>a+x*x,0));return v.map(x=>norm?x/norm:0);});const scored=evidence.map((e,i)=>{const center=Array.from({length:dimension},(_,k)=>normalized.reduce((n,v,j)=>n+(j===i?0:v[k]),0)/(vectors.length-1)),score=cosine(normalized[i],center);return {evidenceId:e.id,evidence:e,score,reason:'Embedding similarity to other sampled excerpts: '+score.toFixed(3)+'. Low similarity is a reading prompt, not a coding error.'};});const cutoff=outlierCutoff(scored.map(f=>f.score)),findings=scored.filter(f=>cutoff!==null&&f.score<cutoff).sort((a,b)=>a.score-b.score);return {mode,findings,cutoff,sent:evidence.length,total,decisionScope,sampling,model:env.EMBEDDING_MODEL||'nomic-embed-text',method:'Cosine similarity to leave-one-out normalized embedding centroid; scores below the sample mean by at least 1.5 population standard deviations and 0.05; no required outliers'};}if(mode==='consistency'){const result=await chatJSON(env,'Review whether each coded quotation is supported by the supplied definition. Return {findings:[{evidenceId,reason}]}, flagging only clear mismatches. This is a reading aid, not inter-coder agreement.',{code,evidence});const ids=new Set(evidence.map(e=>e.id));return {mode,budget:modelBudget(env),providerResponses:[result.__provider],coverage:{sent:evidence.length,total,sampled:evidence.length<total},findings:(result.findings||[]).filter(f=>ids.has(f.evidenceId)&&typeof f.reason==='string').map(f=>({...f,evidence:evidence.find(e=>e.id===f.evidenceId)})),sent:evidence.length,total,decisionScope,sampling,model:env.AI_MODEL||'qwen3.5:9b'};}
 const instruction=mode==='definition'?'Draft a code definition with inclusion and exclusion criteria grounded in the supplied quotations.':'Summarize recurring themes, differences, and counterexamples in the supplied quotations. Distinguish estimates and opinions from factual claims.';const result=await chatJSON(env,instruction+' Return {title,text,citations:[evidenceId]}. Each substantive conclusion must be traceable to a supplied evidence ID.',{code,evidence});if(typeof result.text!=='string'||!result.text.trim())throw Error('The model returned no review text.');const citations=(result.citations||[]).filter(id=>evidence.some(e=>e.id===id));if(!citations.length)throw Error('The model did not link its review to supplied evidence. No changes were saved.');return {mode,budget:modelBudget(env),providerResponses:[result.__provider],coverage:{sent:evidence.length,total,sampled:evidence.length<total},title:result.title||'AI-assisted review',text:result.text,citations:citations.map(id=>evidence.find(e=>e.id===id)),sent:evidence.length,total,decisionScope,sampling,codeId:b.codeId,model:env.AI_MODEL||'qwen3.5:9b'};}
