import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core';
export const projects = sqliteTable('projects', {id:text('id').primaryKey(),name:text('name').notNull(),ownerId:text('owner_id').notNull(),state:text('state').notNull(),revision:integer('revision').notNull().default(0),lastOperation:text('last_operation'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()});
export const members = sqliteTable('members', {id:text('id').primaryKey(),projectId:text('project_id').notNull().references(()=>projects.id),userId:text('user_id'),email:text('email').notNull(),role:text('role').notNull()},t=>[index('members_project').on(t.projectId),index('members_identity').on(t.userId,t.email)]);
export const events=sqliteTable('events',{id:text('id').primaryKey(),projectId:text('project_id').notNull().references(()=>projects.id),actor:text('actor').notNull(),action:text('action').notNull(),detail:text('detail').notNull(),createdAt:text('created_at').notNull()},t=>[index('events_project').on(t.projectId)]);
export const siteSettings=sqliteTable('site_settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const backups=sqliteTable('backups',{id:text('id').primaryKey(),projectId:text('project_id').notNull().references(()=>projects.id),revision:integer('revision').notNull(),objectKey:text('object_key').notNull(),checksum:text('checksum').notNull(),bytes:integer('bytes').notNull(),label:text('label').notNull(),actor:text('actor').notNull(),createdAt:text('created_at').notNull()},t=>[index('backups_project_revision').on(t.projectId,t.revision)]);
export const embeddings=sqliteTable('embeddings',{id:text('id').primaryKey(),projectId:text('project_id').notNull().references(()=>projects.id),sourceId:text('source_id').notNull(),revision:integer('revision').notNull(),model:text('model').notNull(),start:integer('start').notNull(),end:integer('end').notNull(),vector:text('vector').notNull(),contentHash:text('content_hash').notNull().default(''),createdAt:text('created_at').notNull()},t=>[index('embeddings_scope').on(t.projectId,t.sourceId,t.revision,t.model)]);
export const jobs=sqliteTable('jobs',{id:text('id').primaryKey(),projectId:text('project_id').notNull().references(()=>projects.id),sourceId:text('source_id').notNull(),remoteId:text('remote_id'),recordingKey:text('recording_key'),status:text('status').notNull(),progress:integer('progress').notNull().default(0),resultKey:text('result_key'),error:text('error'),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('jobs_project').on(t.projectId,t.createdAt)]);
export const privateNotes=sqliteTable('private_notes',{id:text('id').primaryKey(),projectId:text('project_id').notNull().references(()=>projects.id),authorId:text('author_id').notNull(),title:text('title').notNull(),content:text('content').notNull(),revision:integer('revision').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('private_notes_author_project').on(t.projectId,t.authorId,t.updatedAt)]);
