import React,{useState} from 'react';
import {Files,X,Sparkles} from 'lucide-react';
export const time=n=>new Date(n).toLocaleString();
export const fmt=n=>String(Math.floor(n/60)).padStart(2,'0')+':'+String(Math.floor(n%60)).padStart(2,'0');
export function IconButton({icon:Icon,label,onClick,...rest}){return <button className="icon-button" aria-label={label} title={label} onClick={onClick} {...rest}><Icon size={17}/></button>}
export function PlayIcon(){return <Sparkles size={17}/>;}
export function Badge({children,type=''}){return <span className={'badge '+type}>{children}</span>}
export function Empty({icon:Icon=Files,title,children,action}){return <div className="empty"><Icon size={32}/><h3>{title}</h3><p>{children}</p>{action}</div>}
export function Modal({title,children,onClose,wide=false}){return <div className="modal-shade" onClick={onClose}><section className={'modal '+(wide?'wide':'')} role="dialog" aria-modal="true" aria-label={title} onClick={e=>e.stopPropagation()}><header><h2>{title}</h2><IconButton icon={X} label="Close dialog" onClick={onClose}/></header>{children}</section></div>}
export function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
export function FormModal({title,fields,initial={},onSave,onClose,wide=false,help}){const [data,set]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState('');return <Modal title={title} onClose={onClose} wide={wide}><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await onSave(data);onClose();}catch(e){setError(e.message);}finally{setBusy(false);}}}>{help&&<p className="muted">{help}</p>}{fields.map(f=><Field label={f.label} key={f.key}>{f.options?<select value={data[f.key]??''} onChange={e=>set({...data,[f.key]:e.target.value})}>{f.options.map(o=><option value={typeof o==='string'?o:o.value} key={typeof o==='string'?o:o.value}>{typeof o==='string'?o:o.label}</option>)}</select>:f.textarea?<textarea rows={f.rows||6} value={data[f.key]??''} onChange={e=>set({...data,[f.key]:e.target.value})}/>:<input type={f.type||'text'} required={f.required} value={data[f.key]??''} onChange={e=>set({...data,[f.key]:e.target.value})}/>}</Field>)}{error&&<p className="error">{error}</p>}<footer><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save'}</button></footer></form></Modal>}
