import {caseIncludes,intersects} from './research-operations.mjs';
export function descendants(state,id){const ids=new Set([id]);let n;do{n=ids.size;for(const c of state.codes)if(ids.has(c.parentId))ids.add(c.id);}while(n!==ids.size);return ids;}
export const geometry=r=>r?[r.page??null,r.x,r.y,r.width,r.height,r.pageWidth??null,r.pageHeight??null]:null;
export const excerptKey=c=>JSON.stringify([c.documentId,c.kind||'text',c.kind==='media'?c.recordingKey:null,c.kind==='media'?c.timeStart:c.start,c.kind==='media'?c.timeEnd:c.end,geometry(c.region)]);
export function matchesAttribute(value,target,operator='eq'){if(operator==='eq')return String(value??'')===String(target??'');if(operator==='neq')return String(value??'')!==String(target??'');if(value==null||target==null||String(target).trim()==='')return false;let a,b;if(typeof value==='number'){a=value;b=Number(target);if(!Number.isFinite(b))return false;}else if(/^\d{4}-\d{2}-\d{2}$/.test(String(value))&&/^\d{4}-\d{2}-\d{2}$/.test(String(target))){a=String(value);b=String(target);}else return false;return operator==='gt'?a>b:operator==='gte'?a>=b:operator==='lt'?a<b:operator==='lte'?a<=b:false;}
export function scopedCodings(s,f={}){const ids=f.codeId?descendants(s,f.codeId):null,which=s.cases?.find(c=>c.id===f.caseId);return s.codings.filter(c=>s.documents.some(d=>d.id===c.documentId&&d.sourceRole!=='reference'&&!(d.reviewFlags||[]).some(f=>intersects(f,c)))&&!c.deletedAt&&c.status!=='needs_review'&&(!f.sourceId||c.documentId===f.sourceId)&&(!f.coder||c.coder===f.coder)&&(!f.status||f.status==='all'||c.status===f.status)&&(!ids||ids.has(c.codeId))&&(!f.caseId||(which&&caseIncludes(which,c)))&&(!f.text||String(c.text||'').toLocaleLowerCase().includes(f.text.toLocaleLowerCase()))&&(!f.attribute||matchesAttribute(s.documents.find(d=>d.id===c.documentId)?.attributes?.[f.attribute],f.attributeValue,f.attributeOperator)));}
export function unionLength(spans){let total=0,last=-Infinity;for(const [a,b] of spans.filter(([a,b])=>Number.isFinite(a)&&Number.isFinite(b)&&b>a).sort((x,y)=>x[0]-y[0])){total+=Math.max(0,b-Math.max(a,last));last=Math.max(last,b);}return total;}
export const MEASURES={applications:'Code applications',excerpts:'Distinct excerpts',characters:'Text coverage (codepoints)',seconds:'Recording coverage (seconds)',area:'Image / PDF selection area (%)'};
export function measure(s,rows,mode='applications'){if(mode==='applications')return rows.length;if(mode==='excerpts')return new Set(rows.map(excerptKey)).size;if(mode==='characters'||mode==='seconds'){const groups=new Map();for(const c of rows){const doc=s.documents.find(d=>d.id===c.documentId);if(mode==='characters'&&c.kind)continue;if(mode==='seconds'&&(c.kind!=='media'||!c.recordingKey||doc?.mediaKey!==c.recordingKey))continue;const k=mode==='seconds'?c.documentId+':'+c.recordingKey:c.documentId;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(mode==='seconds'?[c.timeStart,c.timeEnd]:[c.start,c.end]);}return [...groups.values()].reduce((n,v)=>n+unionLength(v),0);}if(mode==='area'){const unique=[...new Map(rows.filter(c=>['image','pdf'].includes(c.kind)&&c.region).map(c=>[excerptKey(c),c])).values()];return unique.reduce((n,c)=>{const r=c.region;return n+100*r.width*r.height/(c.kind==='pdf'?r.pageWidth*r.pageHeight:1);},0);}throw Error('Unknown analysis measure.');}
export function codeRows(s,mode='subtree'){if(mode==='categories')return (s.categories||[]).map(c=>({...c,codeIds:new Set(s.codes.filter(k=>descendants({codes:s.categories||[]},c.id).has(k.categoryId)).map(k=>k.id))}));if(mode==='all')return [{id:'all',name:'All codes',color:'#537a92',codeIds:new Set(s.codes.map(c=>c.id))}];return s.codes.map(c=>({...c,codeIds:mode==='direct'?new Set([c.id]):descendants(s,c.id)}));}
export function analysisMatrix(s,rows,{rowMode='subtree',group='source',metric='applications'}={}){const attribute=group.startsWith('attribute:')?group.slice(10):null,cols=attribute?[...new Set((s.cases||[]).map(c=>c.attributes?.[attribute]).filter(v=>v!==null&&v!==undefined))].map(v=>({id:String(v),name:String(v),cases:s.cases.filter(c=>c.attributes?.[attribute]===v)})):group==='case'?(s.cases||[]):s.documents;const result=codeRows(s,rowMode).map(code=>{const applications=rows.filter(c=>code.codeIds.has(c.codeId));return {...code,applications,total:measure(s,applications,metric),cells:cols.map(col=>{const list=applications.filter(c=>attribute?col.cases.some(k=>caseIncludes(k,c)):group==='case'?caseIncludes(col,c):c.documentId===col.id);return {id:col.id,name:col.name,rows:list,value:measure(s,list,metric)};})};});return {rows:result,columns:cols,total:measure(s,rows,metric)};}
function extent(c){return c.kind==='media'?[c.timeStart,c.timeEnd]:!c.kind?[c.start,c.end]:null;}
export function relates(a,b,operator='overlap',near=200){if(a.id===b.id||a.documentId!==b.documentId||(a.kind||'text')!==(b.kind||'text'))return false;if(operator==='same-source')return true;if(a.kind==='media'&&(!a.recordingKey||a.recordingKey!==b.recordingKey))return false;if(['image','pdf'].includes(a.kind)){if(operator==='exact')return JSON.stringify(geometry(a.region))===JSON.stringify(geometry(b.region));return false;}const x=extent(a),y=extent(b);if(!x||!y)return false;const [p,q]=x,[r,t]=y;switch(operator){case 'exact':return p===r&&q===t;case 'contains':return p<=r&&q>=t;case 'touch':return q===r||t===p;case 'near':return Math.max(0,Math.max(p,r)-Math.min(q,t))<=near;default:return Math.max(p,r)<Math.min(q,t);}}
export function codeRelations(s,rows,operator='overlap',near=200){const codes=s.codes.filter(c=>rows.some(r=>r.codeId===c.id)),out=[];for(let i=0;i<codes.length;i++)for(let j=operator==='contains'?0:i+1;j<codes.length;j++){if(i===j)continue;const left=rows.filter(c=>c.codeId===codes[i].id),right=rows.filter(c=>c.codeId===codes[j].id),pairs=[];for(const a of left)for(const b of right)if(relates(a,b,operator,near))pairs.push([a,b]);if(pairs.length)out.push({a:codes[i],b:codes[j],pairs,count:pairs.length});}return out;}
const STOP={en:'a an and are as at be but by for from has have he her his i in is it its of on or our she that the their them there they this to was we were what when which who will with you your',fr:'à au aux avec ce ces dans de des du elle en et eux il je la le les leur lui ma mais mes moi mon ne nos notre nous on ou par pas pour que qui sa se ses son sur ta te tes toi ton tu un une vos votre vous',es:'a al con de del el ella en es esta este la las lo los mi no o para por que se sin su sus tu un una y yo'};
export function wordTokens(text){const out=[];const re=/[\p{L}\p{N}]+(?:['’\-][\p{L}\p{N}]+)*/gu;let m,last=0,position=0;while((m=re.exec(text))){position+=Array.from(text.slice(last,m.index)).length;const start=position,end=start+Array.from(m[0]).length;out.push({word:m[0].toLocaleLowerCase(),start,end});position=end;last=re.lastIndex;}return out;}
export function words(s,docs,{language='en',custom='',n=1,min=2}={}){const stop=new Set((STOP[language]||'').split(/\s+/).concat(custom.toLocaleLowerCase().split(/[\s,;]+/))),map=new Map();for(const d of docs){const tokens=wordTokens(d.text);for(let i=0;i<=tokens.length-n;i++){const ts=tokens.slice(i,i+n);if(ts.some(t=>stop.has(t.word)||Array.from(t.word).length<min)||(d.reviewFlags||[]).some(f=>intersects(f,{start:ts[0].start,end:ts.at(-1).end})))continue;const term=ts.map(t=>t.word).join(' ');if(!map.has(term))map.set(term,{term,count:0,hits:[]});const row=map.get(term);row.count++;row.hits.push({id:d.id+':'+ts[0].start,documentId:d.id,start:ts[0].start,end:ts.at(-1).end,text:Array.from(d.text).slice(ts[0].start,ts.at(-1).end).join('')});}}return [...map.values()].sort((a,b)=>b.count-a.count||a.term.localeCompare(b.term));}
export function reportRows(s,rows){const header=['Source','Source ID','Source revision','Code','Code ID','Coder','Decision','Selection kind','Start (codepoint)','End (codepoint)','Quotation','Coding memo','Recording key','Start (seconds)','End (seconds)','Timing basis','Alignment status','Cases','Source attributes','Region geometry (JSON)','Source media type'];return [header,...rows.filter(c=>s.documents.some(d=>d.id===c.documentId&&d.sourceRole!=='reference'&&!(d.reviewFlags||[]).some(f=>intersects(f,c)))).map(c=>{const d=s.documents.find(d=>d.id===c.documentId),turns=(d?.turns||[]).filter(t=>t.anchorStatus!=='needs_review'&&intersects(t,c)),timed=turns.filter(t=>Number.isFinite(t.timeStart)&&Number.isFinite(t.timeEnd));return [d?.name,c.documentId,d?.revision,s.codes.find(k=>k.id===c.codeId)?.name,c.codeId,c.coder,c.status,c.kind||'text',c.start,c.end,c.text,c.memo,c.recordingKey||d?.alignment?.recordingKey||'',c.kind==='media'?c.timeStart:timed[0]?.timeStart,c.kind==='media'?c.timeEnd:timed.at(-1)?.timeEnd,c.kind==='media'?'Coded recording range':timed.length?'Supplied overlapping turn bounds; no interpolation':'Not supplied',d?.alignment?.status||'unbound',(s.cases||[]).filter(k=>caseIncludes(k,c)).map(k=>k.name).join('; '),JSON.stringify(d?.attributes||{}),c.region?JSON.stringify(c.region):'',d?.mediaType||''];})];}
