import {memoReferenceMetadata} from './memo-references.mjs';
import {applyAutocodingOperation,validateSuggestionCandidate} from './autocoding.mjs';
import {applyResultQueryOperation} from './query-result-operations.mjs';
import {normalizeDiarization,correctSpeakers} from './speaker-tracks.mjs';
import {normalizeTeamPolicy} from './team-policy.mjs';
import {comparisonScope,compareCodingPair} from './coder-comparison.mjs';
import {importCodeDefinitions} from './codebook-import.mjs';
import {queryRangeRelated} from './query-kind-guards.mjs';
import {applyResearchOperation,validateResearchState,attributesFor,remapCode} from './research-operations.mjs';
import {citationCurrent,validateAnalysisMemo} from './analysis-memos.mjs';
import {snapshotSource,alignmentFor,hasTiming} from './transcript-alignment.mjs';
import {addReviewTasks,decideReviewTask,reanchorReviewTask} from './processing-domain.mjs';
export const uid = () => crypto.randomUUID();
export const cp = text => Array.from(text);
export const slice = (text,start,end) => cp(text).slice(start,end).join('');
export function emptyState(name='Untitled study') {return {name,protocol:'generic',documents:[],codes:[],categories:[],codings:[],cases:[],memos:[],journals:[],extractions:[],coverage:[],suggestions:[],settings:{aiEndpoint:'',aiModel:'',audioEndpoint:''}};}
export function validateState(s) {
 if(!s||!Array.isArray(s.documents)||!Array.isArray(s.codes)||!Array.isArray(s.codings))throw Error('Invalid project archive.');
 normalizeTeamPolicy(s.settings?.teamAccess);
 const ids=a=>{const keys=a.map(x=>String(x.id));if(new Set(keys).size!==keys.length)throw Error('Duplicate record identifiers.');};
 for(const key of ['documents','codes','codings']) ids(s[key]);
 const docs=new Map(s.documents.map(d=>[String(d.id),d])),codes=new Map(s.codes.map(c=>[String(c.id),c]));
 for(const d of s.documents){if(typeof d.text!=='string'||d.text.length>2000000)throw Error('Source text is missing or too large.');if(d.direction!==undefined&&!['auto','ltr','rtl'].includes(d.direction))throw Error('Invalid source text direction.');}
 for(const c of s.codes){let n=c;const seen=new Set();while(n?.parentId){if(seen.has(String(n.id)))throw Error('Code hierarchy contains a cycle.');seen.add(String(n.id));n=codes.get(String(n.parentId));if(!n)throw Error('Missing parent code.');}}
 for(const c of s.codings){const d=docs.get(String(c.documentId));if(!d||!codes.has(String(c.codeId)))throw Error('A coding refers to a missing source or code.');if(!c.deletedAt&&c.status!=='needs_review'&&c.kind!=='image'&&c.kind!=='media'&&c.kind!=='pdf'&&(!Number.isInteger(c.start)||!Number.isInteger(c.end)||c.start<0||c.end<=c.start||c.end>cp(d.text).length||slice(d.text,c.start,c.end)!==c.text))throw Error('A quotation does not match its source. Review the import anchors.');}
 validateResearchState(s);return true;
}
export function protocolIssues(s){const out=[],groups=new Map();for(const c of s.codings.filter(c=>!c.deletedAt&&c.status!=='needs_review'&&c.kind!=='image'&&c.kind!=='media'&&c.kind!=='pdf')){const key=[c.documentId,c.start,c.end,c.coder].join(':');if(!groups.has(key))groups.set(key,[]);groups.get(key).push(c);}
 for(const cs of groups.values()){const names=cs.map(c=>s.codes.find(k=>k.id===c.codeId)?.name||'');const substantive=names.some(n=>/^(0[1-9]|10)\./.test(n));if(substantive&&s.protocol==='nhhr'){const e=names.filter(n=>/^E[1-4]\b/.test(n)),st=names.filter(n=>/^S[1-5]\b/.test(n));if(e.length!==1||st.length!==1)out.push({type:'protocol',coding:cs[0],message:'A substantive claim needs exactly one evidence grade and one stance.'});}for(const c of cs.filter(c=>(s.codes.find(k=>k.id===c.codeId)?.name||'').startsWith('CB.')))if(!s.extractions?.some(x=>x.codingId===c.id&&String(x.value??'').trim()))out.push({type:'extraction',coding:c,message:'Cost-benefit claim needs an extraction row.'});}
 for(const c of s.codings.filter(c=>!c.deletedAt&&c.status==='needs_review'))out.push({type:'anchor',coding:c,message:'Transcript changed across this quotation. Review its anchor.'});return out;
}
export function reviseDocument(s,id,newText,actor){const d=s.documents.find(x=>x.id===id);if(!d)throw Error('Source not found.');if(d.text===newText)return;const old=cp(d.text),next=cp(newText);let a=0;while(a<old.length&&a<next.length&&old[a]===next[a])a++;let b=0;while(b<old.length-a&&b<next.length-a&&old[old.length-1-b]===next[next.length-1-b])b++;const oldEnd=old.length-b,delta=next.length-old.length;snapshotSource(d,actor);for(const c of s.codings.filter(c=>c.documentId===id&&c.kind!=='image'&&c.kind!=='media'&&c.kind!=='pdf'&&c.status!=='needs_review')){if(c.end<=a){c.sourceRevision=(d.revision||1)+1;continue;}if(c.start>=oldEnd){c.start+=delta;c.end+=delta;c.sourceRevision=(d.revision||1)+1;}else{c.status='needs_review';c.sourceRevision=d.revision||1;}}for(const t of d.turns||[]){if(t.end<=a)continue;if(t.anchorStatus==='needs_review')continue;if(t.start>=oldEnd){t.start+=delta;t.end+=delta;}else{t.timingStatus='needs_review';t.anchorStatus='needs_review';t.originalStart??=t.start;t.originalEnd??=t.end;t.end=Math.max(t.start,t.end+delta);}}for(const f of d.reviewFlags||[]){if(f.end<=a)continue;if(f.start>=oldEnd){f.start+=delta;f.end+=delta;}else{f.start=Math.min(f.start,a);f.end=Math.max(f.start,f.end>=oldEnd?f.end+delta:next.length-b);f.anchorStatus='needs_review';}}d.text=newText;d.attributes??={};if('Transcript reviewed' in d.attributes)d.attributes['Transcript reviewed']='Pending';d.reviewStatus='Pending';d.revision=(d.revision||1)+1;for(const t of [...(s.reviewTasks||[]),...(s.reviewTasks||[]).flatMap(t=>t.relatedEvidence||[]),...(s.readingProgress||[])].filter(t=>t.documentId===id)){if(t.anchorStatus==='needs_review')continue;if(t.end<=a){t.sourceRevision=d.revision;continue;}if(t.start>=oldEnd){t.start+=delta;t.end+=delta;t.sourceRevision=d.revision;}else t.anchorStatus='needs_review';}for(const m of [...s.memos,...(s.passagePins||[]),...(s.cases||[]).flatMap(c=>c.passages||[]),...(s.passageLinks||[]).flatMap(l=>[l.from,l.to])].filter(m=>m.documentId===id&&m.start!=null)){if(m.anchorStatus==='needs_review')continue;if(m.end<=a){m.sourceRevision=d.revision;continue;}if(m.start>=oldEnd){m.start+=delta;m.end+=delta;m.sourceRevision=d.revision;}else m.anchorStatus='needs_review';}}
export function applyOperation(original,op,actor,role='owner'){const s=structuredClone(original);s.memos??=[];s.extractions??=[];s.coverage??=[];s.suggestions??=[];const isReviewer=['owner','reviewer'].includes(role);if(role==='viewer')throw Error('Read-only project access.');const data=structuredClone(op.data||{});
 switch(op.type){
 case 'permissions.update':if(role!=='owner')throw Error('Only the owner can configure project permissions.');s.settings={...s.settings,teamAccess:normalizeTeamPolicy(data)};break;
 case 'codebook.import':importCodeDefinitions(s,data.codes,uid);break;
 case 'code.create':s.codes.push({id:uid(),name:String(data.name||'').trim(),description:data.description||'',color:data.color||'#537a92',parentId:data.parentId||null,categoryId:data.categoryId||null,codable:data.codable!==false});if(!s.codes.at(-1).name)throw Error('A code name is required.');break;
 case 'code.update':{const c=s.codes.find(x=>x.id===data.id);if(!c)throw Error('Code not found.');if(data.description!==undefined&&data.description!==c.description){c.definitionHistory??=[];c.definitionHistory.push({description:c.description,review:structuredClone(c.definitionReview||null),actor,date:new Date().toISOString()});delete c.definitionReview;}Object.assign(c,{name:data.name??c.name,description:data.description??c.description,parentId:data.parentId===undefined?c.parentId:data.parentId,color:data.color??c.color,categoryId:data.categoryId===undefined?c.categoryId:data.categoryId});break;}
 case 'code.merge':{if(!isReviewer)throw Error('Reviewer access required.');if(data.from===data.into)throw Error('Select two different codes.');if(!s.codes.some(x=>x.id===data.into))throw Error('Target code is missing.');s.codings.forEach(c=>{if(c.codeId===data.from)c.codeId=data.into;});s.codes.forEach(c=>{if(c.parentId===data.from)c.parentId=data.into;});remapCode(s,data.from,data.into);for(const set of s.codeSets||[])set.codeIds=[...new Set(set.codeIds.map(id=>id===data.from?data.into:id))];s.codeMerges??=[];s.codeMerges.push({from:structuredClone(s.codes.find(c=>c.id===data.from)),into:data.into,actor,date:new Date().toISOString()});s.codes=s.codes.filter(c=>c.id!==data.from);break;}
 case 'coding.create':{const d=s.documents.find(x=>x.id===data.documentId);if(!d)throw Error('Source missing.');const text=data.kind==='image'||data.kind==='media'||data.kind==='pdf'?(data.text||'Media selection'):slice(d.text,data.start,data.end);if(!text)throw Error('Select a passage first.');if(data.kind==='media'&&(!(data.timeStart>=0)||!(data.timeEnd>data.timeStart)))throw Error('Enter a valid time range.');if(data.kind==='pdf'){const r=data.region;if(d.mediaType!=='application/pdf'||!r||!Number.isInteger(r.page)||r.page<1||![r.x,r.y,r.width,r.height,r.pageWidth,r.pageHeight].every(Number.isFinite)||r.x<0||r.y<0||r.width<=0||r.height<=0||r.x+r.width>r.pageWidth+.01||r.y+r.height>r.pageHeight+.01)throw Error('Choose a valid region inside a PDF page.');}for(const codeId of data.codeIds||[]){if(!s.codes.some(x=>x.id===codeId&&x.codable!==false))throw Error('Unknown code.');if(s.codings.some(c=>c.documentId===d.id&&c.codeId===codeId&&c.start===data.start&&c.end===data.end&&!c.deletedAt&&c.coder===actor&&c.kind===data.kind&&(data.kind!=='media'||(c.timeStart===data.timeStart&&c.timeEnd===data.timeEnd))&&(!['image','pdf'].includes(data.kind)||JSON.stringify(c.region)===JSON.stringify(data.region))))continue;s.codings.push({id:uid(),documentId:d.id,codeId,start:data.start,end:data.end,text,coder:actor,date:new Date().toISOString(),status:'coded',memo:data.memo||'',sourceRevision:d.revision||1,...(data.kind?{kind:data.kind,timeStart:data.timeStart,timeEnd:data.timeEnd,recordingKey:data.kind==='media'?d.mediaKey:undefined,mediaKey:['image','pdf'].includes(data.kind)?d.mediaKey:undefined,region:data.region}: {})});}break;}
 case 'coding.delete':{const c=s.codings.find(c=>c.id===data.id);if(!c)throw Error('Coding missing.');if(c.coder!==actor&&!isReviewer)throw Error('Only a reviewer may remove another coder’s decision.');c.deletedAt=new Date().toISOString();c.deletedBy=actor;break;}
 case 'coding.resolve':{if(!isReviewer)throw Error('Reviewer access required.');const c=s.codings.find(x=>x.id===data.id),d=s.documents.find(x=>x.id===c?.documentId);if(!c||!d)throw Error('Coding missing.');Object.assign(c,{start:data.start,end:data.end,text:slice(d.text,data.start,data.end),status:'coded',sourceRevision:d.revision,reviewer:actor});break;}
 case 'coding.review':{if(!isReviewer)throw Error('Reviewer access required.');for(const id of data.ids||[]){const c=s.codings.find(x=>x.id===id);if(c&&c.status!=='needs_review'){if(data.status==='accepted'&&s.protocol==='nhhr'&&protocolIssues(s).some(i=>i.type==='protocol'&&i.coding.documentId===c.documentId&&i.coding.start===c.start&&i.coding.end===c.end&&i.coding.coder===c.coder))throw Error('Resolve evidence and stance checks before accepting this claim.');c.status=data.status==='accepted'?'accepted':'flagged';c.reviews??=[];c.reviews.push({reviewer:actor,status:data.status,note:data.note||'',date:new Date().toISOString()});c.reviewNote=data.note||'';c.reviewer=actor;}}break;}
 case 'source.import':{const sourceId=uid(),diarization=data.diarization?normalizeDiarization({...data.diarization,importedSourceId:data.diarization.sourceId,sourceId}):null;s.documents.push({id:sourceId,name:data.name,text:data.text||'',direction:data.direction||'auto',importProvenance:structuredClone(data.importProvenance||null),ocr:structuredClone(data.ocr||null),reviewStatus:data.reviewStatus||'Pending',revision:1,sourceRole:data.sourceRole==='reference'?'reference':'interview',attributes:data.attributes||{},turns:structuredClone(data.turns||[]),transcriptMetadata:structuredClone(data.transcriptMetadata||null),transcription:structuredClone(data.transcription||null),alignment:data.alignment||{recordingKey:null,status:'unbound',units:'seconds'},speakerMappings:data.speakerMappings||[],diarization,pages:data.pages||[],mediaKey:data.mediaKey||null,mediaType:data.mediaType||null,mediaWidth:data.mediaWidth,mediaHeight:data.mediaHeight,excludeAI:!!data.excludeAI,versions:structuredClone(data.versions||[])});break;}
 case 'source.revise':if(!isReviewer)throw Error('Reviewer access required.');reviseDocument(s,data.id,data.text,actor);break;
 case 'source.media.attach':{const d=s.documents.find(x=>x.id===data.id);if(!d)throw Error('Source missing.');if(d.mediaKey!==data.mediaKey){snapshotSource(d,actor);for(const c of s.codings.filter(c=>c.documentId===d.id&&['media','image','pdf'].includes(c.kind)&&!c.deletedAt)){if(c.kind==='media')c.recordingKey??=d.mediaKey;else c.mediaKey??=d.mediaKey;c.status='needs_review';}d.alignment={...(d.alignment||alignmentFor(d)),status:hasTiming(d)?'needs_review':'untimed'};}Object.assign(d,{mediaKey:data.mediaKey,mediaType:data.mediaType,mediaWidth:data.mediaWidth,mediaHeight:data.mediaHeight});break;}
 case 'source.attributes':{const d=s.documents.find(x=>x.id===data.id);if(!d)throw Error('Source missing.');d.attributes=attributesFor(s,{...d.attributes,...data.attributes},'file');if(data.excludeAI!==undefined)d.excludeAI=!!data.excludeAI;if(data.direction!==undefined){if(!['auto','ltr','rtl'].includes(data.direction))throw Error('Choose automatic, left-to-right or right-to-left direction.');d.direction=data.direction;}break;}
 case 'source.transcript':{if(!isReviewer)throw Error('Reviewer access required.');const d=s.documents.find(x=>x.id===data.id);if(!d)throw Error('Source missing.');if(d.text===data.text){snapshotSource(d,actor);d.revision=(d.revision||1)+1;for(const a of [...(s.passagePins||[]),...(s.cases||[]).flatMap(c=>c.passages||[]),...(s.passageLinks||[]).flatMap(l=>[l.from,l.to])].filter(a=>a.documentId===d.id&&a.anchorStatus!=='needs_review'))a.sourceRevision=d.revision;}else reviseDocument(s,data.id,data.text,actor);d.attributes??={};if('Transcript reviewed' in d.attributes)d.attributes['Transcript reviewed']='Pending';d.reviewStatus='Pending';if(data.recordingKey&&data.recordingKey!==d.mediaKey)throw Error('This transcript belongs to a different recording. Its result is retained; reconnect the original recording before applying.');d.turns=structuredClone(data.turns||[]);if(data.diarization)d.diarization=normalizeDiarization(data.diarization,{sourceId:d.id,recordingKey:data.recordingKey});else if(data.speakerTracks){if(!data.jobId||!data.recordingKey)throw Error('Generated speaker tracks require their recording job.');d.diarization=normalizeDiarization({...data.speakerTracks,sourceId:d.id,recordingKey:data.recordingKey,runId:data.jobId,units:'seconds'});d.turns=d.turns.map(t=>({...t,speakerRunId:data.jobId}));}d.transcriptMetadata=structuredClone(data.transcriptMetadata||null);d.alignment=alignmentFor(d,data.recordingKey||null);d.transcription={jobId:data.jobId,model:data.model,recordingKey:data.recordingKey||null,date:new Date().toISOString(),reviewer:actor};break;}
 case 'hierarchy.apply':{if(!isReviewer)throw Error('Reviewer access required.');const seen=new Set();for(const group of data.groups||[]){if(!group.name?.trim()||!Array.isArray(group.codeIds)||group.codeIds.length<2)throw Error('Invalid hierarchy group.');const id=uid();for(const child of group.codeIds){const c=s.codes.find(c=>c.id===child);if(!c||seen.has(child))throw Error('A code occurs in more than one proposed group.');seen.add(child);c.parentId=id;}s.codes.push({id,name:group.name,description:group.reason||'',color:'#537a92',codable:false,parentId:null});}break;}
 case 'source.alignment.bind':{if(!isReviewer)throw Error('Reviewer access required.');const d=s.documents.find(x=>x.id===data.id);if(!d?.mediaKey||data.recordingKey!==d.mediaKey||!hasTiming(d)||!data.note?.trim())throw Error('Confirm the current recording matches supplied transcript times and record your verification.');snapshotSource(d,actor);d.alignment={...alignmentFor(d,d.mediaKey),reviewer:actor,note:data.note,date:new Date().toISOString()};break;}
 case 'source.speaker':{if(!isReviewer)throw Error('Reviewer access required.');const d=s.documents.find(x=>x.id===data.id);if(!d)throw Error('Source missing.');const turnIds=data.turnIds??(d.turns||[]).filter(t=>t.speaker===data.from).map(t=>t.id),corrected=correctSpeakers(d,{...data,sourceId:d.id,turnIds},actor);snapshotSource(d,actor);Object.assign(d,corrected,{versions:d.versions});break;}
 case 'source.diarization':{if(!isReviewer)throw Error('Reviewer access required.');const d=s.documents.find(x=>x.id===data.id);if(!d)throw Error('Source missing.');if(!d.mediaKey||!/^(audio|video)\//u.test(d.mediaType||''))throw Error('Attach the current audio/video recording before importing speaker tracks.');const input=data.diarization,same=d.diarization?.runId===input?.runId&&d.diarization?.recordingKey===d.mediaKey,track=input?.provenance?.track,merged=same&&['regular','exclusive'].includes(track)?{...d.diarization,...input,[track==='regular'?'exclusive':'regular']:d.diarization[track==='regular'?'exclusive':'regular'],history:[...(d.diarization.history||[]),...(input.history||[])]}:input;const run=normalizeDiarization(merged,{sourceId:d.id,recordingKey:d.mediaKey});snapshotSource(d,actor);d.diarization=run;break;}
 case 'memo.save':{data.references=memoReferenceMetadata(s,data.content??s.memos.find(m=>m.id===data.id)?.content??'',actor,role);if(data.caseId&&!s.cases.some(c=>c.id===data.caseId))throw Error('Linked memo case is missing.');if(data.origin==='theme-reading-sheet')validateAnalysisMemo(s,data);if(data.origin==='ai-reviewed'&&(!data.title?.trim()||!data.content?.trim()||!Array.isArray(data.citations)||!data.citations.length||data.citations.some(c=>!citationCurrent(s,c))))throw Error('AI memo citations changed or need consent review. Re-run or select current evidence.');const prior=s.memos.find(x=>x.id===data.id);const m={...prior,...data,versions:[...(prior?.versions||[]),...(prior?[{...prior,versions:undefined}]:[])],id:data.id||uid(),author:prior?.author||actor,modifiedBy:actor,date:prior?.date||new Date().toISOString(),modifiedAt:new Date().toISOString()};const idx=s.memos.findIndex(x=>x.id===m.id);if(idx>=0){if(s.memos[idx].author!==actor&&!isReviewer)throw Error('Cannot edit another coder’s memo.');s.memos[idx]=m;}else s.memos.push(m);break;}
 case 'case.save':{const c={...s.cases.find(x=>x.id===data.id),...data,id:data.id||uid(),name:data.name,documentIds:data.documentIds||[],attributes:attributesFor(s,data.attributes||{},'case')};const idx=s.cases.findIndex(x=>x.id===c.id);if(idx>=0)s.cases[idx]=c;else s.cases.push(c);break;}
 case 'extraction.save':{if(!String(data.value??'').trim())throw Error('Record a value or stated estimate before saving the extraction.');if(!s.codings.some(c=>c.id===data.codingId&&!c.deletedAt))throw Error('Choose an existing code application for extraction.');const x={...data,id:data.id||uid(),author:actor};const idx=s.extractions.findIndex(row=>row.id===x.id);if(idx>=0)s.extractions[idx]=x;else s.extractions.push(x);break;}
 case 'coverage.save':{const key=data.documentId+':'+data.module;s.coverage=s.coverage.filter(x=>x.documentId+':'+x.module!==key);s.coverage.push({...data,actor});break;}
 case 'consensus.save':{if(!isReviewer)throw Error('Reviewer access required.');const d=s.documents.find(x=>x.id===data.documentId);if(!d||!Number.isInteger(data.start)||!Number.isInteger(data.end)||data.start<0||data.end<=data.start||data.end>cp(d.text).length||slice(d.text,data.start,data.end)!==data.text||(data.codeIds||[]).some(id=>!s.codes.some(c=>c.id===id&&c.codable!==false)))throw Error('Consensus quotation does not match the current source.');if(!data.reason?.trim())throw Error('Record the reasoning for the consensus decision.');s.consensus??=[];s.consensus.push({...data,id:uid(),reviewer:actor,date:new Date().toISOString(),sourceRevision:d.revision});break;}
 case 'settings.save':if(Object.hasOwn(data,'teamAccess'))throw Error('Use the owner permissions control to change team access.');if(!isReviewer)throw Error('Reviewer access required.');s.settings={...s.settings,...data};break;
 case 'protocol.set':if(!isReviewer)throw Error('Reviewer access required.');s.protocol=data.protocol;break;
 case 'reviewTasks.add':addReviewTasks(s,data,actor);break;
 case 'reviewTask.decide':decideReviewTask(s,data,actor,role,uid,protocolIssues);break;
 case 'reviewTask.reanchor':reanchorReviewTask(s,data,actor,role);break;
 case 'reading.mark':{const d=s.documents.find(d=>d.id===data.documentId);if(!d||!Number.isInteger(data.start)||!Number.isInteger(data.end)||data.start<0||data.end<=data.start||data.end>cp(d.text).length||!['read','deferred'].includes(data.status))throw Error('Choose a valid source range and reading status.');s.readingProgress??=[];const key=[data.documentId,data.start,data.end,actor].join(':');s.readingProgress=s.readingProgress.filter(t=>t.id!==key);s.readingProgress.push({id:key,documentId:d.id,start:data.start,end:data.end,text:slice(d.text,data.start,data.end),status:data.status,sourceRevision:d.revision,actor,date:new Date().toISOString()});break;}
 case 'query.save':{s.savedQueries??=[];if(!data.name?.trim())throw Error('Name this reading query.');const q={id:uid(),name:data.name,author:actor,date:new Date().toISOString(),spec:{codeA:data.spec?.codeA||'',codeB:data.spec?.codeB||'',operator:['and','or','not','near'].includes(data.spec?.operator)?data.spec.operator:'and',near:Math.max(0,Math.min(100000,Number(data.spec?.near)||0)),source:data.spec?.source||'',coder:data.spec?.coder||'',text:data.spec?.text||'',status:data.spec?.status||'all'}};s.savedQueries.push(q);break;}
 case 'query.delete':{const q=s.savedQueries?.find(q=>q.id===data.id);if(q&&q.author!==actor&&!isReviewer)throw Error('Cannot delete another researcher’s query.');s.savedQueries=(s.savedQueries||[]).filter(q=>q.id!==data.id);break;}
 case 'suggestions.add':{if(!Array.isArray(data.suggestions)||data.suggestions.length>1000)throw Error('Invalid suggestion list.');for(const x of data.suggestions){validateSuggestionCandidate(s,x);if(s.suggestions.some(y=>y.status==='pending'&&y.documentId===x.documentId&&y.codeId===x.codeId&&y.start===x.start&&y.end===x.end))continue;s.suggestions.push({...x,id:uid(),status:'pending',createdBy:actor});}break;}
 case 'suggestion.dismiss':{const x=s.suggestions.find(x=>x.id===data.id);if(x){x.status='dismissed';x.reviewedBy=actor;}break;}
 case 'suggestion.accept':{const x=s.suggestions.find(x=>x.id===data.id);if(!x)throw Error('Suggestion missing.');if(x.status!=='pending')throw Error('This suggestion has already been reviewed.');validateSuggestionCandidate(s,x);const d=s.documents.find(xd=>xd.id===x.documentId);if(!d||(d.revision||1)!==x.sourceRevision||slice(d.text,x.start,x.end)!==x.text)throw Error('Suggestion anchor is stale.');s.codings.push({id:uid(),documentId:x.documentId,codeId:x.codeId,start:x.start,end:x.end,text:x.text,coder:actor,date:new Date().toISOString(),status:'coded',sourceRevision:d.revision,origin:'ai-reviewed'});x.status='accepted';x.reviewedBy=actor;break;}
 default:if(!applyAutocodingOperation(s,op,actor,role,{uid})&&!applyResultQueryOperation(s,op,actor,role,{uid})&&!applyResearchOperation(s,op,actor,role,{uid,queryCodings}))throw Error('Unknown operation.');}
 validateState(s);return s;
}
export function queryCodings(s,{codeA='',codeB='',operator='and',source='',coder='',text='',near=200,status='all'}={}){const active=s.codings.filter(c=>!c.deletedAt&&c.status!=='needs_review'&&(status==='all'||c.status===status)&&(!source||c.documentId===source)&&(!coder||c.coder===coder)&&(!text||c.text.toLowerCase().includes(text.toLowerCase())));if(!codeA)return active;const descend=id=>{const set=new Set([id]);let last=0;while(last!==set.size){last=set.size;for(const c of s.codes)if(set.has(c.parentId))set.add(c.id);}return set;};const a=descend(codeA),b=descend(codeB);const left=active.filter(c=>a.has(c.codeId));if(!codeB)return left;const right=active.filter(c=>b.has(c.codeId));if(operator==='or')return active.filter(c=>a.has(c.codeId)||b.has(c.codeId));return left.filter(x=>{const hit=right.some(y=>queryRangeRelated(x,y,operator,near));return operator==='not'?!hit:hit;});}
export function agreement(s,a,b){s={...s,...comparisonScope(s)};const values=new Map();for(const c of s.codings.filter(c=>!c.deletedAt&&(c.coder===a||c.coder===b))){if(c.status==='needs_review'||c.kind)continue;const key=[c.documentId,c.start,c.end].join(':');if(!values.has(key))values.set(key,[new Set(),new Set()]);values.get(key)[c.coder===a?0:1].add(c.codeId);}let agreed=0;for(const [x,y]of values.values())if(x.size===y.size&&[...x].every(k=>y.has(k)))agreed++;return {units:values.size,agreed,percent:values.size?100*agreed/values.size:null,method:'Exact-span code-set agreement. Different segment boundaries count as disagreements; this is not Cohen’s kappa.'};}
export function characterKappa(s,a,b,codeId,documentId=''){const result=compareCodingPair(s,a,b,{codeId,sourceId:documentId}),row=result.byCode[0];return {...row,method:result.method+' '+result.scope.method};}
