import {isSQLite,readNativeProject} from './native-project-import.mjs';
import {zipSync,unzipSync,strToU8,strFromU8} from 'fflate';
import initSqlJs from 'sql.js';
import wasm from 'sql.js/dist/sql-wasm.wasm?url';
import mammoth from 'mammoth/mammoth.browser';
import {timestampedTranscript} from './transcript.mjs';
import {readTextDocument} from './source-text-import.mjs';
import {importRefi} from './refi-import.mjs';
import {normalizeQualCoder,qualCoderTables} from './qualcoder-import.mjs';
import {emptyState,validateState,uid,cp} from './domain.mjs';
const xmlEsc=s=>String(s??'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));
export function download(name,content,type='application/json'){const blob=content instanceof Blob?content:new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function csv(rows){return rows.map(row=>row.map(value=>'"'+String(value??'').replaceAll('"','""')+'"').join(',')).join('\r\n');}
export function exportCSV(s){const map=new Map(s.codes.map(c=>[c.id,c])),docs=new Map(s.documents.map(d=>[d.id,d]));return csv([['Source','Code','Coder','Start (codepoint)','End (codepoint)','Quotation','Status','Memo','Selection kind','Recording key','Start (seconds)','End (seconds)','Alignment status'],...s.codings.filter(c=>!c.deletedAt).map(c=>[docs.get(c.documentId)?.name,map.get(c.codeId)?.name,c.coder,c.start,c.end,c.text,c.status,c.memo,c.kind||'text',c.recordingKey||docs.get(c.documentId)?.mediaKey||'',c.kind==='media'?c.timeStart:'',c.kind==='media'?c.timeEnd:'',docs.get(c.documentId)?.alignment?.status||'unbound'])]);}
export {exportQDC,exportQDPX} from './refi.mjs';
function parseXML(str){const doc=new DOMParser().parseFromString(str,'application/xml');if(doc.querySelector('parsererror'))throw Error('Invalid XML project.');return doc;}
function parseCodes(doc){const codes=[];for(const el of doc.getElementsByTagNameNS('*','Code')){const parent=el.parentElement?.localName==='Code'?el.parentElement.getAttribute('guid'):null;codes.push({id:el.getAttribute('guid')||uid(),name:el.getAttribute('name')||'Unnamed code',parentId:parent,description:[...el.children].find(x=>x.localName==='Description')?.textContent||'',codable:el.getAttribute('isCodable')!=='false',color:el.getAttribute('color')||'#4e7b91'});}return codes;}
async function sqliteProject(bytes,options={}){const SQL=await initSqlJs({locateFile:()=>wasm}),db=new SQL.Database(bytes);try{const names=db.exec("SELECT name FROM sqlite_master WHERE type='table'")[0]?.values.flat()||[];if(['project','document','code','coding'].every(n=>names.includes(n))||['projects','documents','tags','highlights'].every(n=>names.includes(n))||['project','source','freecode','coding'].every(n=>names.includes(n)))return readNativeProject(db,options);}finally{db.close();}return qualcoder(bytes);}
async function qualcoder(bytes){const SQL=await initSqlJs({locateFile:()=>wasm}),db=new SQL.Database(bytes);try{const names=db.exec("SELECT name FROM sqlite_master WHERE type='table'")[0]?.values.flat()||[];if(['source','code_name','code_text'].some(n=>!names.includes(n)))throw Error('This SQLite file is missing required QualCoder source and coding tables.');for(const [table,required] of Object.entries({source:['id','name','fulltext'],code_name:['cid','name'],code_text:['ctid','cid','fid','pos0','pos1','seltext']})){const columns=db.exec('PRAGMA table_info('+table+')')[0]?.values.map(r=>r[1])||[];if(required.some(c=>!columns.includes(c)))throw Error('Invalid QualCoder '+table+' table schema.');}const tables={};for(const table of qualCoderTables){try{const r=db.exec('SELECT * FROM '+table);tables[table]=r[0]?r[0].values.map(v=>Object.fromEntries(r[0].columns.map((k,i)=>[k,v[i]]))):[];}catch{tables[table]=[];}}return normalizeQualCoder(tables);}finally{db.close();}}
export async function importProject(file,options={}){const bytes=new Uint8Array(await file.arrayBuffer());if(isSQLite(bytes))return sqliteProject(bytes,options);if(file.name.endsWith('.json')){const x=JSON.parse(strFromU8(bytes));const s=x.state||x;validateState(s);return s;}const z=unzipSync(bytes);if(z['research-weave.json']){const s=JSON.parse(strFromU8(z['research-weave.json'])).state;const manifest=z['research-weave-media.json']?JSON.parse(strFromU8(z['research-weave-media.json'])):{};s._mediaFiles=Object.entries(manifest).filter(([id,m])=>z[m.path]).map(([documentId,m])=>({documentId,bytes:z[m.path],name:m.path.split('/').at(-1),type:m.type,width:m.width,height:m.height}));for(const d of s.documents)if(d.mediaKey)d.mediaKey=null;validateState(s);return s;}const qda=Object.keys(z).find(k=>(k==='data.qda'||k.endsWith('/data.qda'))&&!k.startsWith('__MACOSX/'));if(qda)return sqliteProject(z[qda],options);const nested=Object.keys(z).find(k=>k.endsWith('QualCoder_Project.zip'));if(nested){const sub=unzipSync(z[nested]);const key=Object.keys(sub).find(k=>(k==='data.qda'||k.endsWith('/data.qda'))&&!k.startsWith('__MACOSX/'));if(key)return sqliteProject(sub[key],options);}const nativeEntries=Object.entries(z).filter(([name,data])=>!name.startsWith('__MACOSX/')&&isSQLite(data));if(nativeEntries.length>1)throw Error('This archive contains several SQLite databases. Import one database file at a time.');if(nativeEntries.length===1)return sqliteProject(nativeEntries[0][1],options);const qde=Object.keys(z).find(k=>k.endsWith('.qde'));if(!qde)throw Error('No supported project found. Use a QualCoder ZIP, QDPX, or Research Weave JSON archive.');return importRefi(strFromU8(z[qde]),z,parseCodes);}
export async function importCodebook(file){const text=await file.text();if(file.name.endsWith('.qdc')||file.name.endsWith('.xml'))return parseCodes(parseXML(text));if(file.name.endsWith('.json'))return JSON.parse(text).codes||JSON.parse(text);throw Error('Use a QDC/XML or JSON codebook.');}
export {timestampedTranscript} from './transcript.mjs';
export async function readSource(file,options={}){const plain=await readTextDocument(file,options);if(plain)return plain;const name=file.name.toLowerCase();if(name.endsWith('.docx')){const r=await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()});return {text:r.value,turns:[]};}if(name.endsWith('.json'))return timestampedTranscript(JSON.parse(await file.text()));if(name.endsWith('.srt')||name.endsWith('.vtt')){const raw=await file.text();const toSec=t=>{const p=t.replace(',','.').split(':').map(Number);return p.reduce((a,b)=>a*60+b,0);};const segments=[];for(const block of raw.replace(/^WEBVTT\s*/,'').split(/\n\s*\n/)){const l=block.trim().split('\n'),i=l.findIndex(x=>x.includes('-->'));if(i<0)continue;const [a,b]=l[i].split('-->').map(x=>x.trim().split(' ')[0]);segments.push({start:toSec(a),end:toSec(b),text:l.slice(i+1).join(' '),speaker:'Unassigned'});}return timestampedTranscript(segments);}if(name.endsWith('.pdf')){const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');const worker=await import('pdfjs-dist/legacy/build/pdf.worker.mjs');globalThis.pdfjsWorker=worker;const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),useWorkerFetch:false,isEvalSupported:false}).promise;let text='';const pages=[];for(let n=1;n<=pdf.numPages;n++){const start=cp(text).length;const page=await pdf.getPage(n),content=await page.getTextContent();text+=content.items.map(x=>x.str+(x.hasEOL?'\n':' ')).join('')+'\n';const viewport=page.getViewport({scale:1});pages.push({page:n,start,end:cp(text).length,width:viewport.width,height:viewport.height});}return {text,turns:[],pages};}if(!name.endsWith('.txt')&&!name.endsWith('.md'))throw Error('Choose a supported transcript or reference document. CSV amendments and scripts are method records, not transcripts.');return {text:await file.text(),turns:[]};}
