import {readProjectArchive,readRecoveredProjectArchive,restoreProjectMedia} from './project-archive.mjs';
import {looksLikeZip,hasEndOfCentralDirectory,recoverZipEntries} from './zip-recovery.mjs';
import {readSQLiteTable} from './sqlite-text.mjs';
import {parseCodebookEnvelope} from './codebook-envelope.mjs';
import {isSQLite,readNativeProject} from './native-project-import.mjs';
import {zipSync,unzipSync,strToU8,strFromU8} from 'fflate';
import initSqlJs from 'sql.js';
import wasm from 'sql.js/dist/sql-wasm.wasm?url';
import mammoth from 'mammoth/mammoth.browser';
import {timestampedTranscript} from './transcript.mjs';
import {docxMetadata} from './document-metadata.mjs';
import {speechTranscript} from './speech-source.mjs';
import {decodeSourceText,sourceByteProvenance,readTextDocument} from './source-text-import.mjs';
import {importRefi} from './refi-import.mjs';
import {normalizeQualCoder,qualCoderTables} from './qualcoder-import.mjs';
import {emptyState,validateState,uid,cp} from './domain.mjs';
const xmlEsc=s=>String(s??'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));
export function download(name,content,type='application/json'){const blob=content instanceof Blob?content:new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function csv(rows){return rows.map(row=>row.map(value=>'"'+String(value??'').replaceAll('"','""')+'"').join(',')).join('\r\n');}
export {exportCSV} from './coded-excerpts-export.mjs';
export {exportQDC,exportQDPX} from './refi.mjs';
function parseXML(str){const doc=new DOMParser().parseFromString(str,'application/xml');if(doc.querySelector('parsererror'))throw Error('Invalid XML project.');return doc;}
function parseCodes(doc){const codes=[];for(const el of doc.getElementsByTagNameNS('*','Code')){const parent=el.parentElement?.localName==='Code'?el.parentElement.getAttribute('guid'):null;codes.push({id:el.getAttribute('guid')||uid(),name:el.getAttribute('name')||'Unnamed code',parentId:parent,description:[...el.children].find(x=>x.localName==='Description')?.textContent||'',codable:el.getAttribute('isCodable')!=='false',color:el.getAttribute('color')||'#4e7b91'});}return codes;}
async function sqliteProject(bytes,options={}){const SQL=await initSqlJs({locateFile:()=>wasm}),db=new SQL.Database(bytes);try{const names=db.exec("SELECT name FROM sqlite_master WHERE type='table'")[0]?.values.flat()||[];if(['projects','sources','nodes','coding_references'].every(n=>names.includes(n)))throw Error('Sift QDA SQLite import is unsupported. Export REFI-QDA (.qdpx) from Sift and import that file.');if(['projects','documents','codes','segments'].every(n=>names.includes(n))||['project','document','code','coding'].every(n=>names.includes(n))||['projects','documents','tags','highlights'].every(n=>names.includes(n))||['project','source','freecode','coding'].every(n=>names.includes(n)))return readNativeProject(db,options);}finally{db.close();}return qualcoder(bytes);}
async function qualcoder(bytes){const SQL=await initSqlJs({locateFile:()=>wasm}),db=new SQL.Database(bytes);try{const names=db.exec("SELECT name FROM sqlite_master WHERE type='table'")[0]?.values.flat()||[];if(['source','code_name','code_text'].some(n=>!names.includes(n)))throw Error('This SQLite file is missing required QualCoder source and coding tables.');for(const [table,required] of Object.entries({source:['id','name','fulltext'],code_name:['cid','name'],code_text:['ctid','cid','fid','pos0','pos1','seltext']})){const columns=db.exec('PRAGMA table_info('+table+')')[0]?.values.map(r=>r[1])||[];if(required.some(c=>!columns.includes(c)))throw Error('Invalid QualCoder '+table+' table schema.');}const tables={};for(const table of qualCoderTables){try{const columns=db.exec('PRAGMA table_info("'+table+'")')[0]?.values.map(r=>r[1])||[];tables[table]=columns.length?readSQLiteTable(db,table,columns):[];}catch(error){if(!names.includes(table))tables[table]=[];else throw error;}}return normalizeQualCoder(tables);}finally{db.close();}}
function nativeArchiveState(native){const s=native.mediaFiles.length?native.state:restoreProjectMedia(native.state,{});s._mediaFiles=native.mediaFiles;if(native.warnings?.length)s._importWarnings=native.warnings;s.archiveImport={format:native.manifest.format,metadata:native.metadata,scope:'Imported metadata is reference history; access grants, jobs and server recovery are not reinstated.',...(native.recovery?{recovery:native.recovery}:{}),...(native.missingMedia?.length?{missingMedia:native.missingMedia.map(({key,path,name,byteLength})=>({key,path,name,byteLength}))}:{})};return s;}
/** `options.recordings`: separately downloaded recording Files selected with a study ZIP. */
export async function importProject(file,options={}){const bytes=new Uint8Array(await file.arrayBuffer());if(isSQLite(bytes))return sqliteProject(bytes,options);if(file.name.toLowerCase().endsWith('.json')){const x=JSON.parse(decodeSourceText(bytes).text);const s=x.state||x;validateState(s);return restoreProjectMedia(s,{});}const recordings=await Promise.all((options.recordings||[]).map(async f=>({name:f.name,bytes:new Uint8Array(await f.arrayBuffer())})));if(looksLikeZip(bytes)&&!hasEndOfCentralDirectory(bytes))return nativeArchiveState(await readRecoveredProjectArchive(recoverZipEntries(bytes),{recordings}));const z=unzipSync(bytes);const native=await readProjectArchive(z,{recordings});if(native)return nativeArchiveState(native);if(z['research-weave.json']){const s=JSON.parse(strFromU8(z['research-weave.json'])).state;const manifest=z['research-weave-media.json']?JSON.parse(strFromU8(z['research-weave-media.json'])):{};s._mediaFiles=Object.entries(manifest).filter(([id,m])=>z[m.path]).map(([documentId,m])=>({originalKey:s.documents.find(d=>d.id===documentId)?.mediaKey,documentId,bytes:z[m.path],name:m.path.split('/').at(-1),type:m.type,width:m.width,height:m.height}));if(!s._mediaFiles.length)return restoreProjectMedia(s,{});validateState(s);return s;}const qda=Object.keys(z).find(k=>(k==='data.qda'||k.endsWith('/data.qda'))&&!k.startsWith('__MACOSX/'));if(qda)return sqliteProject(z[qda],options);const nested=Object.keys(z).find(k=>k.endsWith('QualCoder_Project.zip'));if(nested){const sub=unzipSync(z[nested]);const key=Object.keys(sub).find(k=>(k==='data.qda'||k.endsWith('/data.qda'))&&!k.startsWith('__MACOSX/'));if(key)return sqliteProject(sub[key],options);}const nativeEntries=Object.entries(z).filter(([name,data])=>!name.startsWith('__MACOSX/')&&isSQLite(data));if(nativeEntries.length>1)throw Error('This archive contains several SQLite databases. Import one database file at a time.');if(nativeEntries.length===1)return sqliteProject(nativeEntries[0][1],options);const qde=Object.keys(z).find(k=>k.endsWith('.qde'));if(!qde)throw Error('No supported project found. Use a QualCoder ZIP, QDPX, or Research Weave JSON archive.');return importRefi(decodeSourceText(z[qde]).text,z,parseCodes);}
export async function importCodebook(file){const text=decodeSourceText(new Uint8Array(await file.arrayBuffer())).text,name=file.name.toLowerCase();if(name.endsWith('.qdc')||name.endsWith('.xml'))return parseCodes(parseCodebookEnvelope(text));if(name.endsWith('.json'))return JSON.parse(text).codes||JSON.parse(text);throw Error('Use a QDC/XML or JSON codebook.');}
export {timestampedTranscript} from './transcript.mjs';
export async function readSource(file,options={}){const plain=await readTextDocument(file,options);if(plain)return plain;const name=file.name.toLowerCase();if(name.endsWith('.docx')){const bytes=new Uint8Array(await file.arrayBuffer()),metadata=docxMetadata(bytes),r=await mammoth.extractRawText({arrayBuffer:bytes.buffer}),warnings=['DOCX is converted to plain text. Formatting, list markers, table-column grouping, images and original layout are omitted; supplied core document metadata is retained as provenance.',...r.messages.map(m=>m.message)];return {text:r.value,turns:[],warnings,importProvenance:await sourceByteProvenance(bytes,file,'docx',{extractor:'mammoth-raw-text',encoding:'archive-xml',documentMetadata:metadata,losses:warnings})};}if(name.endsWith('.json')){const bytes=new Uint8Array(await file.arrayBuffer()),decoded=decodeSourceText(bytes,options.encoding||'auto');return {...timestampedTranscript(JSON.parse(decoded.text)),importProvenance:await sourceByteProvenance(bytes,file,'transcript-json',{encoding:decoded.encoding,bomBytes:decoded.bomBytes,losses:[]})};}if(/\.(srt|vtt|tsv|stm)$/.test(name)){const bytes=new Uint8Array(await file.arrayBuffer()),decoded=decodeSourceText(bytes,options.encoding||'auto'),format=name.split('.').at(-1),read=speechTranscript(decoded.text,format);return {...read,warnings:read.transcriptMetadata?.provider?.losses||[],importProvenance:await sourceByteProvenance(bytes,file,format,{encoding:decoded.encoding,bomBytes:decoded.bomBytes,losses:read.transcriptMetadata?.provider?.losses||[]})};}if(name.endsWith('.pdf')){const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');const worker=await import('pdfjs-dist/legacy/build/pdf.worker.mjs');globalThis.pdfjsWorker=worker;const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),useWorkerFetch:false,isEvalSupported:false}).promise;let text='';const pages=[];for(let n=1;n<=pdf.numPages;n++){const start=cp(text).length;const page=await pdf.getPage(n),content=await page.getTextContent();text+=content.items.map(x=>x.str+(x.hasEOL?'\n':' ')).join('')+'\n';const viewport=page.getViewport({scale:1});pages.push({page:n,start,end:cp(text).length,width:viewport.width,height:viewport.height});}return {text,turns:[],pages};}if(!name.endsWith('.txt')&&!name.endsWith('.md'))throw Error('Choose a supported transcript or reference document. CSV amendments and scripts are method records, not transcripts.');return {text:await file.text(),turns:[]};}
