import {esc} from './report-export.mjs';
// Chart image export: pure SVG helpers (Node-testable) plus browser-only rasterizing and live-SVG serialization.
export const SVG_NS='http://www.w3.org/2000/svg',MAX_CANVAS_SIDE=16384,MAX_CANVAS_AREA=16777216;
export const INLINE_STYLE_PROPERTIES=['fill','fill-opacity','fill-rule','stroke','stroke-width','stroke-opacity','stroke-dasharray','stroke-linecap','stroke-linejoin','opacity','visibility','display','font-family','font-size','font-weight','font-style','letter-spacing','text-anchor','dominant-baseline'];
export const STYLE_DEFAULTS={'fill-opacity':'1','fill-rule':'nonzero','stroke-opacity':'1','stroke-dasharray':'none','stroke-linecap':'butt','stroke-linejoin':'miter','opacity':'1','visibility':'visible','font-style':'normal','letter-spacing':'normal','text-anchor':'start','dominant-baseline':'auto'};
const FONT_PROPERTIES=new Set(['font-family','font-size','font-weight','font-style','letter-spacing','text-anchor','dominant-baseline']),TEXT_TAGS=new Set(['svg','text','tspan','textpath']);
const rootTag=svg=>{const m=/<svg\b(?:[^>"']|"[^"]*"|'[^']*')*>/i.exec(String(svg||''));if(!m)throw Error('No <svg> element found to export.');return m;};
const attr=(tag,name)=>{const m=new RegExp('\\s'+name+'\\s*=\\s*("([^"]*)"|\'([^\']*)\')','i').exec(tag);return m?(m[2]??m[3]):null;};
const length=value=>{const m=/^\s*([0-9]*\.?[0-9]+(?:e[-+]?\d+)?)\s*(px)?\s*$/i.exec(value??'');return m&&Number(m[1])>0?Number(m[1]):null;};
// Intrinsic size from absolute width/height, else the viewBox, else the browser default replaced-element size.
export function svgDimensions(svg){const tag=rootTag(svg)[0],box=(attr(tag,'viewBox')||'').trim().split(/[\s,]+/).map(Number),vb=box.length===4&&box.every(Number.isFinite)&&box[2]>0&&box[3]>0?{width:box[2],height:box[3]}:null,w=length(attr(tag,'width')),h=length(attr(tag,'height'));if(w&&h)return {width:w,height:h};if(vb&&w)return {width:w,height:w*vb.height/vb.width};if(vb&&h)return {width:h*vb.width/vb.height,height:h};return vb||{width:w||300,height:h||150};}
export function cappedScale(width,height,scale=2,{maxSide=MAX_CANVAS_SIDE,maxArea=MAX_CANVAS_AREA}={}){if(!(width>0&&height>0))throw Error('Chart has no measurable size.');const s=Math.min(scale>0?scale:1,maxSide/width,maxSide/height,Math.sqrt(maxArea/(width*height)));return Math.floor(s*1000)/1000;}
export function pngSize(svg,scale=2,limits){const {width,height}=svgDimensions(svg),s=cappedScale(width,height,scale,limits);return {width:Math.max(1,Math.floor(width*s)),height:Math.max(1,Math.floor(height*s)),scale:s,reduced:s<scale};}
// Rewrites only the root tag's xmlns/width/height; element content and escaped entities are left byte-for-byte.
export function sizedSvgMarkup(svg,{width,height}=svgDimensions(svg)){const m=rootTag(svg),source=String(svg);let tag=m[0].replace(/\s(width|height)\s*=\s*("[^"]*"|'[^']*')/gi,'');if(!/\sxmlns\s*=/.test(tag))tag=tag.replace(/^<svg\b/i,'<svg xmlns="'+SVG_NS+'"');tag=tag.replace(/^<svg\b/i,`<svg width="${+width.toFixed(3)}" height="${+height.toFixed(3)}"`);return source.slice(0,m.index)+tag+source.slice(m.index+m[0].length);}
export function wrapCaption(caption,maxChars,maxLines=6){const words=String(caption??'').replace(/\s+/g,' ').trim().split(' ').filter(Boolean),lines=[];for(const word of words){const last=lines.length-1;if(last>=0&&(lines[last]+' '+word).length<=maxChars)lines[last]+=' '+word;else lines.push(word.length>maxChars?word.slice(0,maxChars-1)+'…':word);}return lines.length>maxLines?[...lines.slice(0,maxLines-1),lines[maxLines-1].slice(0,maxChars-1)+'…']:lines;}
// Places the chart in a white canvas with a visible, escaped provenance caption below it (also kept in <desc>).
export function withCaption(svg,caption){if(!String(caption??'').trim())return sizedSvgMarkup(svg);const {width,height}=svgDimensions(svg),size=Math.max(10,Math.round(width/70)),lines=wrapCaption(caption,Math.max(20,Math.floor((width-24)/(size*.56)))),total=Math.ceil(height+16+lines.length*size*1.35),inner=sizedSvgMarkup(svg,{width,height}).replace(/<\?xml[^>]*\?>/,'');return `<svg xmlns="${SVG_NS}" width="${+width.toFixed(3)}" height="${total}" viewBox="0 0 ${+width.toFixed(3)} ${total}"><desc>${esc(caption)}</desc><rect width="100%" height="100%" fill="#fff"/>${inner}<text x="12" y="${Math.round(height+8+size)}" font-family="sans-serif" font-size="${size}" fill="#3d5361">${lines.map((line,i)=>`<tspan x="12" dy="${i?Math.round(size*1.35):0}">${esc(line)}</tspan>`).join('')}</text></svg>`;}
export function inlineStyleText(tag,get){return INLINE_STYLE_PROPERTIES.filter(p=>!FONT_PROPERTIES.has(p)||TEXT_TAGS.has(String(tag).toLowerCase())).map(p=>[p,String(get(p)??'').trim()]).filter(([p,v])=>v&&(p==='display'?v==='none':STYLE_DEFAULTS[p]!==v)).map(([p,v])=>p+':'+v).join(';');}
// Browser: clone a live <svg>, inline the computed paint/font styles app CSS supplied, and serialize it standalone.
export function serializeInlineSvg(el,{caption=''}={}){if(!el||String(el.tagName).toLowerCase()!=='svg')throw Error('Chart is not visible; open it before exporting.');const clone=el.cloneNode(true),from=[el,...el.querySelectorAll('*')],to=[clone,...clone.querySelectorAll('*')];if(!clone.getAttribute('viewBox')){const r=el.getBoundingClientRect();clone.setAttribute('viewBox',`0 0 ${Math.round(r.width)||300} ${Math.round(r.height)||150}`);}from.forEach((node,i)=>{const style=getComputedStyle(node),text=inlineStyleText(node.tagName,p=>style.getPropertyValue(p));to[i].removeAttribute('style');if(text)to[i].setAttribute('style',text);});clone.setAttribute('xmlns',SVG_NS);return withCaption(new XMLSerializer().serializeToString(clone),caption);}
export async function svgToPng(svg,{scale=2,background='#fff'}={}){const size=pngSize(svg,scale),url=URL.createObjectURL(new Blob([sizedSvgMarkup(svg)],{type:'image/svg+xml;charset=utf-8'}));try{const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('The chart SVG could not be decoded as an image.'));img.src=url;});const canvas=document.createElement('canvas');canvas.width=size.width;canvas.height=size.height;const ctx=canvas.getContext('2d');if(!ctx)throw Error('Canvas drawing is unavailable in this browser.');if(background){ctx.fillStyle=background;ctx.fillRect(0,0,size.width,size.height);}ctx.drawImage(img,0,0,size.width,size.height);return await new Promise((resolve,reject)=>{try{canvas.toBlob(blob=>blob?resolve(blob):reject(Error(`The browser produced no PNG for a ${size.width}×${size.height} canvas.`)),'image/png');}catch(e){reject(Error('PNG export was blocked by the browser ('+(e.name||'error')+': '+e.message+').'));}});}finally{URL.revokeObjectURL(url);}}
