import {pointLength} from './text-points.mjs';
import {scopedCodings,MEASURES} from './analysis-domain.mjs';
import {esc} from './report-export.mjs';
export function validateProjectMap(s,map){
 if(!map||!Array.isArray(map.nodes)||!Array.isArray(map.links)||map.nodes.length>300||map.links.length>1000)throw Error('A map supports up to 300 nodes and 1000 links.');
 const ids=new Set(),evidence=new Set(scopedCodings(s).map(c=>c.id));
 const nodes=map.nodes.map(n=>{if(typeof n.id!=='string'||!n.id||ids.has(n.id)||!String(n.label||'').trim()||String(n.label).length>300||![n.x,n.y].every(Number.isFinite)||Math.abs(n.x)>10000||Math.abs(n.y)>10000)throw Error('Invalid map node.');ids.add(n.id);if(!['concept','code','case','source'].includes(n.kind))throw Error('Invalid map node kind.');if(n.kind==='code'&&!s.codes.some(c=>c.id===n.refId)||n.kind==='case'&&!s.cases.some(c=>c.id===n.refId)||n.kind==='source'&&!s.documents.some(d=>d.id===n.refId&&d.sourceRole!=='reference'))throw Error('Map reference is missing or excluded.');return {id:String(n.id),kind:n.kind,label:String(n.label).trim(),refId:n.kind==='concept'?null:n.refId,x:n.x,y:n.y};});
 const links=map.links.map(l=>{if(!ids.has(l.from)||!ids.has(l.to)||l.from===l.to||String(l.label||'').length>300||!Array.isArray(l.codingIds)||l.codingIds.some(id=>!evidence.has(id)))throw Error('Map links require current, consent-cleared evidence or no evidence.');return {id:String(l.id||l.from+':'+l.to),from:l.from,to:l.to,label:String(l.label||'').trim(),codingIds:[...new Set(l.codingIds)]};});
 if(new Set(links.map(l=>l.id)).size!==links.length)throw Error('Duplicate map link.');
 return {nodes,links};
}
export function mapInScope(map,rows){const eligible=new Set(rows.map(c=>c.id));return {...map,nodes:map.nodes||[],links:(map.links||[]).map(l=>({...l,codingIds:l.codingIds.filter(id=>eligible.has(id))}))};}
export function mapGraphML(map){const nodeKeys=[['label','string'],['kind','string'],['reference','string'],['x','double'],['y','double']],edgeKeys=[['relationship','string'],['evidence','string']];return '<?xml version="1.0"?><graphml xmlns="http://graphml.graphdrawing.org/xmlns">'+nodeKeys.map(([id,t])=>`<key id="${id}" for="node" attr.name="${id}" attr.type="${t}"/>`).join('')+edgeKeys.map(([id,t])=>`<key id="${id}" for="edge" attr.name="${id}" attr.type="${t}"/>`).join('')+'<graph id="concept-map" edgedefault="directed">'+map.nodes.map(n=>`<node id="${esc(n.id)}"><data key="label">${esc(n.label)}</data><data key="kind">${esc(n.kind)}</data><data key="reference">${esc(n.refId||'')}</data><data key="x">${n.x}</data><data key="y">${n.y}</data></node>`).join('')+map.links.map(l=>`<edge id="${esc(l.id)}" source="${esc(l.from)}" target="${esc(l.to)}"><data key="relationship">${esc(l.label)}</data><data key="evidence">${esc(JSON.stringify(l.codingIds))}</data></edge>`).join('')+'</graph></graphml>';}
export function codePortrait(s,rows,{bins=40}={}){if(!Number.isInteger(bins)||bins<2||bins>200)throw Error('Choose 2–200 portrait columns.');return s.documents.filter(d=>d.sourceRole!=='reference').map(d=>{const length=pointLength(d.text||''),list=rows.filter(c=>c.documentId===d.id&&!c.kind);return {source:d,length,cells:Array.from({length:bins},(_,i)=>{const start=Math.floor(i*length/bins),end=Math.floor((i+1)*length/bins),applications=list.filter(c=>Math.max(start,c.start)<Math.min(end,c.end));return {start,end,rows:applications,codes:[...new Set(applications.map(c=>c.codeId))]};})};});}
export function matrixRows(matrix,{metric,scope,group,rowMode}){return [['Analysis measure',MEASURES[metric]],['Scope',scope],['Columns',group],['Rows',rowMode],['Note','Totals deduplicate within scope; overlapping cases and parent rows are nonadditive. Area sums distinct rectangles.'],[],['Code',...matrix.columns.map(c=>c.name),'Deduplicated row total'],...matrix.rows.map(r=>[r.name,...r.cells.map(c=>c.value),r.total]),['Deduplicated scope total',...matrix.columns.map(()=>''),matrix.total]];}
export function reorderCodes(codes,from,before){const list=[...codes].sort((a,b)=>(a.order??codes.indexOf(a))-(b.order??codes.indexOf(b))).map(c=>c.id);if(!list.includes(from)||!list.includes(before))throw Error('Code order changed.');if(from===before)return list;list.splice(list.indexOf(from),1);list.splice(list.indexOf(before),0,from);return list;}
