import {emptyState,validateState} from './domain.mjs';
export const qualCoderTables=['project','source','code_name','code_cat','code_text','cases','case_text','attribute','attribute_type','journal','annotation','stored_sql','coder_names','code_image','code_av'];
export function normalizeQualCoder(tables,name='Imported QualCoder project'){
 const rows=key=>tables[key]||[],s=emptyState(name),attrs=rows('attribute');
 s.categories=rows('code_cat').map(c=>({id:String(c.catid),name:c.name,parentId:c.supercatid?String(c.supercatid):null,memo:c.memo}));
 s.codes=rows('code_name').map(c=>({id:String(c.cid),name:c.name,description:c.memo||'',parentId:c.supercid?String(c.supercid):null,categoryId:c.catid?String(c.catid):null,color:c.color,coder:c.owner,date:c.date}));
 s.documents=rows('source').map(d=>({id:String(d.id),name:d.name,text:d.fulltext||'',revision:1,sourceRole:'interview',attributes:Object.fromEntries(attrs.filter(a=>a.attr_type==='file'&&a.id===d.id).map(a=>[a.name,a.value])),memo:d.memo||'',turns:[],versions:[],originalMediaPath:d.mediapath,owner:d.owner,date:d.date,avTextId:d.av_text_id,risId:d.risid,excludeAI:true}));
 s.codings=rows('code_text').map(c=>({id:String(c.ctid),codeId:String(c.cid),documentId:String(c.fid),start:c.pos0,end:c.pos1,text:c.seltext,coder:c.owner,memo:c.memo||'',date:c.date,status:'coded',sourceRevision:1,important:!!c.important,avId:c.avid}));
 const links=rows('case_text');s.cases=rows('cases').map(c=>({id:String(c.caseid),name:c.name,memo:c.memo,documentIds:[...new Set(links.filter(l=>l.caseid===c.caseid).map(l=>String(l.fid)))],attributes:Object.fromEntries(attrs.filter(a=>a.attr_type==='case'&&a.id===c.caseid).map(a=>[a.name,a.value]))}));
 s.attributeTypes=rows('attribute_type').map(a=>({name:a.name,valueType:a.valuetype,scope:a.caseOrFile,memo:a.memo,owner:a.owner,date:a.date}));
 s.journals=rows('journal').map(j=>({id:String(j.jid),name:j.name,text:j.jentry,coder:j.owner,date:j.date}));s.memos=rows('annotation').map(m=>({id:'annotation-'+m.anid,title:'Passage annotation',content:m.memo,documentId:String(m.fid),start:m.pos0,end:m.pos1,author:m.owner,date:m.date}));
 s.legacy={...tables,attributes:attrs,categories:rows('code_cat'),caseLinks:links,codes:rows('code_name'),annotations:rows('annotation'),imageCodings:rows('code_image'),mediaCodings:rows('code_av'),storedQueries:rows('stored_sql'),coderRegistry:rows('coder_names'),originalTextCodings:rows('code_text')};
 s.importNotes=['Supported QualCoder tables are retained as original records; ancillary graph, RIS and other application tables are not activated by this adapter.','Imported speaker names, transcript accuracy and consent still require review.','Stored SQL queries are retained as inert records; they are never executed.','Case passage bounds are retained in original records; active case links are source-level.'];
 if(rows('code_image').length||rows('code_av').length||s.documents.some(d=>d.originalMediaPath))s.importNotes.push('QualCoder media paths and region/time selections are retained as original records. This importer does not attach archive media or activate those selections; attach originals and review geometry before using them.');
 validateState(s);return s;
}
