import {zipSync,strToU8} from 'fflate';
const esc=s=>String(s??'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\ufffe\uffff]/g,'\uFFFD').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));
function decimal(n){const text=String(n);if(!/[eE]/.test(text))return text;const [coefficient,power]=text.toLowerCase().split('e'),negative=coefficient.startsWith('-'),plain=coefficient.replace('-',''),dot=plain.indexOf('.'),digits=plain.replace('.',''),position=(dot<0?plain.length:dot)+Number(power),value=position<=0?'0.'+'0'.repeat(-position)+digits:position>=digits.length?digits+'0'.repeat(position-digits.length):digits.slice(0,position)+'.'+digits.slice(position);return (negative?'-':'')+value;}
function ids(){const m=new Map();return key=>{if(!m.has(key))m.set(key,crypto.randomUUID());return m.get(key);};}
function codeTree(s,g,noteRefs=()=> ''){const node=c=>`<Code guid="${g('code:'+c.id)}" name="${esc(c.name)}" color="${esc(/^#[0-9a-f]{6}$/i.test(c.color)?c.color:'#537a92')}" isCodable="${c.codable===false?'false':'true'}"><Description>${esc(c.description)}</Description>${noteRefs('code',c.id)}${s.codes.filter(x=>x.parentId===c.id).map(node).join('')}</Code>`;const category=cat=>`<Code guid="${g('category:'+cat.id)}" name="${esc(cat.name)}" isCodable="false"><Description>${esc(cat.memo)}</Description>${(s.categories||[]).filter(x=>x.parentId===cat.id).map(category).join('')}${s.codes.filter(c=>!c.parentId&&c.categoryId===cat.id).map(node).join('')}</Code>`;return (s.categories||[]).filter(c=>!c.parentId).map(category).join('')+s.codes.filter(c=>!c.parentId&&!(s.categories||[]).some(x=>x.id===c.categoryId)).map(node).join('');}
export function exportQDC(s){const g=ids();return '<?xml version="1.0" encoding="UTF-8"?><CodeBook xmlns="urn:QDA-XML:codebook:1.0"><Codes>'+codeTree(s,g)+'</Codes></CodeBook>';}
export function exportQDPX(s,mediaFiles={}){
 const g=ids(),files={},mediaManifest={},fallback=new Date().toISOString();
 const memos=[...(s.memos||[]),...(s.journals||[]).map(j=>({id:'journal:'+j.id,title:j.name,content:j.text,author:j.coder,date:j.date})),...s.codings.filter(c=>!c.deletedAt&&c.memo).map(c=>({id:'coding-memo:'+c.id,title:'Coding memo',content:c.memo,author:c.coder,date:c.date,codingId:c.id}))];
 const date=v=>{const d=new Date(v||fallback);return Number.isNaN(d.getTime())?fallback:d.toISOString();};
 const provenance=(author,created,modified)=>`creatingUser="${g('user:'+(author||'Imported coder'))}" creationDateTime="${date(created)}" modifiedDateTime="${date(modified||created)}"`;
 const users=[...new Set([...s.codings.filter(c=>!c.deletedAt).map(c=>c.coder),...memos.map(m=>m.author||'Imported coder')].filter(Boolean))];
 const refs=(kind,id)=>memos.filter(m=>kind==='coding'?m.codingId===id:kind==='code'?m.codeId===id:kind==='source'?m.documentId===id:!m.documentId&&!m.codeId&&!m.codingId).map(m=>`<NoteRef targetGUID="${g('memo:'+m.id)}"/>`).join('');
 const attributes=[];for(const [scope,list] of [['file',s.documents],['case',s.cases]])for(const name of [...new Set(list.flatMap(d=>Object.keys(d.attributes||{})))]){const declared=s.attributeTypes?.find(t=>t.scope===scope&&t.name===name)?.valueType,items=list.map(d=>d.attributes?.[name]).filter(v=>v!=null&&v!==''),type=['number','numeric'].includes(declared)?'Float':declared==='boolean'?'Boolean':declared==='date'?'Date':!declared&&items.length&&items.every(v=>typeof v==='number')?'Float':!declared&&items.length&&items.every(v=>typeof v==='boolean')?'Boolean':'Text';attributes.push({scope,name,type,key:scope+':'+name});}
 const values=(a,scope='file')=>Object.entries(a||{}).filter(([k,v])=>v!=null&&v!=='').map(([k,v])=>{const item=attributes.find(t=>t.scope===scope&&t.name===k),type=item?.type||'Text';if(type==='Float'&&!Number.isFinite(Number(v)))throw Error('Invalid numeric exchange attribute: '+k);if(type==='Date'&&!/^\d{4}-\d{2}-\d{2}$/.test(String(v)))throw Error('Invalid date exchange attribute: '+k);const value=type==='Float'?decimal(Number(v)):type==='Boolean'?(v===true||v==='true'?'true':v===false||v==='false'?'false':null):v;if(value===null)throw Error('Invalid boolean exchange attribute: '+k);return `<VariableValue><VariableRef targetGUID="${g('variable:'+scope+':'+k)}"/><${type}Value>${esc(value)}</${type}Value></VariableValue>`;}).join('');
 const coding=c=>`<Coding guid="${g('coding:'+c.id)}" creatingUser="${g('user:'+c.coder)}" creationDateTime="${date(c.date)}"><CodeRef targetGUID="${g('code:'+c.codeId)}"/>${refs('coding',c.id)}</Coding>`;
 const textSelections=d=>{const groups=new Map();for(const c of s.codings.filter(c=>c.documentId===d.id&&!c.kind&&!c.deletedAt&&c.status!=='needs_review')){const key=[c.start,c.end,c.coder].join(':');if(!groups.has(key))groups.set(key,[]);groups.get(key).push(c);}return [...groups.values()].map(cs=>`<PlainTextSelection guid="${g('selection:'+d.id+':'+cs[0].start+':'+cs[0].end+':'+cs[0].coder)}" startPosition="${cs[0].start}" endPosition="${cs[0].end}" ${provenance(cs[0].coder,cs[0].date)}>${cs.map(coding).join('')}</PlainTextSelection>`).join('');};
 const text=d=>{const file=g('source:'+d.id)+'.txt';files['Sources/'+file]=strToU8(d.text);return `guid="${g('source:'+d.id)}" name="${esc(d.name)}" plainTextPath="internal://${file}"`;};
 let sources='';for(const d of s.documents){const bytes=mediaFiles[d.mediaKey],type=d.mediaType||'';const body=`<Description>${esc(d.memo)}</Description>${textSelections(d)}${refs('source',d.id)}${values(d.attributes)}`;
 if(bytes&&type==='application/pdf'){const file=g('media:'+d.id)+'.pdf';files['Sources/'+file]=bytes;mediaManifest[d.id]={path:'Sources/'+file,type};const selections=s.codings.filter(c=>c.documentId===d.id&&c.kind==='pdf'&&!c.deletedAt).map(c=>{const r=c.region;return `<PDFSelection name="${esc(c.text||c.memo)}" guid="${g('media-selection:'+c.id)}" page="${r.page-1}" firstX="${Math.round(r.x)}" firstY="${Math.round(r.y)}" secondX="${Math.round(r.x+r.width)}" secondY="${Math.round(r.y+r.height)}" ${provenance(c.coder,c.date)}><Description>${esc(c.text)}</Description>${coding(c)}</PDFSelection>`;}).join('');sources+=`<PDFSource guid="${g('pdf:'+d.id)}" name="${esc(d.name)}" path="internal://${file}"><Description>${esc(d.memo)}</Description>${selections}<Representation ${text(d)}>${body}</Representation></PDFSource>`;continue;}
 if(d.text||!bytes)sources+=`<TextSource ${text({...d,name:bytes?d.name+' · text':d.name})}>${body}</TextSource>`;
 if(bytes){const file=g('media:'+d.id)+'.'+(type.split('/')[1]?.replace('x-wav','wav')||'bin');files['Sources/'+file]=bytes;mediaManifest[d.id]={path:'Sources/'+file,type,width:d.mediaWidth,height:d.mediaHeight};if(type.startsWith('image/')){const w=d.mediaWidth||10000,h=d.mediaHeight||10000;const selections=s.codings.filter(c=>c.documentId===d.id&&c.kind==='image'&&!c.deletedAt).map(c=>`<PictureSelection name="${esc(c.text||c.memo)}" guid="${g('media-selection:'+c.id)}" firstX="${Math.round(c.region.x*w)}" firstY="${Math.round(c.region.y*h)}" secondX="${Math.round((c.region.x+c.region.width)*w)}" secondY="${Math.round((c.region.y+c.region.height)*h)}" ${provenance(c.coder,c.date)}><Description>${esc(c.text)}</Description>${coding(c)}</PictureSelection>`).join('');sources+=`<PictureSource guid="${g('picture:'+d.id)}" name="${esc(d.name)}" path="internal://${file}">${selections}${refs('source',d.id)}${values(d.attributes)}</PictureSource>`;}
 if(/^(audio|video)\//.test(type)){const tag=type.startsWith('audio/')?'Audio':'Video';const selections=s.codings.filter(c=>c.documentId===d.id&&c.kind==='media'&&!c.deletedAt&&c.status!=='needs_review'&&(!c.recordingKey||c.recordingKey===d.mediaKey)).map(c=>`<${tag}Selection guid="${g('media-selection:'+c.id)}" begin="${Math.round(c.timeStart*1000)}" end="${Math.round(c.timeEnd*1000)}" ${provenance(c.coder,c.date)}><Description>${esc(c.text)}</Description>${coding(c)}</${tag}Selection>`).join('');sources+=`<${tag}Source guid="${g('av:'+d.id)}" name="${esc(d.name)}" path="internal://${file}">${selections}${refs('source',d.id)}${values(d.attributes)}</${tag}Source>`;}}}
 const notes=memos.map(m=>{const passage=m.documentId&&Number.isInteger(m.start)&&m.anchorStatus!=='needs_review';let content,path='';if(passage)content=`<PlainTextContent>${esc(m.content)}</PlainTextContent><PlainTextSelection guid="${g('note-selection:'+m.id)}" startPosition="${m.start}" endPosition="${m.end}"/>`;else{const file=g('memo:'+m.id)+'.txt';files['Sources/'+file]=strToU8(m.content||'');path=` plainTextPath="internal://${file}"`;content='';}return `<Note guid="${g('memo:'+m.id)}" name="${esc(m.title)}" ${provenance(m.author,m.date,m.modifiedAt)}${path}>${content}</Note>`;}).join('');
 const sourceRef=id=>{const d=s.documents.find(x=>x.id===id),bytes=mediaFiles[d?.mediaKey];return bytes&&d.mediaType==='application/pdf'?g('pdf:'+id):bytes&&!d.text?g((d.mediaType.startsWith('image/')?'picture:':'av:')+id):g('source:'+id);};
 const cases=s.cases.map(c=>`<Case guid="${g('case:'+c.id)}" name="${esc(c.name)}"><Description>${esc(c.memo)}</Description>${values(c.attributes,'case')}${c.documentIds.map(id=>`<SourceRef targetGUID="${sourceRef(id)}"/>`).join('')}</Case>`).join('');
 const xml=`<?xml version="1.0" encoding="UTF-8"?><Project xmlns="urn:QDA-XML:project:1.0" name="${esc(s.name)}" origin="Research Weave">${s.description?`<Description>${esc(s.description)}</Description>`:''}${users.length?'<Users>'+users.map(u=>`<User guid="${g('user:'+u)}" name="${esc(u)}"/>`).join('')+'</Users>':''}${s.codes.length?'<CodeBook><Codes>'+codeTree(s,g,refs)+'</Codes></CodeBook>':''}${attributes.length?'<Variables>'+attributes.map(a=>`<Variable guid="${g('variable:'+a.key)}" name="${esc(a.name)}" typeOfVariable="${a.type}"/>`).join('')+'</Variables>':''}${cases?'<Cases>'+cases+'</Cases>':''}${sources?'<Sources>'+sources+'</Sources>':''}${notes?'<Notes>'+notes+'</Notes>':''}${refs('project')}</Project>`;
 files['research-weave-exchange-scope.json']=strToU8(JSON.stringify({standard:'REFI-QDA 1.0',variables:'Typed source and case variables; missing/null values omitted from standard XML.',nativeOnly:['Memo @code/@source/@case/@memo token references and stable record IDs; standard notes retain plain text only','Source direction, original-byte digests, extraction losses and OCR provenance','Turn and word timestamps and timing history','Passage-level case assignments','Pinned passage relationships','Coding status, archived coding, query provenance, review tasks and audit history'],lossless:'research-weave.json preserves native project fields. Private account notes are never part of this archive.'}));files['research-weave-alignment.json']=strToU8(JSON.stringify({units:'seconds',lossless:'research-weave.json and per-source transcript JSON preserve supplied turn/word timing and revision history.',externalRefi:'Turn/word synchronization is retained in the native sidecar only. External REFI audio selections use rounded milliseconds; synchronized transcript interoperability is not yet verified.',sources:s.documents.map(d=>({id:d.id,alignment:d.alignment||null,timedTurns:(d.turns||[]).filter(t=>Number.isFinite(t.timeStart)).length}))}));files['research-weave-media.json']=strToU8(JSON.stringify(mediaManifest));files['project.qde']=strToU8(xml);files['research-weave.json']=strToU8(JSON.stringify({format:'research-weave',version:1,state:s}));return zipSync(files);
}
