import {emptyState,validateState} from './domain.mjs';
import {readSQLiteTable,sqliteTextEncoding,sqliteTextSelection,decodeSQLiteTextRows} from './sqlite-text.mjs';
// Independently implemented allowlist adapter. Source contracts were inspected, not copied.
export const REQUAL_SCHEMA={projects:['project_id','project_name'],documents:['project_id','doc_id','doc_name','doc_text'],codes:['project_id','code_id','code_name'],segments:['project_id','segment_id','doc_id','code_id','segment_start','segment_end','segment_text']};
const fields={projects:['project_id','project_name','project_description','created_at'],requal_version:['project_id','version'],documents:['project_id','doc_id','doc_name','doc_text','doc_description','created_at','user_id'],codes:['project_id','code_id','code_name','code_description','code_color','user_id'],segments:['project_id','segment_id','doc_id','code_id','segment_start','segment_end','segment_text','user_id'],categories:['project_id','category_id','category_name','category_description','user_id'],categories_codes_map:['project_id','category_id','code_id'],cases:['project_id','case_id','case_name','case_description'],cases_documents_map:['project_id','case_id','doc_id'],memos:['project_id','memo_id','user_id','text'],memos_codes_map:['memo_id','code_id'],memos_documents_map:['memo_id','doc_id','memo_start','memo_end'],memos_segments_map:['memo_id','segment_id'],attributes:['project_id','attribute_id','attribute_name','attribute_object','attribute_type'],attribute_values:['attribute_id','attribute_value_id','value'],attributes_documents_map:['project_id','doc_id','attribute_id','attribute_value_id'],attributes_cases_map:['project_id','case_id','attribute_id','attribute_value_id']};
const TEXT_FIELDS=new Set(['project_name','project_description','created_at','version','doc_name','doc_text','doc_description','code_name','code_description','code_color','segment_text','category_name','category_description','case_name','case_description','text','attribute_name','attribute_object','attribute_type','value']);
const minimum={...REQUAL_SCHEMA,requal_version:['project_id','version'],categories:['project_id','category_id','category_name'],categories_codes_map:['project_id','category_id','code_id'],cases:['project_id','case_id','case_name'],cases_documents_map:['project_id','case_id','doc_id'],memos:['project_id','memo_id','text'],memos_codes_map:['memo_id','code_id'],memos_documents_map:['memo_id','doc_id','memo_start','memo_end'],memos_segments_map:['memo_id','segment_id'],attributes:['project_id','attribute_id','attribute_name'],attribute_values:['attribute_id','attribute_value_id','value'],attributes_documents_map:['project_id','doc_id','attribute_id','attribute_value_id'],attributes_cases_map:['project_id','case_id','attribute_id','attribute_value_id']};
const query=(db,sql,params=[])=>{const result=db.exec(sql,params)[0];return result?result.values.map(values=>Object.fromEntries(result.columns.map((name,i)=>[name,values[i]]))):[];};
const bounded=(db,sql,params=[])=>{const rows=query(db,sql+' LIMIT 200001',params);if(rows.length>200000)throw Error('Requal project exceeds the browser import record limit.');return rows;};
function choose(projects,projectId){if(!projects.length)throw Error('Requal database has no project.');if(projectId==null||projectId===''){if(projects.length!==1){const error=Error('This Requal database contains multiple projects. Select one exact project ID before importing.');error.projects=projects.map(p=>({id:String(p.project_id),name:p.project_name}));throw error;}return projects[0];}const project=projects.find(p=>String(p.project_id)===String(projectId));if(!project)throw Error('Selected Requal project is missing.');return project;}
export function requalProjectChoices(db){return {format:'requal',projects:readSQLiteTable(db,'projects',['project_id','project_name']).map(p=>({id:String(p.project_id),name:p.project_name}))};}
export function readRequal(db,options={}){
 const names=query(db,"SELECT name FROM sqlite_master WHERE type='table'").map(r=>r.name),columns={},encoding=sqliteTextEncoding(db);
 for(const [table,required]of Object.entries(minimum)){if(!names.includes(table)){if(table in REQUAL_SCHEMA)throw Error('Requal is missing required '+table+' table.');continue;}const actual=query(db,'PRAGMA table_info("'+table+'")').map(r=>r.name);if(required.some(name=>!actual.includes(name)))throw Error('Invalid Requal '+table+' table schema.');columns[table]=actual;}
 const selected=(table,where='',params=[])=>{if(!names.includes(table))return [];const allowed=fields[table].filter(name=>columns[table]?.includes(name));return decodeSQLiteTextRows(bounded(db,'SELECT '+sqliteTextSelection(allowed,TEXT_FIELDS)+' FROM "'+table+'"'+where,params),TEXT_FIELDS,encoding);};
 const project=choose(selected('projects'),options.projectId),tables={projects:[project]};
 for(const table of Object.keys(fields)){if(table==='projects')continue;if(['memos_codes_map','memos_documents_map','memos_segments_map'].includes(table)){if(names.includes('memos'))tables[table]=selected(table,' WHERE memo_id IN (SELECT memo_id FROM memos WHERE project_id=?)',[project.project_id]);}else if(table==='attribute_values'){if(names.includes('attributes'))tables[table]=selected(table,' WHERE attribute_id IN (SELECT attribute_id FROM attributes WHERE project_id=?)',[project.project_id]);}else tables[table]=selected(table,' WHERE project_id=?',[project.project_id]);}
 return normalizeRequal(tables,{...options,projectId:project.project_id});
}
const verifiedVersions=new Set(['1.0.0','1.2.4.9009']);
const sourceSlice=(text,start,end)=>Array.from(text).slice(start,end).join('');
const bounds=(text,start,end)=>Number.isSafeInteger(start)&&Number.isSafeInteger(end)&&start>=0&&end>start&&end<=Array.from(text).length;
const author=id=>id==null?'Imported Requal author (unidentified)':'Imported Requal user '+String(id)+' (identity unverified)';
export function normalizeRequal(tables,{projectId}={}){
 const rows=table=>tables[table]||[],project=choose(rows('projects'),projectId),pid=String(project.project_id),selected=table=>rows(table).filter(row=>String(row.project_id)===pid),s=emptyState(project.project_name||'Imported Requal project'),losses=[],excluded=[],records={categoryLinks:[],memoLinks:[],attributes:[]},id=(kind,value)=>'requal:'+pid+':'+kind+':'+value,prov=(kind,value,userId)=>({application:'requal',projectId:pid,recordType:kind,originalId:String(value),...(userId==null?{}:{originalUserId:String(userId)})});
 const versions=selected('requal_version').map(row=>String(row.version)),version=versions.length===1?versions[0]:null,contract=verifiedVersions.has(version);
 s.description=project.project_description||'';s.nativeImport={application:'requal',projectId:pid,permissionsImported:false,sourceOffsetUnit:contract?'One-based Unicode character positions; inclusive end':'Unverified version or ambiguous version records; passage bounds withheld',projectMetadata:{created:project.created_at||null,version,versionRecords:versions},offsetContract:{verified:contract,supportedVersions:[...verifiedVersions],source:'Requal R/mod_document_code_utils_document_code.R get_segment_text: R substr(start,stop), pinned v1.0.0 and dd266149',oneBased:true,endInclusive:true},losses,excluded,records};
 const docMap=new Map(),codeMap=new Map(),segmentMap=new Map();
 for(const d of selected('documents')){if(typeof d.doc_text!=='string')throw Error('Requal source text is missing.');const doc={id:id('source',d.doc_id),name:d.doc_name||'Imported source',text:d.doc_text,memo:d.doc_description||'',direction:'auto',revision:1,sourceRole:'interview',attributes:{},turns:[],versions:[],excludeAI:true,importProvenance:{...prov('document',d.doc_id,d.user_id),created:d.created_at||null}};s.documents.push(doc);docMap.set(String(d.doc_id),doc);}
 for(const c of selected('codes')){const code={id:id('code',c.code_id),name:c.code_name||'Imported code',description:c.code_description||'',color:/^#[0-9a-f]{6}$/i.test(c.code_color||'')?c.code_color:'#537a92',parentId:null,codable:true,importProvenance:{...prov('code',c.code_id,c.user_id),originalColor:c.code_color||null}};const rgb=/^rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)$/i.exec(c.code_color||'');if(rgb&&rgb.slice(1).every(n=>Number(n)<=255))code.color='#'+rgb.slice(1).map(n=>Number(n).toString(16).padStart(2,'0')).join('');else if(c.code_color&&!/^#[0-9a-f]{6}$/i.test(c.code_color))losses.push({kind:'color',codeId:code.id,message:'Unsupported native code color retained in provenance; a display fallback was used.'});s.codes.push(code);codeMap.set(String(c.code_id),code);}
 for(const c of selected('segments')){const doc=docMap.get(String(c.doc_id)),code=codeMap.get(String(c.code_id));if(!doc||!code){excluded.push({kind:'segment',id:String(c.segment_id),reason:'Missing or out-of-project source/code; application excluded.'});continue;}const start=Number.isSafeInteger(c.segment_start)?c.segment_start-1:c.segment_start,end=c.segment_end,quote=typeof c.segment_text==='string'?c.segment_text:'',verified=contract&&bounds(doc.text,start,end)&&sourceSlice(doc.text,start,end)===quote,coding={id:id('segment',c.segment_id),documentId:doc.id,codeId:code.id,start,end,text:quote,coder:author(c.user_id),date:null,status:verified?'coded':'needs_review',sourceRevision:1,memo:'',origin:'requal-import',importProvenance:{...prov('segment',c.segment_id,c.user_id),originalStart:c.segment_start,originalEnd:c.segment_end,sourceVersion:version,offsetUnit:'Native one-based Unicode inclusive bounds; verification required'}};s.codings.push(coding);segmentMap.set(String(c.segment_id),coding);if(!verified)losses.push({kind:'anchor',codingId:coding.id,message:'Requal version, bounds or exact stored quotation could not be verified; coding withheld. No offset-unit guessing or text search performed.'});}
 s.cases=selected('cases').map(c=>({id:id('case',c.case_id),name:c.case_name||'Imported case',memo:c.case_description||'',documentIds:[],passages:[],attributes:{},importProvenance:prov('case',c.case_id)}));const caseMap=new Map(s.cases.map(c=>[c.importProvenance.originalId,c]));
 for(const link of selected('cases_documents_map')){const doc=docMap.get(String(link.doc_id)),which=caseMap.get(String(link.case_id));if(doc&&which){if(!which.documentIds.includes(doc.id))which.documentIds.push(doc.id);}else excluded.push({kind:'case-link',reason:'Missing or out-of-project source/case; link excluded.'});}
 s.categories=selected('categories').map(c=>({id:id('category',c.category_id),name:c.category_name||'Imported category',memo:c.category_description||'',parentId:null,importProvenance:prov('category',c.category_id,c.user_id)}));const categoryMap=new Map(s.categories.map(c=>[c.importProvenance.originalId,c]));
 for(const link of selected('categories_codes_map')){const code=codeMap.get(String(link.code_id)),category=categoryMap.get(String(link.category_id));if(code&&category)records.categoryLinks.push({codeId:code.id,categoryId:category.id});else excluded.push({kind:'category-link',reason:'Missing or out-of-project code/category; link excluded.'});}
 for(const code of s.codes){const memberships=[...new Set(records.categoryLinks.filter(link=>link.codeId===code.id).map(link=>link.categoryId))];if(memberships.length===1)code.categoryId=memberships[0];else if(memberships.length>1)losses.push({kind:'category-membership',codeId:code.id,message:'Multiple native category memberships retained in provenance; no arbitrary single category or duplicate code was inferred.'});}
 for(const m of selected('memos')){const memo={id:id('memo',m.memo_id),title:'Imported Requal memo '+String(m.memo_id),content:m.text||'',author:author(m.user_id),date:null,importProvenance:prov('memo',m.memo_id,m.user_id)},links=[];
  for(const link of rows('memos_codes_map').filter(link=>String(link.memo_id)===String(m.memo_id))){const code=codeMap.get(String(link.code_id));if(code)links.push({kind:'code',codeId:code.id});}
  for(const link of rows('memos_segments_map').filter(link=>String(link.memo_id)===String(m.memo_id))){const coding=segmentMap.get(String(link.segment_id));if(coding)links.push({kind:'segment',codingId:coding.id,codeId:coding.codeId,documentId:coding.documentId,...(coding.status==='needs_review'?{anchorStatus:'needs_review'}:{start:coding.start,end:coding.end,text:coding.text,sourceRevision:1,anchorStatus:'current'})});}
  for(const link of rows('memos_documents_map').filter(link=>String(link.memo_id)===String(m.memo_id))){const doc=docMap.get(String(link.doc_id));if(!doc)continue;const anchored=link.memo_start!=null||link.memo_end!=null,start=Number.isSafeInteger(link.memo_start)?link.memo_start-1:link.memo_start,end=link.memo_end,valid=contract&&bounds(doc.text,start,end);links.push({kind:anchored?'passage':'source',documentId:doc.id,originalStart:link.memo_start,originalEnd:link.memo_end,...(anchored?valid?{start,end,text:sourceSlice(doc.text,start,end),sourceRevision:1,anchorStatus:'current'}:{anchorStatus:'needs_review'}:{})});}
  records.memoLinks.push({memoId:memo.id,links});if(links.length===1){const {kind,originalStart,originalEnd,...link}=links[0];Object.assign(memo,link);if(link.anchorStatus==='current')memo.citations=[{documentId:link.documentId,start:link.start,end:link.end,text:link.text,sourceRevision:1,relation:'evidence'}];if(link.anchorStatus==='needs_review')losses.push({kind:'memo-anchor',memoId:memo.id,message:'Memo text retained; native passage anchor requires review.'});}else if(links.length>1)losses.push({kind:'memo-membership',memoId:memo.id,message:'Memo has multiple native targets. Every link retained in provenance; prose imported once without selecting an arbitrary active target.'});s.memos.push(memo);
 }
 const definitions=new Map(selected('attributes').map(a=>[String(a.attribute_id),a])),values=new Map(rows('attribute_values').map(value=>[String(value.attribute_value_id),value]));
 for(const [table,scope,map,key]of [['attributes_documents_map','file',docMap,'doc_id'],['attributes_cases_map','case',caseMap,'case_id']])for(const link of selected(table)){const target=map.get(String(link[key])),definition=definitions.get(String(link.attribute_id)),value=values.get(String(link.attribute_value_id));if(!target||!definition||!value||String(value.attribute_id)!==String(link.attribute_id)){excluded.push({kind:'attribute-link',reason:'Missing or out-of-project attribute/target/value; link excluded.'});continue;}const name=String(definition.attribute_name),record={scope,targetId:target.id,name,attributeId:String(link.attribute_id),valueId:String(link.attribute_value_id),value:value.value,originalType:definition.attribute_type||null};records.attributes.push(record);if(Object.hasOwn(target.attributes,name)&&target.attributes[name]!==value.value){delete target.attributes[name];record.conflict=true;losses.push({kind:'attribute-collision',targetId:target.id,name,message:'Multiple native values or definitions share an attribute name; conflicting values retained in provenance without overwrite.'});}else if(!records.attributes.slice(0,-1).some(prior=>prior.targetId===target.id&&prior.name===name&&prior.conflict))Object.defineProperty(target.attributes,name,{value:value.value,writable:true,enumerable:true,configurable:true});if(!s.attributeTypes?.some(type=>type.name===name&&type.scope===scope)){s.attributeTypes??=[];s.attributeTypes.push({name,scope,valueType:'text'});}}
 s.importNotes=['One-way native Requal SQLite import. This is distinct from the related RQDA migration adapter; no native Requal exporter or R/Shiny runtime round trip is claimed.','Exactly one selected project is imported. User identities, email/login/password records, permissions, audit-log payloads, saved SQL and runtime settings are not queried or imported. Explicit historical user IDs distinguish authors without authenticating identity.','Source Unicode and original selected quotation text are retained exactly. Verified native bounds convert one-based inclusive positions to zero-based exclusive codepoint anchors. Unknown or ambiguous version records and stale quotes remain withheld for review.','Source, code, case and category descriptions are retained. Multiple category/memo targets remain in provenance where one active target cannot represent the native relationships.','Source/case attribute values remain strings or null without numeric/date inference. Researcher attributes are omitted. Original native colors are preserved even when the display uses a safe fallback.','All sources are excluded from AI pending human consent review. No timestamps, speaker labels, membership permissions or media attachments are inferred.',...losses.map(loss=>loss.message)];
 validateState(s);return s;
}
