import {emptyState,validateState} from './domain.mjs';
import {sqliteTextEncoding,sqliteTextSelection,decodeSQLiteTextRows} from './sqlite-text.mjs';
export const RQDA_SCHEMA={project:['databaseversion'],source:['id','name','file','status'],freecode:['id','name','status'],coding:['cid','fid','selfirst','selend','status']};
const fields={project:['databaseversion','date','dateM','memo','about'],source:['id','name','file','memo','owner','date','dateM','status'],freecode:['id','name','memo','owner','date','dateM','status','color'],coding:['cid','fid','seltext','selfirst','selend','status','owner','date','memo'],coding2:['cid','fid','seltext','selfirst','selend','status','owner','date','memo'],cases:['id','name','memo','owner','date','dateM','status'],caselinkage:['caseid','fid','selfirst','selend','status','owner','date','memo'],codecat:['name','catid','memo','owner','date','dateM','status'],treecode:['cid','catid','date','dateM','memo','status','owner'],journal:['name','journal','date','dateM','owner','status']};
const TEXT_FIELDS=new Set(['databaseversion','date','dateM','memo','about','name','file','owner','color','seltext','journal']);
const required={...RQDA_SCHEMA,cases:['id','name','status'],caselinkage:['caseid','fid','status'],codecat:['catid','name','status'],treecode:['cid','catid','status'],journal:['name','journal','status'],coding2:RQDA_SCHEMA.coding};
const query=(db,sql)=>{const r=db.exec(sql)[0];return r?r.values.map(v=>Object.fromEntries(r.columns.map((k,i)=>[k,v[i]]))):[];};
const active=r=>Number(r.status)===1;
const knownVersion=version=>String(version)==='0.2.2';
const quote=(text,start,end)=>Array.from(text).slice(start,end).join('');
const bounds=(text,start,end)=>Number.isSafeInteger(start)&&Number.isSafeInteger(end)&&start>=0&&end>start&&end<=Array.from(text).length;
export function rqdaProjectChoices(db){const records=query(db,'SELECT databaseversion FROM project LIMIT 2');if(records.length!==1)throw Error('RQDA requires exactly one project metadata record; databases are not merged.');return {format:'rqda',projects:[{id:'1',name:'Imported RQDA project'}]};}
export function readRQDA(db,options={}){const names=query(db,"SELECT name FROM sqlite_master WHERE type='table'").map(r=>r.name),tables={},encoding=sqliteTextEncoding(db);rqdaProjectChoices(db);for(const [table,list] of Object.entries(fields)){if(!names.includes(table))continue;const columns=query(db,'PRAGMA table_info("'+table+'")').map(r=>r.name);if((required[table]||[]).some(c=>!columns.includes(c)))throw Error('Invalid RQDA '+table+' table schema.');const selected=list.filter(c=>columns.includes(c));tables[table]=decodeSQLiteTextRows(query(db,'SELECT rowid AS "__rowid",'+sqliteTextSelection(selected,TEXT_FIELDS)+' FROM "'+table+'" LIMIT 200001'),TEXT_FIELDS,encoding);if(tables[table].length>200000)throw Error('RQDA project has too many records for browser import.');}return normalizeRQDA(tables,options);}
export function normalizeRQDA(tables,{projectId,name='Imported RQDA project'}={}){
 const projects=tables.project||[];if(projects.length!==1)throw Error('RQDA requires exactly one project metadata record; databases are not merged.');if(projectId!==undefined&&projectId!==null&&String(projectId)!=='1')throw Error('Selected RQDA project is missing.');const p=projects[0],s=emptyState(name),contract=knownVersion(p.databaseversion),losses=[],excluded=[],records={categoryLinks:[],caseLinks:[]},id=(kind,value)=>'rqda:'+kind+':'+value,prov=(kind,value)=>({application:'rqda',recordType:kind,originalId:String(value)}),rows=k=>tables[k]||[];
 s.description=p.memo||'';s.nativeImport={application:'rqda',projectId:'1',permissionsImported:false,sourceOffsetUnit:contract?'RQDA 0.2.2 GTK character offsets: zero-based Unicode codepoints; exclusive end':'Unverified RQDA version; passage bounds withheld',projectMetadata:{databaseVersion:p.databaseversion||null,created:p.date||null,modified:p.dateM||null},offsetContract:{supportedVersion:'0.2.2',verified:contract,source:'RQDA R/CodesFun.R sindex; R/utils.R UpdateCoding',zeroBased:true,endExclusive:true},losses,excluded,records};
 const docs=rows('source').filter(active),codes=rows('freecode').filter(active),docMap=new Map(),codeMap=new Map();
 s.documents=docs.map(d=>{if(typeof d.file!=='string')throw Error('RQDA source text is missing.');const doc={id:id('source',d.id),name:d.name||'Imported source',text:d.file,memo:d.memo||'',revision:1,sourceRole:'interview',direction:'auto',turns:[],versions:[],attributes:{},excludeAI:true,importProvenance:{...prov('source',d.id),owner:d.owner||null,created:d.date||null,modified:d.dateM||null}};docMap.set(String(d.id),doc);return doc;});
 s.codes=codes.map(c=>{const code={id:id('code',c.id),name:c.name||'Imported code',description:c.memo||'',codable:true,parentId:null,color:c.color||'#537a92',importProvenance:{...prov('freecode',c.id),owner:c.owner||null,created:c.date||null,modified:c.dateM||null}};codeMap.set(String(c.id),code);return code;});
 for(const table of ['coding','coding2'])for(const [index,c] of rows(table).entries()){if(!active(c))continue;const doc=docMap.get(String(c.fid)),code=codeMap.get(String(c.cid)),original=c.__rowid??index+1;if(!doc||!code){excluded.push({kind:table,id:String(original),reason:'Inactive or missing source/code; application excluded.'});continue;}const validBounds=bounds(doc.text,c.selfirst,c.selend),hasStoredQuote=typeof c.seltext==='string',text=hasStoredQuote?c.seltext:contract&&validBounds?quote(doc.text,c.selfirst,c.selend):'',verified=contract&&validBounds&&(!hasStoredQuote||quote(doc.text,c.selfirst,c.selend)===c.seltext),coding={id:id(table,original),documentId:doc.id,codeId:code.id,start:c.selfirst,end:c.selend,text,coder:c.owner||'Imported RQDA coding (author unidentified)',date:c.date||null,status:verified?'coded':'needs_review',sourceRevision:1,memo:c.memo||'',origin:'rqda-import',importProvenance:{...prov(table,original),originalStart:c.selfirst,originalEnd:c.selend,sourceDatabaseVersion:p.databaseversion||null,quoteBasis:hasStoredQuote?'Original seltext':verified?'Current source slice under documented RQDA contract':'Unavailable; original bounds require review'}};s.codings.push(coding);if(!verified)losses.push({kind:'anchor',codingId:coding.id,message:'RQDA version, bounds or exact selected text could not be verified; coding withheld. No unit guessing, boundary adjustment or text reanchoring performed.'});if(c.memo){const citation=verified?{documentId:doc.id,start:c.selfirst,end:c.selend,text,sourceRevision:1,relation:'evidence'}:null;s.memos.push({id:id(table+'-memo',original),title:'Imported coding memo',content:c.memo,author:c.owner||'Imported RQDA memo (author unidentified)',date:c.date||null,documentId:doc.id,codeId:code.id,codingId:coding.id,anchorStatus:verified?'current':'needs_review',...(citation?{...citation,citations:[citation]}:{}),importProvenance:prov(table+'-memo',original)});}}
 s.cases=rows('cases').filter(active).map(c=>({id:id('case',c.id),name:c.name||'Imported case',memo:c.memo||'',documentIds:[],passages:[],attributes:{},importProvenance:{...prov('case',c.id),owner:c.owner||null,created:c.date||null,modified:c.dateM||null}}));
 const caseMap=new Map(s.cases.map(c=>[c.importProvenance.originalId,c]));
 for(const [index,l] of rows('caselinkage').entries()){if(!active(l))continue;const doc=docMap.get(String(l.fid)),which=caseMap.get(String(l.caseid));if(!doc||!which){excluded.push({kind:'caselinkage',id:String(l.__rowid??index+1),reason:'Inactive or missing source/case.'});continue;}const valid=contract&&bounds(doc.text,l.selfirst,l.selend),record={...prov('caselinkage',l.__rowid??index+1),caseId:which.id,documentId:doc.id,originalStart:l.selfirst,originalEnd:l.selend,memo:l.memo||'',owner:l.owner||null,active:valid};records.caseLinks.push(record);if(!valid){losses.push({kind:'case-anchor',message:'Case passage membership has missing or unverified bounds; retained in provenance without broadening it to a whole source.'});continue;}if(l.selfirst===0&&l.selend===Array.from(doc.text).length){if(!which.documentIds.includes(doc.id))which.documentIds.push(doc.id);}else which.passages.push({id:id('case-link',l.__rowid??index+1),documentId:doc.id,start:l.selfirst,end:l.selend,text:quote(doc.text,l.selfirst,l.selend),sourceRevision:1,anchorStatus:'current',actor:l.owner||'Imported RQDA case link (author unidentified)',date:l.date||null});}
 s.categories=rows('codecat').filter(active).map(c=>({id:id('category',c.catid),name:c.name||'Imported category',memo:c.memo||'',parentId:null,importProvenance:prov('codecat',c.catid)}));const categoryMap=new Map(s.categories.map(c=>[c.importProvenance.originalId,c]));
 for(const l of rows('treecode').filter(active)){const code=codeMap.get(String(l.cid)),category=categoryMap.get(String(l.catid));if(!code||!category){excluded.push({kind:'treecode',reason:'Inactive or missing code/category.'});continue;}records.categoryLinks.push({codeId:code.id,categoryId:category.id,memo:l.memo||'',owner:l.owner||null,date:l.date||null});}
 for(const code of s.codes){const links=[...new Set(records.categoryLinks.filter(l=>l.codeId===code.id).map(l=>l.categoryId))];if(links.length===1)code.categoryId=links[0];else if(links.length>1)losses.push({kind:'category-membership',codeId:code.id,message:'Code belongs to several native categories. All memberships retained in provenance; no single active category or duplicate code was inferred.'});}
 s.journals=rows('journal').filter(active).map((j,index)=>({id:id('journal',j.__rowid??index+1),name:j.name||'Imported journal',text:j.journal||'',coder:j.owner||'Imported RQDA journal (author unidentified)',date:j.date||null,modifiedAt:j.dateM||null,importProvenance:prov('journal',j.__rowid??index+1)}));
 s.importNotes=['One-way native RQDA SQLite migration; not a native RQDA exporter and not a verified R/Requal runtime round trip.','Only status=1 sources, codes, coding, cases, case links, categories, category links and journals are activated. Original owner fields describe historical authorship; permissions, users, SQL queries, settings, image paths and binary media are not imported.','RQDA schema 0.2.2 uses zero-based Unicode character positions with exclusive ends. Original seltext must match exactly; where absent, the current source slice is identified explicitly. Unknown versions and stale anchors are withheld for review.','Case passage links remain passage-specific. Multiple code-category memberships remain in provenance where the target codebook cannot represent them.','Source, code, case and category memos remain descriptions; coding memos are preserved on applications and as linked memos. Source direction defaults to auto. No speaker labels or recording timestamps are inferred.','Sources default to excluded from AI pending consent review. File categories, typed attributes, point annotations, image coding and other unsupported ancillary tables are omitted; keep the original database separately.',...losses.map(l=>l.message)];
 validateState(s);return s;
}
