// Common function words per language, used to drop grammatical words from word frequency, clouds and n-grams.
// Lists are deliberately conservative (articles, pronouns, auxiliaries, prepositions, conjunctions and very
// common adverbs) so content words a researcher may want to see are kept. Users can add their own words.
const LISTS={
 en:`a about above after again against all also am an and any are aren't as at be because been before being below between both but by can can't cannot could couldn't did didn't do does doesn't doing don't down during each few for from further had hadn't has hasn't have haven't having he he'd he'll he's her here here's hers herself him himself his how how's i i'd i'll i'm i've if in into is isn't it it's its itself just let's me more most mustn't my myself no nor not now of off on once only or other ought our ours ourselves out over own same shan't she she'd she'll she's should shouldn't so some such than that that's the their theirs them themselves then there there's these they they'd they'll they're they've this those through to too under until up us very was wasn't we we'd we'll we're we've were weren't what what's when when's where where's which while who who's whom why why's will with won't would wouldn't you you'd you'll you're you've your yours yourself yourselves yeah yes okay ok um uh like really gonna wanna`,
 fr:`à afin ai aie aient ais ait as au aucun aussi autre aux avaient avais avait avec avez aviez avions avoir avons ayant c ça car ce ceci cela celle celles celui cependant ces cet cette ceux chaque chez comme comment d dans de des donc dont du elle elles en encore entre es est et étaient étais était étant été êtes étions être eu eux fait faire fois furent fut ici il ils j je jusqu l la là le les leur leurs lui m ma mais me même mes moi moins mon n ne ni nos notre nous on ont or ou où par parce pas peu peut plus pour pourquoi qu quand que quel quelle quelles quels qui sa sans se sera serait ses si sien son sont sous soyez sur t ta tandis te tes toi ton tous tout toute toutes très tu un une vos votre vous y oui non bon ben euh alors voilà`,
 es:`a al algo algunas algunos ante antes aquel aquella aquellas aquellos aquí así como con contra cual cuando de del desde donde dos durante e el él ella ellas ellos en entre era erais eran eras eres es esa esas ese eso esos esta está estaba estaban estado estáis estamos están estar estas este esto estos estoy fue fueron fui fuimos ha había habían han has hasta hay he la las le les lo los más me mi mí mis mucho muy nada ni no nos nosotras nosotros nuestra nuestro o os otra otro para pero poco por porque que qué quien quienes se sea ser si sí sido sin sobre sois somos son soy su sus también tanto te tenemos tener tengo ti tiene tienen todo todos tu tú tus un una uno unos vosotras vosotros vuestra vuestro y ya yo bueno pues eh vale`,
 de:`aber alle allem allen aller alles als also am an ander andere anderem anderen anderer anderes auch auf aus bei bin bis bist da damit dann das dass dein deine dem den denn der des dich die dies diese diesem diesen dieser dieses dir doch dort du durch ein eine einem einen einer eines einig einige er es etwas euch euer eure für gegen gewesen hab habe haben hat hatte hatten hier hin hinter ich ihm ihn ihnen ihr ihre im in indem ins ist ja jede jedem jeden jeder jedes jene jetzt kann kein keine können könnte machen man manche mein meine mich mir mit muss musste nach nicht nichts noch nun nur ob oder ohne sehr sein seine selbst sich sie sind so solche soll sollte sondern sonst über um und uns unser unter viel vom von vor wann war waren warum was weil weiter welche wenn wer werde werden wie wieder will wir wird wo wollen würde zu zum zur zwar zwischen also halt eben genau naja äh`,
 it:`a ad agli ai al alla alle allo anche avere aveva avevano c che chi ci come con contro cosa così cui da dal dalla dalle degli dei del della delle dello di dove e è ed era erano essere gli ha hai hanno ho i il in io la le lei li lo loro lui ma me mi mia mie miei mio molto ne nei nel nella nelle no noi non nostra nostro o per perché più poi quale quando quanto quella quelle quelli quello questa queste questi questo se sei si sia siamo sono su sua sue sui sul sulla suo suoi te ti tra tu tua tuo tutti tutto un una uno vi voi già cioè quindi allora ecco boh insomma`,
 pt:`a ao aos aquela aquelas aquele aqueles aquilo as até com como da das de dela delas dele deles depois do dos e é ela elas ele eles em entre era eram essa essas esse esses esta está estão estas este estes eu foi foram há isso isto já lhe lhes mais mas me mesmo meu meus minha minhas muito na não nas nem no nos nós nossa nossas nosso nossos num numa o os ou para pela pelas pelo pelos por qual quando que quem se sem ser será seu seus só sua suas também te tem têm tinha tu tua tuas teu teus um uma você vocês vos então né tipo pois assim`,
 nl:`aan al alles als altijd andere ben bij daar dan dat de der deze die dit doch doen door dus een eens en er ge geen geweest haar had heb hebben heeft hem het hier hij hoe hun iemand iets ik in is ja je kan kon kunnen maar me meer men met mij mijn moet na naar niet niets nog nu of om omdat onder ons ook op over reeds te tegen toch toen tot u uit uw van veel voor want waren was wat we wel werd wezen wie wij wil worden wordt zal ze zelf zich zij zijn zo zonder zou eigenlijk gewoon even`,
 sv:`alla allt att av blev bli blir blivit de dem den denna deras dess dessa det detta dig din dina ditt du där då efter ej eller en er era ert ett från för ha hade han hans har henne hennes hon honom hur här i icke ingen inom inte jag ju kan kunde man med mellan men mig min mina mitt mot mycket ni nu när någon något några och om oss på samma sedan sig sin sina själv skulle som så sådan till under upp ut utan vad var vara varför varit varje vars vem vi vid vilka vilken vilket vår våra vårt än är åt över ja nej liksom alltså typ`,
 da:`ad af alle alt anden at blev blive bliver da de dem den denne der deres det dette dig din disse dog du efter eller en end er et for fra ham han hans har havde have hende hendes her hos hun hvad hvis hvor i ikke ind jeg jer jo kunne man mange med meget men mig min mine mit mod når ned noget nogle nu og også om op os over på selv sig sin sine sit skal skulle som sådan til ud under var vi vil ville vor været ja nej altså`,
 nb:`alle at av bare begge ble bli blir blitt både da de deg dem den denne der dere deres det dette din disse ditt du eller en enn er et ett etter for fordi fra før ha hadde han hans har henne hennes her hun hva hvem hver hvilke hvilken hvis hvor hvordan hvorfor i ikke ingen inn ja jeg kan kom kun kunne man mange med meg mellom men min mine mitt mot mye ned noe noen nå når og også om opp oss over på samme seg selv sin sine sitt skal skulle slik som så sånn til uten var ved vi vil ville vår være vært å altså liksom`,
 fi:`ei eivät emme en et ette että he heidän heidät heille heillä hän hänen hänet häntä itse ja johon joka jolla jonka jos jossa josta jota jotka kanssa koska kuin kuka kun me meidän meille meillä meitä mikä miksi minä minua minulla minun minut missä mitä mukaan mutta ne niiden niin niitä noin nuo nyt nämä ole olemme olen olet olette oli olimme olin olisi olit olitte olivat olla olleet ollut on ovat se sekä sen siinä siitä sille sillä sinä sinua sinun sitä tai te teidän teille tämä tämän tässä tästä tätä vaan vai vaikka yli niinku tota`,
 pl:`a aby albo ale ani aż bardzo bez bo być był była było były będzie będą ci cię co czy czyli dla do dlaczego dlatego gdy gdzie go i ich im ja jak jako je jego jej jest jestem jeszcze jeśli już ją każdy kiedy kto która które którego której który których lub ma mają mam mi mnie mogą może można mu my na nad nam nas nawet nic nie niech niego niej nim niż no o od oraz on ona one oni ono po pod ponieważ przed przez przy się sobie są ta tak także tam te tego tej ten też to tu tutaj ty tylko tym u w we więc wszystko właśnie z za ze że żeby jakby znaczy`,
 ru:`а без более бы был была были было быть в вам вас весь во вот все всего всех вы где да даже для до его ее ей ему если есть еще же за здесь и из или им их к как когда кто ли либо мне может мы на надо наш не него нее нет ни них но ну о об однако он она они оно от очень по под при с со так также такой там те тем то того тоже той только том ты у уж уже хотя чего чей чем что чтобы чье чья эта эти это я наша наше наши ваш ваша ваше ваши свой своя свое свои мой моя мое мои твой ага вообще типа`,
 tr:`acaba ama aslında az bazı belki biri birkaç birşey biz bu çok çünkü da daha de defa diye eğer en gibi hem hep hepsi her hiç için ile ise kez ki kim mı mu mü nasıl ne neden nerde nerede nereye niçin niye o sanki şey siz şu tüm ve veya ya yani bir ben sen onlar bunu şunu onu evet hayır işte`,
 id:`ada adalah agar akan aku anda apa atau bagi bahwa banyak beberapa begitu belum bisa dalam dan dari dengan di dia ia ini itu jadi jika juga kalau kami kamu karena ke kita lagi lalu maka mana masih mereka nya oleh pada para saat saja sama sangat saya sebagai sedang seperti sudah supaya tapi telah tentang tersebut tetapi untuk yaitu yang ya tidak gak nggak sih dong kok`,
};
export const STOPWORD_LANGUAGES=[['en','English'],['fr','French'],['es','Spanish'],['de','German'],['it','Italian'],['pt','Portuguese'],['nl','Dutch'],['sv','Swedish'],['da','Danish'],['nb','Norwegian (Bokmål)'],['fi','Finnish'],['pl','Polish'],['ru','Russian'],['tr','Turkish'],['id','Indonesian'],['none','No built-in stop list']];
const cache=new Map();
/** The stop-word set for a language code ('none' or unknown gives an empty set). Apostrophes are normalised to '. */
export function stopwordSet(language='en'){if(!cache.has(language))cache.set(language,new Set((LISTS[language]||'').split(/\s+/).filter(Boolean).map(w=>normalizeWord(w))));return cache.get(language);}
export const normalizeWord=w=>String(w).toLocaleLowerCase().replace(/[’ʼ]/g,"'");
export const stopwordCount=language=>stopwordSet(language).size;
