import {unzipSync,strFromU8} from 'fflate';
import {decodeSourceText} from './source-text-import.mjs';
export function parseCSV(text){const rows=[];let row=[],value='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(ch===','&&!quoted){row.push(value);value='';}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(value);if(row.some(v=>v!==''))rows.push(row);row=[];value='';}else value+=ch;}if(quoted)throw Error('Unclosed CSV quotation.');row.push(value);if(row.some(v=>v!==''))rows.push(row);return rows;}
export async function readTable(file,options={}){if(file.size>10000000)throw Error('Choose a table under 10 MB.');if(!file.name.toLowerCase().endsWith('.xlsx'))return parseCSV(decodeSourceText(new Uint8Array(await file.arrayBuffer()),options.encoding||'auto').text);let expanded=0,count=0;const z=unzipSync(new Uint8Array(await file.arrayBuffer()),{filter:e=>{if(++count>5000||(expanded+=e.originalSize)>40000000)throw Error('Expanded table is too large.');return /^xl\/(sharedStrings\.xml|workbook\.xml|_rels\/workbook\.xml\.rels|worksheets\/[^/]+\.xml)$/.test(e.name)&&e.originalSize<20000000;}});if(Object.values(z).reduce((n,b)=>n+b.length,0)>40000000)throw Error('Expanded table is too large.');const xml=k=>{if(!z[k])return null;const doc=new DOMParser().parseFromString(strFromU8(z[k]),'application/xml');if(doc.querySelector('parsererror'))throw Error('Malformed spreadsheet XML.');return doc;};const shared=[...(xml('xl/sharedStrings.xml')?.getElementsByTagName('si')||[])].map(n=>[...n.getElementsByTagName('t')].map(t=>t.textContent).join(''));const first=xml('xl/workbook.xml')?.getElementsByTagName('sheet')[0],id=first?.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id')||first?.getAttribute('r:id'),rel=[...(xml('xl/_rels/workbook.xml.rels')?.getElementsByTagName('Relationship')||[])].find(r=>r.getAttribute('Id')===id);if(rel?.getAttribute('TargetMode')==='External')throw Error('External worksheets are unsupported.');const target=rel?.getAttribute('Target')||'worksheets/sheet1.xml',parts=[];for(const p of (target.startsWith('/')?target.slice(1):'xl/'+target).split('/')){if(p==='..')parts.pop();else if(p&&p!=='.')parts.push(p);}const sheet=xml(parts.join('/'));if(!sheet)throw Error('The first worksheet is missing. Export a flat case table.');return [...sheet.getElementsByTagName('row')].map(row=>{const out=[];for(const cell of row.getElementsByTagName('c')){let index=0;for(const ch of (cell.getAttribute('r')||'A').replace(/\d/g,''))index=index*26+ch.charCodeAt(0)-64;const type=cell.getAttribute('t'),v=cell.getElementsByTagName('v')[0]?.textContent||'';out[index-1]=type==='s'?shared[Number(v)]||'':type==='inlineStr'?[...cell.getElementsByTagName('t')].map(t=>t.textContent).join(''):v;}return Array.from({length:out.length},(_,i)=>out[i]||'');}).filter(r=>r.some(Boolean));}
export function casesFromTable(rows,state,{nameColumn='name',sourceColumn='sources',memoColumn='memo',provenance=null}={}){
 if(rows.length<2)throw Error('Include a header and at least one case.');
 const header=rows[0].map(h=>String(h).trim());if(header.some(h=>!h)||new Set(header).size!==header.length)throw Error('Case table headers must be non-empty and unique.');
 if(!header.includes(nameColumn))throw Error('Choose the column containing case names.');
 const selected=[nameColumn,sourceColumn,memoColumn].filter(k=>k&&header.includes(k));if(new Set(selected).size!==selected.length)throw Error('Choose different columns for names, sources and memos.');
 return rows.slice(1).map((r,index)=>{if(r.length>header.length)throw Error('Case row '+(index+2)+' has more values than headers.');const obj=Object.fromEntries(header.map((k,i)=>[k,r[i]??''])),name=String(obj[nameColumn]).trim();if(!name)throw Error('Case row '+(index+2)+' needs a name.');
 const sources=String(sourceColumn?obj[sourceColumn]||'':'').split('|').map(x=>x.trim()).filter(Boolean).map(name=>{const matches=state.documents.filter(d=>d.id===name||d.name===name);if(matches.length!==1)throw Error('Source '+name+' must identify exactly one source.');return matches[0].id;});
 return {name,documentIds:sources,memo:memoColumn?obj[memoColumn]||'':'',attributes:Object.fromEntries(Object.entries(obj).filter(([k])=>!selected.includes(k))),...(provenance?{importProvenance:{...provenance,row:index+2,columnMapping:{nameColumn,sourceColumn:header.includes(sourceColumn)?sourceColumn:null,memoColumn:header.includes(memoColumn)?memoColumn:null}}}:{})};});
}
