import {cp,slice} from './domain.mjs';
export const wordCount=text=>(String(text||'').match(/[\p{L}\p{N}]+(?:['’][\p{L}\p{N}]+)*/gu)||[]).length;
export const currentCodings=s=>s.codings.filter(c=>!c.deletedAt&&c.status!=='needs_review'&&!c.kind);
export function sourceTurns(d){return (d.turns||[]).map((t,i)=>({...t,index:t.sourceIndex??i,number:(t.sourceIndex??i)+1,documentId:d.id,text:slice(d.text,t.start,t.end),words:wordCount(slice(d.text,t.start,t.end)),restricted:(d.reviewFlags||[]).some(f=>Math.max(f.start,t.start)<Math.min(f.end,t.end))})).filter(t=>t.anchorStatus!=='needs_review');}
export function speakerProfile(d){const map=new Map();for(const t of sourceTurns(d)){if(!map.has(t.speaker))map.set(t.speaker,{speaker:t.speaker,turns:0,words:0});const row=map.get(t.speaker);row.turns++;row.words+=t.words;}const total=[...map.values()].reduce((a,r)=>a+r.words,0);return [...map.values()].map(r=>({...r,share:total?r.words/total:0}));}
export function codingEvidence(s,{documentId='',speaker='',status='all'}={}){const docs=new Map(s.documents.map(d=>[d.id,d]));return currentCodings(s).filter(c=>docs.get(c.documentId)?.sourceRole!=='reference').filter(c=>(!documentId||c.documentId===documentId)&&(status==='all'||(status==='accepted'?c.status==='accepted':c.status==='provisional'))).filter(c=>{const d=docs.get(c.documentId);return !speaker||(d?.turns||[]).some(t=>t.anchorStatus!=='needs_review'&&t.speaker===speaker&&Math.max(t.start,c.start)<Math.min(t.end,c.end));});}
export function excerptGroups(codings){const map=new Map();for(const c of codings){const key=[c.documentId,c.start,c.end].join(':');if(!map.has(key))map.set(key,{key,documentId:c.documentId,start:c.start,end:c.end,text:c.text,codings:[],codeIds:[]});const row=map.get(key);row.codings.push(c);if(!row.codeIds.includes(c.codeId))row.codeIds.push(c.codeId);}return [...map.values()];}
export function themeProfile(s,options={}){const evidence=codingEvidence(s,options);return s.codes.filter(c=>c.codable!==false).map(code=>{const applications=evidence.filter(c=>c.codeId===code.id),excerpts=excerptGroups(applications);return {code,applications,excerpts,count:excerpts.length};}).filter(r=>r.count).sort((a,b)=>b.count-a.count);}
export function themeRelationships(s,options={}){const groups=excerptGroups(codingEvidence(s,options)),map=new Map();for(const excerpt of groups){const ids=[...excerpt.codeIds].sort();for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const key=ids[i]+':'+ids[j];if(!map.has(key))map.set(key,{key,a:ids[i],b:ids[j],excerpts:[]});map.get(key).excerpts.push(excerpt);}}return [...map.values()].map(r=>({...r,count:r.excerpts.length})).sort((a,b)=>b.count-a.count);}
export function codedCoverage(d,codings){const intervals=codings.filter(c=>c.documentId===d.id).map(c=>[c.start,c.end]).sort((a,b)=>a[0]-b[0]);let count=0,end=-1;for(const [a,b] of intervals){if(b<=end)continue;count+=b-Math.max(a,end);end=b;}const total=cp(d.text).length;return {characters:count,total,percent:total?100*count/total:0};}
export function demoReport(s,options={}){const selected=codingEvidence(s,options),rows=themeProfile(s,options),docs=s.documents.filter(d=>d.sourceRole!=='reference'&&(!options.documentId||d.id===options.documentId)),excerpts=excerptGroups(selected);return ['# '+s.name,'',s.demo?'Illustrative demo coding. This is a working example, not a reviewed research finding.':'Working coding summary. Interpretation and attribution require research review.','',`Sources: ${docs.length}. Turns: ${docs.reduce((n,d)=>n+sourceTurns(d).length,0)}. Transcript words: ${docs.reduce((n,d)=>n+wordCount(d.text),0)}. Selected excerpts: ${excerpts.length}. Code applications: ${selected.length}.`, `Scope: ${options.speaker||'All supplied speaker labels'}; coding layer ${options.status||'all'}.`,'','Speaker labels and transcript text are unverified. Word counts do not measure speaking time. Excerpt counts reflect selected demo coding and do not establish thematic prevalence. Restricted passages are omitted from this report.','',...rows.flatMap(({code,excerpts})=>['## '+code.name,'',code.description||'',...excerpts.filter(e=>!docs.find(d=>d.id===e.documentId)?.reviewFlags?.some(f=>Math.max(f.start,e.start)<Math.min(f.end,e.end))).slice(0,3).flatMap(e=>['','> '+e.text.replace(/\n/g,'\n> '),'',`Source: ${docs.find(d=>d.id===e.documentId)?.name}; codepoints ${e.start}–${e.end}; decisions: ${e.codings.map(c=>c.status).join(', ')}.`])]),'','## Review before reporting','Confirm transcript wording, speaker identities, attribution/consent and proposed code definitions. Check each quote in its source. Do not treat this single interview as cross-case evidence.'].join('\n');}
