// Deterministic word-cloud layout: size scale, Archimedean spiral with rectangle collision, rotation, WCAG-checked colour schemes and SVG serialization. Pure; runs in Node and the browser.
export const SCALES=['linear','sqrt','log'],ROTATIONS=['none','mixed','vertical'],SCHEMES=['accent','top','categorical','sequential','source'],BACKGROUNDS={light:'#ffffff',dark:'#15191e'},MIN_WORDS=25,MAX_WORDS=500,MIN_CONTRAST=4.5;
// Categorical palettes chosen per background; every entry is re-checked by ensureContrast before use.
export const PALETTES={light:['#0b5cad','#b3261e','#1b7a3e','#7b3fa6','#9a4d00','#006d75','#a12a68','#5c5f00','#34489a','#7a4a2a'],dark:['#7cb7ff','#ff8a80','#6fd394','#d1a3ff','#ffb25c','#5fd6d6','#ff8fc8','#d4d46a','#a8b4ff','#e0b08a']};
const NEUTRAL={light:'#4a5560',dark:'#c3ccd5'},ACCENT={light:'#0b5cad',dark:'#7cb7ff'},RAMP={light:['#6c7c8c','#0a2f6b'],dark:['#8d9db0','#d6e8ff']};
export const clampWords=n=>Math.max(MIN_WORDS,Math.min(MAX_WORDS,Math.round(Number(n)||100)));
export function seeded(seed=1){let a=(Number(seed)|0)>>>0||1;return ()=>{a=(a+0x6D2B79F5)>>>0;let t=a;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return ((t^(t>>>14))>>>0)/4294967296;};}
const fn=scale=>scale==='log'?Math.log1p:scale==='sqrt'?Math.sqrt:x=>x;
// Normalised position of a count between the smallest and largest count (0..1) under the chosen scale.
export function scalePosition(count,lo,hi,scale='sqrt'){const f=fn(scale);return hi===lo?.5:Math.max(0,Math.min(1,(f(count)-f(lo))/(f(hi)-f(lo))));}
export function fontSize(count,lo,hi,{scale='sqrt',minSize=14,maxSize=64}={}){const a=Math.min(minSize,maxSize),b=Math.max(minSize,maxSize);return Math.round((a+(b-a)*scalePosition(count,lo,hi,scale))*10)/10;}
export function rotationFor(rank,mode='none'){return mode==='vertical'?-90:mode==='mixed'&&rank%3===2?-90:0;}
const hex=c=>{let h=String(c).trim().replace('#','');if(h.length===3)h=[...h].map(x=>x+x).join('');const n=parseInt(h.slice(0,6),16);return Number.isFinite(n)?[(n>>16)&255,(n>>8)&255,n&255]:[0,0,0];},toHex=rgb=>'#'+rgb.map(v=>Math.round(Math.max(0,Math.min(255,v))).toString(16).padStart(2,'0')).join('');
export function luminance(c){const [r,g,b]=hex(c).map(v=>{v/=255;return v<=.03928?v/12.92:((v+.055)/1.055)**2.4;});return .2126*r+.7152*g+.0722*b;}
export function contrast(a,b){const x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);}
export function mix(a,b,t){const x=hex(a),y=hex(b);return toHex(x.map((v,i)=>v+(y[i]-v)*t));}
// Moves a colour toward black (light background) or white (dark background) until it meets the ratio.
export function ensureContrast(color,background,ratio=MIN_CONTRAST){const target=luminance(background)>.18?'#000000':'#ffffff';let c=toHex(hex(color));for(let t=.06;contrast(c,background)<ratio&&t<=1.0001;t+=.06)c=mix(color,target,Math.min(1,t));return contrast(c,background)<ratio?target:c;}
export function backgroundColor(background='light'){return BACKGROUNDS[background]||(/^#/.test(background)?background:BACKGROUNDS.light);}
function sourceCounts(hits=[]){const m=new Map();for(const h of hits)m.set(h.documentId,(m.get(h.documentId)||0)+1);return m;}
// The colour of the source contributing most hits (ties go to the earlier source in the caller's order).
export function dominantSource(hits,order=[]){const m=sourceCounts(hits);let best=null,n=-1,bi=Infinity;for(const [id,c] of m){const i=order.indexOf(id),idx=i<0?Infinity:i;if(c>n||(c===n&&idx<bi)){best=id;n=c;bi=idx;}}return best;}
export function wordColor(word,{scheme='top',background='light',accent,topN=10,reverse=false,lo=1,hi=1,scale='sqrt',sourceOrder=[]}={}){const bg=backgroundColor(background),mode=luminance(bg)>.18?'light':'dark',palette=PALETTES[mode];let c;if(scheme==='accent')c=accent||ACCENT[mode];else if(scheme==='top')c=word.rank<topN?accent||ACCENT[mode]:NEUTRAL[mode];else if(scheme==='categorical')c=palette[word.rank%palette.length];else if(scheme==='sequential'){const [a,b]=reverse?[...RAMP[mode]].reverse():RAMP[mode];c=mix(a,b,scalePosition(word.count,lo,hi,scale));}else if(scheme==='source'){const id=dominantSource(word.hits,sourceOrder),i=sourceOrder.indexOf(id);c=i<0?NEUTRAL[mode]:palette[i%palette.length];}else c=NEUTRAL[mode];return ensureContrast(c,bg);}
// Legend colours for the source scheme, in the caller's source order.
export function sourceLegend(sources=[],background='light'){const bg=backgroundColor(background),palette=PALETTES[luminance(bg)>.18?'light':'dark'];return sources.map((s,i)=>({id:s.id??s,name:s.name??String(s.id??s),color:ensureContrast(palette[i%palette.length],bg)}));}
export function estimateWidth(text,size,charWidth=.6){return Array.from(String(text)).length*size*charWidth;}
// Spatial hash of placed rectangles so collision checks stay near O(1) per candidate.
function grid(width,height,cell=24){const cols=Math.ceil(width/cell)+1,rows=Math.ceil(height/cell)+1,cells=Array.from({length:cols*rows},()=>[]),rects=[];let last=-1;const meets=(r,o)=>r.x0<o.x1&&r.x1>o.x0&&r.y0<o.y1&&r.y1>o.y0,range=r=>[Math.max(0,Math.floor(r.x0/cell)),Math.min(cols-1,Math.floor(r.x1/cell)),Math.max(0,Math.floor(r.y0/cell)),Math.min(rows-1,Math.floor(r.y1/cell))];return {hit(r){if(last>=0&&meets(r,rects[last]))return true;const c0=Math.max(0,Math.floor(r.x0/cell)),c1=Math.min(cols-1,Math.floor(r.x1/cell)),r0=Math.max(0,Math.floor(r.y0/cell)),r1=Math.min(rows-1,Math.floor(r.y1/cell));for(let y=r0;y<=r1;y++)for(let x=c0;x<=c1;x++){const list=cells[y*cols+x];for(let i=0;i<list.length;i++)if(meets(r,rects[list[i]])){last=list[i];return true;}}return false;},add(r){const j=rects.push(r)-1,[c0,c1,r0,r1]=range(r);for(let y=r0;y<=r1;y++)for(let x=c0;x<=c1;x++)cells[y*cols+x].push(j);}};}
export function overlaps(a,b){return a.x0<b.x1&&a.x1>b.x0&&a.y0<b.y1&&a.y1>b.y0;}
// items: [{term,count,hits?}] (any order). Returns placed words with centre x/y, box, rotation and colour, plus the words that did not fit.
export function layoutCloud(items=[],options={}){const {width=800,height=480,maxWords=100,scale='sqrt',minSize=14,maxSize=64,rotation='none',seed=1,padding=2,charWidth=.6,lineHeight=1.15,measure,scheme='top',background='light',accent,topN=10,reverse=false,sources=[]}=options,W=Math.max(50,width),H=Math.max(50,height),top=[...items].filter(w=>w&&w.count>0&&String(w.term??'').length).sort((a,b)=>b.count-a.count||String(a.term).localeCompare(String(b.term))).slice(0,clampWords(maxWords)),hi=top[0]?.count||1,lo=top.at(-1)?.count||1,rand=seeded(seed),g=grid(W,H),sourceOrder=sources.map(s=>s?.id??s),words=[],dropped=[],failed=[],e=W/H,cx=W/2,cy=H/2,rMax=Math.hypot(W/e,H)/2+2;
 for(const id of top.flatMap(w=>(w.hits||[]).map(h=>h.documentId)))if(!sourceOrder.includes(id))sourceOrder.push(id);
 top.forEach((item,rank)=>{const term=String(item.term),size=fontSize(item.count,lo,hi,{scale,minSize,maxSize}),rotate=rotationFor(rank,rotation),tw=measure?measure(term,size,rank<topN?700:500):estimateWidth(term,size,charWidth),th=size*lineHeight,bw=(rotate?th:tw)+padding*2,bh=(rotate?tw:th)+padding*2,base={term,count:item.count,rank,size,rotate},angle=rand()*Math.PI*2,jx=(rand()-.5)*W*.1,jy=(rand()-.5)*H*.1;if(bw>W||bh>H||failed.some(f=>f.rotate===rotate&&f.bw<=bw&&f.bh<=bh)){dropped.push({...base,reason:bw>W||bh>H?'larger than the canvas':'no space left'});return;}let spot=null;const b=Math.max(1,Math.min(3,Math.min(bw,bh)/24));for(let t=0;!spot;t+=Math.max(.1,2.5/(t*b+1))){const r=t*b;if(r>rMax)break;const x=cx+jx*Math.min(1,r/40+.2)+e*r*Math.cos(t+angle),y=cy+jy*Math.min(1,r/40+.2)+r*Math.sin(t+angle),box={x0:x-bw/2,y0:y-bh/2,x1:x+bw/2,y1:y+bh/2};if(box.x0<0||box.y0<0||box.x1>W||box.y1>H||g.hit(box))continue;spot={x,y,box};}if(!spot){failed.push({rotate,bw,bh});dropped.push({...base,reason:'no space left'});return;}g.add(spot.box);const ids=sourceCounts(item.hits);const word={...base,x:Math.round(spot.x*10)/10,y:Math.round(spot.y*10)/10,width:rotate?th:tw,height:rotate?tw:th,box:spot.box,weight:rank<topN?700:500,sources:ids.size,hits:item.hits};word.color=wordColor(word,{scheme,background,accent,topN,reverse,lo,hi,scale,sourceOrder});words.push(word);});
 return {width:W,height:H,background:backgroundColor(background),words,dropped,considered:top.length,total:items.length,occurrences:items.reduce((n,w)=>n+(w.count||0),0),sourceOrder,options:{scale,minSize,maxSize,rotation,scheme,seed,maxWords:clampWords(maxWords)}};}
export function escapeXML(value){return String(value??'').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F￾￿]/g,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));}
export function cloudCaption({scope='',stopList='',hidden=[],include=[],layout,shown,considered,total,dropped,occurrences}={}){const s=shown??layout?.words.length??0,c=considered??layout?.considered??s,t=total??layout?.total??c,d=dropped??layout?.dropped.length??0,o=occurrences??layout?.occurrences;return [scope&&'Scope: '+scope+'.','Stop list: '+(stopList||'none')+(hidden.length?'; hidden by viewer: '+hidden.join(', '):'')+'.',include.length?'Include-only list: '+include.join(', ')+'.':'','Showing '+s+' of '+c+' terms considered ('+t+' distinct terms'+(o!=null?', '+o+' occurrences':'')+')'+(d?'; '+d+' did not fit':'')+'.','Sizes and counts describe word frequency in the selected text, not importance.'].filter(Boolean).join(' ');}
function wrap(text,chars){const out=[];let line='';for(const w of String(text).split(/\s+/)){if(line&&(line+' '+w).length>chars){out.push(line);line=w;}else line=line?line+' '+w:w;}if(line)out.push(line);return out;}
export function cloudSVG(layout,{title='Word cloud',caption='',fontFamily='system-ui, -apple-system, Segoe UI, sans-serif'}={}){const {width:W,height:H,background:bg}=layout,dark=luminance(bg)<=.18,capColor=ensureContrast(dark?NEUTRAL.dark:NEUTRAL.light,bg),fs=12,lines=caption?wrap(caption,Math.max(20,Math.floor((W-24)/(fs*.55)))):[],total=H+(lines.length?lines.length*fs*1.4+16:0),f=escapeXML(fontFamily);const text=layout.words.map(w=>'<text x="'+w.x+'" y="'+w.y+'" font-size="'+w.size+'" font-weight="'+w.weight+'" fill="'+w.color+'" text-anchor="middle" dominant-baseline="central"'+(w.rotate?' transform="rotate('+w.rotate+' '+w.x+' '+w.y+')"':'')+'><title>'+escapeXML(w.term+': '+w.count+' occurrence'+(w.count===1?'':'s')+' in '+w.sources+' source'+(w.sources===1?'':'s'))+'</title>'+escapeXML(w.term)+'</text>').join('');const cap=lines.map((l,i)=>'<text x="12" y="'+(H+12+fs+i*fs*1.4)+'" font-size="'+fs+'" fill="'+capColor+'">'+escapeXML(l)+'</text>').join('');return '<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" width="'+W+'" height="'+Math.ceil(total)+'" viewBox="0 0 '+W+' '+Math.ceil(total)+'" role="img" aria-labelledby="wc-title wc-desc" font-family="'+f+'"><title id="wc-title">'+escapeXML(title)+'</title><desc id="wc-desc">'+escapeXML(caption)+'</desc><rect width="100%" height="100%" fill="'+bg+'"/>'+text+cap+'</svg>';}
